crypto-tests/src/hash.rs

The `new_tests!` macro can now be used with a trailing new line, i.e.:
```
new_tests!(
"test1",
"test2",
);
```

crypto-tests: support trailing newlines in the new_tests! macro

---

byte-tools/src/write_slice.rs

both said little endian, changed the big endian one to the right comment

fix to documentation (correct endianess comment)

---

hex-literal/src/lib.rs

The extra backtick breaks formatting in docs.rs

Removes unnecessary backtick from hex-literal doc

---

block-buffer/Cargo.toml

byteorder:1.0.0 does not export byteorder::BE.
It was added in byteorder:1.1.0.
Noticed in https://github.com/pest-parser/pest/pull/390.

Make block-buffer minimal-versions correct

---

opaque-debug/src/lib.rs

This avoids a compiler error when used with edition 2015 std crates that don't have an std feature.

Don't depend on user crate's std feature

---

hex-literal/src/lib.rs

When including this library in a crate with `#![no_std]` forces the std library to be included. Thanks!

add no_std to hex-literal

---

byte-tools/src/lib.rs

`byte-tools/src/lib.rs` incorrectly describes the panic condition

Fix incorrect comment

---

block-buffer/Cargo.toml
block-buffer/src/lib.rs

One of my projects has a bunch of duplicate versions of generic-array, through block-buffer (from sha-2), crypto-mac (through hmac) and digest (through hmac and sha2) -- all of them through usage in postgres-protocol. Here's a start at fixing this up.

Bump generic array

---

Cargo.toml
collectable/Cargo.toml
collectable/LICENSE-APACHE
collectable/LICENSE-MIT
collectable/src/lib.rs

This crate provides a set of traits that abstract over various `Vec`-like collection types.
They're useful for the buffer management the `aead` crate presently does using the `Buffer` trait:
https://docs.rs/aead/0.2.0/aead/trait.Buffer.html

collectable: initial crate

---

collectable/src/lib.rs

The previous APIs consumed the underlying iterators even in the event there was insufficient capacity in the collection.
By borrowing them rather than consuming them, we can leave the unconsumed elements in the iterator rather than losing them.

collectable: borrow iterators rather than consume them

---

collectable/src/lib.rs

Fallible push which returns the original item in the event the underlying collection is full.

collectable: add TryPush trait

---

collectable/src/lib.rs

This finishes out the changes from #44 by borrowing the iterator when `try_collect()`ing it.
This allows potentially recovering the values within an iterator if the `try_collect()` operation fails.

collectable: have TryCollect borrow iterator

---

collectable/CHANGELOG.md
collectable/Cargo.toml

- `TryPush` trait ([#45])
- Borrow iterators rather than consume them ([#44], [#46])
[#46]: https://github.com/RustCrypto/utils/pull/46
[#45]: https://github.com/RustCrypto/utils/pull/45
[#44]: https://github.com/RustCrypto/utils/pull/44

collectable v0.0.2

---

collectable/src/lib.rs

...and restore the original `IntoIterator` bounds.
A `&mut I: Iterator` impls `IntoIterator` so there is no need to borrow as the borrowed case is covered by the `IntoIterator` bound.

collectable: revert iterator borrow

---

block-buffer/Cargo.toml

The `RustCrypto/traits` and `RustCrypto/block-ciphers` repos are both bumped to this version already.

block-buffer: bump generic array to v0.14

---

hex-literal/hex-literal-impl/src/lib.rs

Currently, rustc does not pass the exact original `TokenStream` to
proc-macros in several cases. This has many undesirable effects, such as
losing correct location information in error message.
See https://github.com/rust-lang/rust/issues/43081 for more details
In the future, rustc will begin passing the correct `TokenStream` to
proc-macros. As a result, some tokens may be wrapped in a
`TokenTree::Group` with `Delimiter::None` (when the tokens originally
came from a `macro_rules!`) macro expansion.
I've determined that this change will cause your crate to stop working
on some inputs. This PR updates `hex-literal-impl` to be compatible with both the
old and new `TokenStream` contents.
If you have any questions, feel free to ask me. See https://github.com/rust-lang/rust/issues/72622 for …

Handle `Group`s with `Delimiter::None`

---

opaque-debug/Cargo.toml
opaque-debug/src/lib.rs
opaque-debug/tests/mod.rs

The macro is renamed to `implement`, which allows to use `opaque_debug::implement!(Foo);`. Additionally the crate is migrated to 2018 edition and a simple test is added.

opaque-debug v0.3.0

---

Cargo.toml
cpuid-bool/Cargo.toml
cpuid-bool/src/lib.rs

A specialized alternative to `is_x86_feature_detected`. This crate is no-std friendly and caches `bool`, instead of all CPUID flags. I plan to use it for SHA-1 and SHA-2 crates, but it could be usefull for other crates as well, e.g. for `chacha20`.

Add cpuid-bool crate

---

blobby/CHANGELOG.md
blobby/Cargo.toml
blobby/examples/convert.rs
blobby/src/lib.rs

Added `Blob5Iterator` (I plan to use it for AEAD), removed `byteroder` from non-dev dependencies, bumped to 2018 edition.
Apart from the MSRV bump v0.2 is fully compatible with v0.1.

blobby v0.2

---

Cargo.lock
cpuid-bool/CHANGELOG.md
cpuid-bool/Cargo.toml
cpuid-bool/src/lib.rs

cpuid-bool: fix SGX support

---

cpuid-bool/CHANGELOG.md
cpuid-bool/src/lib.rs

cpuid-bool: fix SGX support (take 2)

---

.github/workflows/blobby.yml
.github/workflows/cpuid-bool.yml
Cargo.lock
blobby/examples/convert.rs

Only Rust 1.39 will be tested, even though `blobby` and `cpuid-bool` should work on earlier versions (1.36 and 1.32 respectively).
Closes #71.

Fix MSRV tests

---

.github/workflows/const-oid.yml
Cargo.lock
Cargo.toml
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/LICENSE-APACHE
const-oid/LICENSE-MIT
const-oid/src/lib.rs

This is an extraction of the const OID support added to the `elliptic-curve` crate in RustCrypto/traits#240.

const-oid: initial crate

---

Cargo.lock
block-padding/CHANGELOG.md
block-padding/Cargo.toml
block-padding/src/lib.rs

This primarily needed for correct deriving of `Clone` for block modes.

block-padding: derive Copy, Clone, and Debug traits

---

.github/workflows/const-oid.yml
.github/workflows/workspace.yml
const-oid/src/lib.rs

~~Attempting to use the new `const fn` features set to ship in 1.46, however it seems this may not be a good idea until const panic support ships and malformed OIDs can panic at compile time~~
Uses a workaround proposed by @rodrimati1992 below to allow a limited degree of compile-time const OID validation when used in a `const` context (which is what this crate is designed for, after all).

const-oid validation

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Validate OIDs are well-formed; MSRV 1.46+ ([#76])
[#76]: https://github.com/RustCrypto/utils/pull/76

const-oid v0.2.0

---

Cargo.lock
cpuid-bool/CHANGELOG.md
cpuid-bool/Cargo.toml
cpuid-bool/src/lib.rs

The new API creates a module which contains `InitToken` zero sized type. The only way to create a value of this type is via functions which ensure that initialization code has been executed. It should be slightly more efficient for our use-cases, since initialization branch can be eliminated from methods which work with initialized algorithm (e.g. `update` and `encrypt_blocks/decrypt_blocks`).
In future it could be beneficial to add "cpuid enums", i.e. macro which would generate code not for a `bool`, but for a user-specified enum.

Improve cpuid-bool efficiency

---

Cargo.lock
const-oid/Cargo.toml
const-oid/README.md
const-oid/src/lib.rs

This commit adds backing storage to `ObjectIdentifier` and with it the ability to parse them at runtime from BER/DER bytestrings and dot-delimited strings.

const-oid: byte and string parsers

---

pkcs8/src/algorithm.rs
pkcs8/src/asn1.rs
pkcs8/tests/lib.rs

Otherwise it's referenced as `private_key_info.algorithm.algorithm` which feels redundant.
This doesn't technically match the name in the ASN.1 schema, however the documentation addresses that.

pkcs8: rename AlgorithmIdentifier `algorithm` field => `oid`

---

pkcs8/src/private_key_info.rs

Omits the actual private key data to avoid leaking it in e.g. logs

pkcs8: add `Debug` impl for `PrivateKeyInfo`

---

.github/workflows/pkcs8.yml
pkcs8/Cargo.toml
pkcs8/src/document.rs
pkcs8/src/lib.rs
pkcs8/src/pem.rs
pkcs8/src/private_key_info.rs
pkcs8/tests/lib.rs

Refactors the previous `pkcs::pem::Document` type into a more general-purpose heap-backed `pkcs8::Document` type.
This type's invariant is to ensure it contains a valid PKCS#8 document which will always parse successfully as `PrivateKeyInfo`.

pkcs8: extract `Document` type

---

pkcs8/src/document.rs
pkcs8/src/lib.rs

Adds a trait for deserializing PKCS#8 encoded private keys which wraps up parsing DER into `PrivateKeyInfo` and, when the `pem` feature is enabled, parsing it from PEM as well.

pkcs8: add FromPkcs8 trait

---

pkcs8/src/document.rs
pkcs8/src/lib.rs
pkcs8/src/pem.rs
pkcs8/src/spki.rs
pkcs8/tests/private_key.rs
pkcs8/tests/public_key.rs

Generalizes PEM support so it can support both public and private keys, splitting `pkcs8::Document` into `pkcs8::PublicKeyDocument` and `pkcs8::PrivateKeyDocument`.

pkcs8: PEM support for decoding SubjectPublicKeyInfo

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs
pkcs8/Cargo.toml

- Byte and string parsers ([#89])
[#89]: https://github.com/RustCrypto/utils/pull/89

const-oid v0.3.0

---

pkcs8/src/lib.rs
pkcs8/src/traits.rs

Also renames the former `FromPkcs8` trait to `FromPrivateKey`.

pkcs8: add `FromPublicKey` trait

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Impl `TryFrom<&[u32]>` for ObjectIdentifier ([#105])
[#105]: https://github.com/RustCrypto/utils/pull/105

const-oid v0.3.1

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Documentation improvements ([#107])
[#107]: https://github.com/RustCrypto/utils/pull/107

const-oid v0.3.2

---

const-oid/src/lib.rs

Removes some obsolete descriptions of how this crate worked previously.

const-oid: documentation improvements

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Documentation improvements ([#112])
[#112]: https://github.com/RustCrypto/utils/pull/110

const-oid v0.3.4

---

pkcs8/src/traits.rs

Adds the following methods gated on the `std` feature:
- `pkcs8::FromPrivateKey::{load_pkcs8_der, load_pkcs8_pem}`
- `pkcs8::FromPublicKey::{load_public_key_der, load_public_key_pem}`

pkcs8: add helper methods to load keys from the local filesystem

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Helper methods to load keys from the local filesystem ([#115])
[#115]: https://github.com/RustCrypto/utils/pull/115

pkcs8 v0.1.1

---

.github/workflows/const-oid.yml
const-oid/Cargo.toml
const-oid/src/lib.rs

Support for serializing OIDs as ASN.1 BER

const-oid: add `ObjectIdentifier::{write_ber, to_ber}` methods

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- `ObjectIdentifier::{write_ber, to_ber}` methods ([#118])
[#118]: https://github.com/RustCrypto/utils/pull/118

const-oid v0.3.5

---

pkcs8/Cargo.toml
pkcs8/src/algorithm.rs
pkcs8/src/asn1.rs
pkcs8/src/asn1/decoder.rs
pkcs8/src/asn1/encoder.rs
pkcs8/src/lib.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs
pkcs8/tests/private_key.rs

Adds support for encoding `AlgorithmIdentifier` and `PrivateKeyInfo`

pkcs8: DER encoding support

---

pkcs8/src/document.rs
pkcs8/src/pem.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs
pkcs8/tests/private_key.rs
pkcs8/tests/public_key.rs

Support for encoding keys in RFC 7468 "PEM encoding" format.

pkcs8: PEM encoder support

---

pkcs8/src/document.rs
pkcs8/src/lib.rs
pkcs8/src/pem.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs
pkcs8/src/traits.rs
pkcs8/tests/public_key.rs

Support for serializing the following as PEM:
- `PrivateKeyInfo`, `SubjectPublicKeyInfo`
- `PrivateKeyDocument`, `PublicKeyDocument`
- Trait-based serialization via `ToPrivateKey`, `ToPublicKey`

pkcs8: PEM serialization support

---

pkcs8/src/document.rs
pkcs8/src/traits.rs
pkcs8/tests/private_key.rs
pkcs8/tests/public_key.rs

Also use them to impl the trait methods to load files, and add additional tests.

pkcs8: add methods to load document types from files

---

pkcs8/src/document.rs
pkcs8/src/traits.rs

Support for writing keys to files when the `std` feature is enabled.
On Unix platforms, this also takes care of setting restricted file permissions so private keys aren't world/group readable.

pkcs8: file writing methods for public/private keys

---

pkcs8/src/document.rs
pkcs8/src/traits.rs
pkcs8/tests/private_key.rs
pkcs8/tests/public_key.rs

Renames methods which read data from files to be prefixed with `read_*`
This is more consistent with Rust's `io::Read` trait.

pkcs8: rename `load_*_file` methods to `read_*_file`

---

pkcs8/src/algorithm.rs
pkcs8/src/asn1/decoder.rs
pkcs8/src/asn1/encoder.rs
pkcs8/src/document.rs
pkcs8/src/error.rs
pkcs8/src/pem.rs

The previous opaque `Error` makes it impossible to distinguish from decoding errors (i.e. malformed ASN.1 DER) versus common filesystem errors which might occur, such as files not existing or permission errors.
This commit adds a very simple error enum which makes it possible to distinguish these cases and provides better error messages when these events occur.

pkcs8: error enum

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- File writing methods for public/private keys ([#126])
- Methods for loading `*Document` types from files ([#125])
- DER encoding support ([#120], [#121])
- PEM encoding support ([#122], [#124])
- `ToPrivateKey`/`ToPublicKey` traits ([#123])
- `Error` enum ([#128])
- Rename `load_*_file` methods to `read_*_file` ([#127])
[#128]: https://github.com/RustCrypto/utils/pull/128
[#127]: https://github.com/RustCrypto/utils/pull/127
[#126]: https://github.com/RustCrypto/utils/pull/126
[#125]: https://github.com/RustCrypto/utils/pull/125
[#124]: https://github.com/RustCrypto/utils/pull/124
[#123]: https://github.com/RustCrypto/utils/pull/123
[#122]: https://github.com/RustCrypto/utils/pull/122
[#121]: https://github.com/RustCrypto/utils/pull/121
[#120]: …

pkcs8 v0.2.0

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- rustdoc improvements ([#130])
[#130]: https://github.com/RustCrypto/utils/pull/130

pkcs8 v0.2.1

---

pkcs8/src/algorithm.rs
pkcs8/src/asn1/encoder.rs
pkcs8/tests/private_key.rs
pkcs8/tests/public_key.rs

The immediate goal of this change is to ensure Ed25519 keys are encoded with AlgorithmIdentifiers that match keys generated by OpenSSL.
The `parameters` field of `AlgorithmIdentifier` is defined as being optional, and Ed25519 keys take advantage of this and completely omit any sort of `parameters` from the ASN.1 SEQUENCE.
The previous encoding logic hardcoded the RSA encoding behavior defined in RFC 3279 Section 2.3.1:
> The parameters field MUST have ASN.1 type NULL for this
> algorithm identifier.
However, this encoding appears to be a sort of unique historical accident specific to RSA.
While we could pursue a solution that doesn't require special casing RSA, it would be a breaking API change at the very least. It would also complicate the API for (all?) non-RSA algorithms.

pkcs8: special case RSA AlgorithmIdentifier parameters encoding

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Decoding/encoding support for Ed25519 keys ([#134], [#135])
[#135]: https://github.com/RustCrypto/utils/pull/135
[#134]: https://github.com/RustCrypto/utils/pull/134

pkcs8 v0.2.2

---

const-oid/src/lib.rs

X.660 uses the term "arc" to describe the components of an OID.
This commit renames "nodes" (which is more of an informal term) to "arcs" to reflect this.

const-oid: rename nodes to arcs

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs
pkcs8/Cargo.toml

- `Arcs` iterator ([#141], [#142])
- Rename "nodes" to "arcs" ([#142])
- Layout optimization ([#143])
- Refactor and improve length limits ([#144])
[#144]: https://github.com/RustCrypto/utils/pull/144
[#143]: https://github.com/RustCrypto/utils/pull/143
[#142]: https://github.com/RustCrypto/utils/pull/142
[#141]: https://github.com/RustCrypto/utils/pull/141

const-oid v0.4.0

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

*NOTE:* this is technically a breaking change from v0.3.0 which was released earlier today. However, after v0.3.1 is released, v0.3.0 will be yanked and is hopefully not in use by anyone yet.
- Bump `const-oid` dependency to v0.4 ([#145])
[#145]: https://github.com/RustCrypto/utils/pull/145

pkcs8 v0.3.1

---

pkcs8/src/algorithm.rs

Adds a convenience method to retrieve the `parameters` of an `AlgorithmIdentifier` as an `ObjectIdentifier` without having to match on the intermediate `AlgorithmParameters` enum.

pkcs8: add `AlgorithmIdentifier::parameters_oid`

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- `AlgorithmIdentifier::parameters_oid` method ([#148])
[#148]: https://github.com/RustCrypto/utils/pull/148

pkcs8 v0.3.2

---

der/src/encode.rs
der/src/length.rs
der/src/lib.rs
pkcs8/src/algorithm.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs

Small cleanup and consistency improvement.
It may be possible to eliminate this module in the future, or it might make sense to make it the one place for all length-related functionality which could be useful.
For now, it gets this code out of the way to permit more refactoring.

der: extract `length` module

---

der/src/decode.rs
der/src/encode.rs
der/src/error.rs
der/src/length.rs
der/src/tag.rs
pkcs8/src/algorithm.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs

Adds a lambda argument to the `nested` function, having it perform TLV decoding and yielding the decoded tag and value to the lambda.
Also adds a set of new functions for parsing fields with expected tags, including a general purpose `tagged` for expecting a particular tag, and ones for the supported ASN.1 types presently used by the `pkcs8` crate.

der: refactor decoder using lambdas

---

der/src/any.rs
der/src/decoder.rs
der/src/length.rs
der/src/optional.rs
der/src/sequence.rs
der/src/tag.rs
pkcs8/src/algorithm.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs

Adds a `Decoder` struct which wraps a slice that's in the process of being decoded, along with ample helper methods for various types which simplify writing decoders.

der: `Decoder` struct

---

der/src/any.rs
der/src/bit_string.rs
der/src/byte_slice.rs
der/src/decoder.rs
der/src/encoder.rs
der/src/error.rs
der/src/integer.rs
der/src/length.rs
der/src/lib.rs
der/src/null.rs
der/src/octet_string.rs
der/src/oid.rs
der/src/sequence.rs
der/src/tag.rs
der/src/traits.rs

Adds a newtype for byteslices that provides a central place to check the `Length::max()` invariant inforced by this library.
Uses this newly introduced type to impl `Any`, `BitString`, `OctetString`, and `Sequence`.
This eliminates the last of the `Result::expect` calls in this library and moves it closer to being panic-free.

der: extract `ByteSlice` type

---

der/src/asn1/sequence.rs
der/src/encoder.rs

DRYs out computing the length of the inner body of a SEQUENCE (sans tag and length prefix) into a single function.

der: extract `sequence::encoded_len_inner()`

---

der/src/byte_slice.rs
der/src/tag.rs

Adds `Display` impl with upper case type names (e.g. "OBJECT IDENTIFIER") and a `Debug` impl with the hex octet and the type name:
Tag(0x06: OBJECT IDENTIFIER)

der: `Debug` and `Display` impls for `Tag`

---

der/src/traits.rs
pkcs8/src/algorithm.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs

Unfortunately this adds the `Decodable` lifetime to `Message`, but I'm not sure there's much that can be done about that.
I tried HRTBs but encountered HRTB-related errors (e.g. "error: implementation of `TryFrom` is not general enough") so it seemed simpler to just add a lifetime to `Message`.

der: bound `Message` on `Decodable`

---

der/src/asn1/any.rs
der/src/asn1/bit_string.rs
der/src/asn1/boolean.rs
der/src/asn1/integer.rs
der/src/asn1/null.rs
der/src/asn1/octet_string.rs
der/src/asn1/sequence.rs
der/src/decoder.rs
der/src/encoder.rs
der/src/error.rs
der/src/header.rs
der/src/length.rs
der/src/lib.rs
der/src/tag.rs
der/src/traits.rs
pkcs8/src/algorithm.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs

Renames the previous `Error` enum to `ErrorKind`, and adds an `Error` struct with a `::kind()` method as well as an optional position where the error occurred to assist in debugging.
Also adds a proper `Display` impl to `ErrorKind` with messages about each of the variants.

der: error handling improvements

---

der/src/asn1/any.rs
der/src/decoder.rs
der/src/error.rs
der/src/lib.rs
der/src/tag.rs
der/src/traits.rs

Adds a heavily-commented code example for how to define, encode, and decode ASN.1 DER messages.

der: add "Usage" section to rustdoc

---

der/src/asn1/bit_string.rs
der/src/asn1/integer.rs
der/src/asn1/octet_string.rs
der/src/lib.rs

Adds a type which provides raw access to the underlying bytes of an ASN.1 INTEGER which can be used for decoding/encoding "big integer" types such as cryptographic keys.
Note that this implementation does not ensure that the encoding of such integers is canonical. For now it's documented that the user of the `RawInteger` type must perform such canonicalization.
This can potentially be addressed in a follow-up PR providing a generic implementation of DER canonicalization rules.

der: add `RawInteger` type

---

const-oid/src/lib.rs

One of the lengths (4) was mishandled, which prevented code from compiling when used in a const context.

const-oid: fix bug in const initializer

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Bug in const initializer ([#172])
[#172]: https://github.com/RustCrypto/utils/pull/172

const-oid v0.4.1

---

der/src/asn1/any.rs
der/src/asn1/boolean.rs
der/src/asn1/integer.rs
der/src/asn1/null.rs
der/src/asn1/oid.rs
der/src/decoder.rs
der/src/encoder.rs
der/src/length.rs
der/src/lib.rs
der/src/tag.rs
der/src/traits.rs
pkcs8/src/private_key_info.rs

Adds some basic tests for encoding/decoding, including ones for various ASN.1 types and the `Decoder` and `Encoder` types themselves.

der: assorted tests

---

der/src/decoder.rs
der/src/lib.rs
pkcs8/src/algorithm.rs
pkcs8/src/spki.rs

...on the nested decoder it creates.
This changes the API to have the `FnOnce` callback for decoding a sequence borrow the decoder rather than passing it by value.
This allows the caller function to retain ownership, and with that it can call finish automatically.

der: have `Decoder::sequence` call `::finish` automatically

---

pkcs8/src/algorithm.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs

Gets rid of some redundant boilerplate

pkcs8: use DER encoding helpers

---

der/src/asn1/any.rs
der/src/asn1/sequence.rs
der/src/decoder.rs
pkcs8/src/algorithm.rs
pkcs8/src/private_key_info.rs
pkcs8/src/spki.rs

DRYs out the parsing of fields nested in `Sequence` data into a new `Sequence::decode_nested` method.

der: extract `Sequence::decode_nested`

---

Cargo.lock
Cargo.toml
der/Cargo.toml
der/derive/CHANGELOG.md
der/derive/Cargo.toml
der/derive/README.md
der/derive/src/lib.rs
der/src/lib.rs

Adds a preliminary custom derive macro for the `der::Message` crate which works on any struct whose fields impl `Decodable` and `Encodable`.

der_derive: custom derive support for the `der` crate

---

der/derive/src/lib.rs
der/src/error.rs
der/src/lib.rs

Adds a field attribute for providing a type hint when decoding/encoding messages.
This can be used to implement intermediate conversions, e.g. in the event a field doesn't directly implement `Decodable` and `Encodable`.

der: #[asn1(type = "...")] custom derive attribute

---

pkcs8/src/lib.rs

PKCS#8 decoders/encoders need custom DER format support in order to parse the contents of private and public key fields.
Re-exporting the version of the `der` crate used by `pkcs8` allows them to easily access this while still gating the functionality on the crate-as-a-feature.

pkcs8: re-export the `der` crate

---

pkcs8/Cargo.toml

Since it's re-exported, even though the `pkcs8` crate doesn't use it, it's nice to activate the feature anyway just in case downstream users of the `der` crate want it.

pkcs8: activate `der/std`

---

der/src/asn1.rs
der/src/asn1/sequence.rs
der/src/lib.rs

Provides access to `der::sequence::encoded_len`, which is helpful for lower-level use cases.

der: make `sequence` module public

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Use `der` crate for decoding/encoding ASN.1 DER ([#153], [#180])
[#153]: https://github.com/RustCrypto/utils/pull/153
[#180]: https://github.com/RustCrypto/utils/pull/180

pkcs8 v0.3.3

---

.github/workflows/der.yml
Cargo.lock
der/Cargo.toml
der/src/asn1.rs
der/src/asn1/big_integer.rs
der/src/asn1/bit_string.rs
der/src/asn1/integer.rs
der/src/asn1/octet_string.rs
der/src/lib.rs

Replaces the previous `RawInteger` type (which did not properly enforce DER encoding invariants) with a `BigUInt` type which properly handles decoding/encoding.
This requires pulling in an additional dependency (`typenum`, at least until min const generics land), so it's presently feature gated under the `big-uint` crate feature.
The immediate intended use case is replacing decoding/encoding logic for DER-encoded signatures in the `ecdsa` crate, and as such it's presently specialized to integers between 1-127 bytes, however this implementation could be further generalized to support larger integers.

der: BigUInt type

---

.github/workflows/pkcs8.yml
Cargo.lock
pkcs8/Cargo.toml
pkcs8/src/pem.rs

Provides a constant time implementation of unpadded Base64.
See #200.

pkcs8: use `b64ct` crate

---

der/src/asn1/big_uint.rs
der/src/lib.rs

This is needed for trait bounds.

der: export `BigUIntSize`

---

b64ct/src/errors.rs
b64ct/src/lib.rs
b64ct/tests/mod.rs

This PR adds two `unsafe` line for conversion into strings. We could remove them by using byte slices/vectors instead of strings. I am not sure how useful in practice is to have `&str`/`String` instead of `&[u8]`/`Vec<u8>`.
Panic-free property was verified in [godbolt](https://rust.godbolt.org/z/qe5Y5z).
Errors become a bit verbose, ideally it would be nice to have "anonymous enums" (i.e. `InvalidLengthError | InvalidEncodingError`), but we have to work with what we have.
One potential optimization is to modify `decode` API to:
```rust
// `buf` contains a B64-encoded string
pub fn decode<'a>(buf: &'a mut [u8]) -> Result<&'a [u8], InvalidEncodingError> { .. }
```
This way we will be able to reuse the buffer and remove the `Error` enum, but, again, I am not sure how such change would …

Rustified panic-free modification of b64ct

---

b64ct/benches/mod.rs
b64ct/src/lib.rs
b64ct/tests/mod.rs

As discussed in #205, unfortunately, compiler is not smart enough to remove panics even if we'll guard against the potential overflow. It's possible to make it panic-free by sprinkling a number of `get_uncheked`, but I would like avoid following this route if possible. Thus this panicking version should be a good enough starting point.

Add decode_in_place and benchmarks to b64ct

---

der/Cargo.toml
der/derive/Cargo.toml
der/derive/README.md

Some were mistakenly pointed at the `pkcs8` crate

der: fix doc links

---

der/src/asn1/big_uint.rs
der/src/asn1/integer.rs

Fixes a bug in leading `0` handling for unsigned integers (needed if the second octet is >=0x80)

der: fix unsigned INTEGER handling; more test vectors

---

der/src/asn1/integer.rs
der/src/lib.rs
pkcs8/src/private_key_info.rs

Support for encoding/decoding unsigned ASN.1 INTEGER values to/from these Rust primitive types.

der: u8 and u16 support

---

Cargo.lock
block-buffer/CHANGELOG.md
block-buffer/Cargo.toml
block-buffer/src/lib.rs
block-padding/CHANGELOG.md
block-padding/Cargo.toml
block-padding/src/lib.rs

This PR modifies `block-buffer` and `block-padding` APIs to reduce their surface and to make them mostly panic-free. Lack of panics in `block-buffer` was checked using godbolt. The relevant `unsafe` code line relies on the following invariant: `pos` is always strictly smaller than block size.
Because of this invariant I had to remove the `input_lazy` method, which was initially added for Skein. I think it will be better to later introduce a separate "lazy" buffer type. As a consequence it means that Skein will not be compatible with the core API introduced in RustCrypto/traits#380 (I think it could be eventually fixed with specialization). For most users it will be a barely noticeable implementation detail (i.e. Skein will simply implement the mid-level traits directly, without relying on …

block-buffer and block-padding improvements

---

Cargo.lock
dbl/Cargo.toml
dbl/src/lib.rs

The existing code is unsound since it has neither compile, or run time checks that value is properly aligned.

dbl: fix unsoundness

---

Cargo.lock
b64ct/CHANGELOG.md
b64ct/Cargo.toml
b64ct/src/lib.rs
pkcs8/Cargo.toml

- `decode_in_place` method ([#206])
- Panic-free operation ([#204], [#209])
- Overflow bug ([#212])
[#204]: https://github.com/RustCrypto/utils/pull/204
[#206]: https://github.com/RustCrypto/utils/pull/206
[#209]: https://github.com/RustCrypto/utils/pull/209
[#212]: https://github.com/RustCrypto/utils/pull/212

b64ct v0.2.0

---

der/src/decoder.rs

Adds a set of inherent methods to `Decoder` to assist in decoding ASN.1 `INTEGER` values:
- `int8`
- `int16`
- `uint8`
- `uint16`
- `big_uint`

der: add integer decoder helper methods

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs
pkcs8/Cargo.toml

- `BigUInt` type ([#196])
- `i16` support ([#199])
- `u8` and `u16` support ([#210])
- Integer decoder helper methods ([#219])
- Handle leading byte of `BIT STRING`s ([#193])
[#193]: https://github.com/RustCrypto/utils/pull/193
[#196]: https://github.com/RustCrypto/utils/pull/196
[#199]: https://github.com/RustCrypto/utils/pull/199
[#210]: https://github.com/RustCrypto/utils/pull/210
[#219]: https://github.com/RustCrypto/utils/pull/219

der v0.2.0

---

base64ct/src/errors.rs
base64ct/src/lib.rs
base64ct/tests/padded.rs
base64ct/tests/unpadded.rs
pkcs8/src/pem.rs

We need support for both:
- "PEM" (as used by PKCS#8) needs padded Base64
- "B64" (as used by the PHC string format) and JWK need unpadded Base64

base64ct: support both unpadded and padded encodings

---

.github/workflows/pkcs8.yml
base64ct/src/errors.rs
base64ct/src/lib.rs
base64ct/tests/lib.rs
pkcs8/src/pem.rs

Removes padding prior to decoding, allowing the unpadded decoding path to be the "one true way" to handle all decoding.
Validates padding bytes in constant-time, returning an error flag to be OR'd into the other potential encoding errors and branched upon only after fully decoding/validating all other data.

base64ct: unify padded and unpadded decoding

---

base64ct/README.md
base64ct/src/errors.rs
base64ct/src/lib.rs
base64ct/tests/lib.rs
pkcs8/src/pem.rs

Adds support for Base64url: a URL-safe variant of the standard Base64 encoding.
Uses `-` and `_` for encoding Base64 values 62/63, as opposed to the standard `+` and `/`.

base64ct: Base64url encoding support

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Bump `der` crate dependency to v0.2 ([#224])
- Use `base64ct` v0.1 for PEM encoding ([#232])
[#224]: https://github.com/RustCrypto/utils/pull/224
[#232]: https://github.com/RustCrypto/utils/pull/232

pkcs8 v0.4.0

---

Cargo.lock
base64ct/CHANGELOG.md
base64ct/Cargo.toml
base64ct/src/lib.rs

Improves the `encode` function by improving code reuse and removing an unreachable panic in the padded path. Also marks all inner functions with `#[inline(always)]` to remove call indirection. Most often crates will use only one module, so I think such inlining is warranted.

base64ct: minor code improvements

---

Cargo.lock
base64ct/CHANGELOG.md
base64ct/Cargo.toml
base64ct/src/lib.rs

- bcrypt encoding ([#237])
- `crypt(3)` encoding ([#239])
- Internal refactoring ([#235], [#236])
[#235]: https://github.com/RustCrypto/utils/pull/235
[#236]: https://github.com/RustCrypto/utils/pull/236
[#237]: https://github.com/RustCrypto/utils/pull/237
[#239]: https://github.com/RustCrypto/utils/pull/239

base64ct v0.1.2

---

base64ct/src/bcrypt.rs
base64ct/src/crypt.rs
base64ct/src/encoding.rs
base64ct/src/standard.rs
base64ct/src/url.rs
base64ct/src/variant.rs

Replaces imperative decode_6bits/encode_6bits method with declarative associated constants describing the encoding.
This method still avoids the use of lookup tables and all inputs are still processed identically without any branching.

base64ct: declarative decoding/encoding

---

Cargo.lock
base64ct/CHANGELOG.md
base64ct/Cargo.toml
base64ct/README.md
base64ct/src/lib.rs
base64ct/src/variant/bcrypt.rs
base64ct/src/variant/crypt.rs
pkcs8/Cargo.toml

- Refactor with `Encoding` trait ([#238])
- Internal refactoring ([#241], [#242])
[#238]: https://github.com/RustCrypto/utils/pull/238
[#241]: https://github.com/RustCrypto/utils/pull/241
[#242]: https://github.com/RustCrypto/utils/pull/242

base64ct v0.2.0

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Bump `basec4ct` dependency to v0.2 ([#238], [#243])
[#238]: https://github.com/RustCrypto/utils/pull/238
[#243]: https://github.com/RustCrypto/utils/pull/243

pkcs8 v0.4.1

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/derive/CHANGELOG.md
der/derive/Cargo.toml
der/src/lib.rs

- Support for `PrintableString` and `Utf8String` ([#245])
[#245]: https://github.com/RustCrypto/utils/pull/245

der v0.2.1

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- Support for `UTCTime` and `GeneralizedTime` ([#250])
[#250]: https://github.com/RustCrypto/utils/pull/250

der v0.2.2

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- Additional `rustdoc` documentation ([#252], [#256])
[#252]: https://github.com/RustCrypto/utils/pull/252
[#256]: https://github.com/RustCrypto/utils/pull/256

der v0.2.3

---

pkcs8/src/lib.rs
pkcs8/src/private_key_info/encrypted.rs

Updates the rustdoc with links to #263

pkcs8: add tracking issues for PKCS#8 encryption support

---

const-oid/src/lib.rs
spki/src/algorithm.rs
spki/src/lib.rs
spki/src/spki.rs

Adds an enum representing `ANY`, `NULL`, and `Objectidentifier` cases for the `parameters` field of `AlgorithmIdentifier`.
Ideally this enum would be unnecessary and we could just use the `der::Any` type for this field, however to make that possible in all relevant use cases we'd need a reference-based type for `ObjectIdentifier` backed by a byte slice containing the DER serialization of the OID. See #266.
Until we have such a type, this enum suffices to make it possible to decode and encode an owned OID value which stores the decoded arcs that comprise it, rather than the DER serialization.

spki: add (back) an `AlgorithmParameters` type

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Initial `EncryptedPrivateKeyInfo` support ([#262])
- Extract SPKI-related types into the `spki` crate ([#261], [#268])
[#261]: https://github.com/RustCrypto/utils/pull/261
[#262]: https://github.com/RustCrypto/utils/pull/262
[#268]: https://github.com/RustCrypto/utils/pull/268

pkcs8 v0.5.0

---

der/src/error.rs
pkcs5/src/pbes1.rs
pkcs5/src/pbes2.rs

This name does a much better job of capturing what it is attempting to report to the caller, and also nicely pairs with `UnknownTag`.

der: rename OidInvalid => UnknownOid

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs
pkcs5/Cargo.toml

- `ErrorKind::UnknownOid` variant ([#273], [#275])
[#273]: https://github.com/RustCrypto/utils/pull/273
[#275]: https://github.com/RustCrypto/utils/pull/275

der v0.2.5

---

.github/workflows/pkcs8.yml
pkcs8/Cargo.toml
pkcs8/src/lib.rs
pkcs8/src/private_key_info.rs
pkcs8/src/private_key_info/encrypted.rs
pkcs8/tests/encrypted_private_key.rs

Gates `EncryptedPrivateKeyInfo` support under a `pkcs5` feature.
This type is worthless without a PKCS#5 implementation to decrypt/encrypt the private key. This feature will allow gating the
`pkcs5` crate and the additional dependencies it needs (via `pkcs5` crate features).
To avoid introducing a new feature being a breaking change, the `pkcs5` feature is enabled by-default.

pkcs8: add `pkcs5` feature

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- `pkcs5` feature ([#278])
- Bump `spki` dependency to v0.2.0 ([#277])
[#277]: https://github.com/RustCrypto/utils/pull/277
[#278]: https://github.com/RustCrypto/utils/pull/278

pkcs8 v0.5.1

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- Make the unit type an encoding of `NULL` ([#281])
[#281]: https://github.com/RustCrypto/utils/pull/281

der v0.2.6

---

der/src/header.rs
der/src/lib.rs

Advanced usages of the crate (which try to map DER-encoded data in a way that isn't 100% isomorphic to Rust struct/enum combinations) can benefit from having this available in the public interface.

der: export `Header` publically

---

Cargo.lock
const-oid/Cargo.toml
const-oid/src/lib.rs
const-oid/tests/lib.rs
pkcs5/src/pbes2.rs

It was using bitwise OR instead of addition.
This commit also significantly expands the tests, including adding test cases for a root arc of 2, assertions for the root arcs everywhere (as they are represented differently internally), and additionally moves tests into the `tests/` directory so we don't need conditional `std` linkage for the tests.

const-oid: fix root arc calculation

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Bug in root arc calculation ([#284])
[#284]: https://github.com/RustCrypto/utils/pull/284

const-oid v0.4.2

---

Cargo.lock
pkcs5/src/lib.rs
pkcs5/tests/pbes2.rs
pkcs8/Cargo.toml
pkcs8/src/lib.rs
pkcs8/src/private_key_info/encrypted.rs
pkcs8/tests/encrypted_private_key.rs

Adds the `pkcs5` crate as an optional dependency (replacing the previous `pkcs5` feature with an optional crate).
Uses the `pkcs5` crate for parsing the `AlgorithmIdentifier` of `EncryptedPrivateKeyInfo`.

pkcs8: use `pkcs5` crate

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Use `pkcs5` crate ([#290])
[#290]: https://github.com/RustCrypto/utils/pull/290

pkcs8 v0.5.2

---

der/src/asn1.rs
der/src/asn1/any.rs
der/src/asn1/choice.rs
der/src/asn1/optional.rs
der/src/decoder.rs
der/src/lib.rs
spki/src/algorithm.rs

Closes #271
The `Choice` trait represents an ASN.1 `CHOICE` and allows types to specify which ASN.1 tags they support.
This is implemented in terms of a static `can_decode` method. Using a method for this means it's possible to impl `Choice` for `Any` (or e.g. enums that contain `Any` as a member).
A blanket impl of `Choice` is provided for all types which impl `Decodable + Encodable + Tagged`, i.e. types which can be viewed as a `Choice` between only one alternative.
This trait is also an ideal for a custom derive macro for enums (and indeed, it's necessary to support an `OPTIONAL CHOICE` which maps to `Option<MyEnum>`.

der: add `Choice` trait

---

der/derive/src/choice.rs
der/derive/src/types.rs

Adds a `choice::Alternative` struct which includes information about how alternatives of an ASN.1 `CHOICE` map to Rust enum variants.
Uses this information to detect when duplicate ASN.1 types are specified for different variants, and panics in this case since this is invalid.

der_derive: add choice::Alternative and duplicate tracking

---

.github/workflows/pkcs5.yml
Cargo.lock
pkcs5/Cargo.toml
pkcs5/src/lib.rs
pkcs5/src/pbes2.rs
pkcs8/Cargo.toml
pkcs8/src/document/encrypted_private_key.rs
pkcs8/src/document/private_key.rs
pkcs8/src/document/public_key.rs
pkcs8/src/private_key_info.rs
pkcs8/src/private_key_info/encrypted.rs
pkcs8/tests/encrypted_private_key.rs

Following up on #293 which added PKCS#8 decryption support, this adds the corresponding support for encrypting `PrivateKeyInfo` as `EncryptedPrivateKeyInfo`.
It provides a simple API which generates a random salt and IV using a provided `CryptoRng`, then uses PBES2 with PBKDF2-SHA256 and AES-256-CBC.
It also provides a parameterized `encrypt_with_params` which allows for supplying a `pbes2::Parameters` structure.

pkcs8: encryption support

---

pkcs8/src/document/private_key.rs
pkcs8/src/error.rs
pkcs8/src/private_key_info/encrypted.rs

The `Error` enum is `non_exhaustive` so this is non-breaking

pkcs8: add Error::Crypto variant

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Support for decrypting/encrypting `EncryptedPrivateKeyInfo` ([#293], [#302])
- PEM support for `EncryptedPrivateKeyInfo` ([#301])
- `Error::Crypto` variant (#305)
[#293]: https://github.com/RustCrypto/utils/pull/293
[#301]: https://github.com/RustCrypto/utils/pull/301
[#302]: https://github.com/RustCrypto/utils/pull/302

pkcs8 v0.5.3

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Encryption helper methods for `FromPrivateKey`/`ToPrivateKey` ([#308])
[#308]: https://github.com/RustCrypto/utils/pull/308

pkcs8 v0.5.4

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- Support for `IA5String` ([#310])
[#310]: https://github.com/RustCrypto/utils/pull/310

der v0.2.9

---

const-oid/src/error.rs
const-oid/src/lib.rs
const-oid/src/parser.rs
const-oid/tests/lib.rs

Adds a new `ObjectIdentifier::parse` function which is declared `const fn` and capable of parsing OIDs from dot-delimited strings in const contexts.
This is much more readable/ideal than the current approach used by `ObjectIdentifier::new`, which accepts a slice of `Arc` (i.e. `u32`) type instead.
Ideally we can phase out the current `::new` in favor of one which parses strings, however that'd be a breaking change, so for now the implementation is side-by-side with the current `::new`.

const-oid: const-friendly string parser

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Const-friendly OID string parser ([#312])
[#312]: https://github.com/RustCrypto/utils/pull/312

const-oid v0.4.3

---

der/Cargo.toml
der/src/asn1/oid.rs
pkcs5/src/pbes1.rs
pkcs5/src/pbes2.rs

Uses the new const-friendly OID string parser for all OID literals.

pkcs5: use const `ObjectIdentifier::parse`

---

const-oid/src/lib.rs
const-oid/src/macros.rs
const-oid/src/parser.rs

Avoids duplication of the `const_assert!` macro

const-oid: extract `macros` module

---

const-oid/src/arcs.rs
const-oid/src/encoder.rs
const-oid/src/lib.rs
const-oid/src/parser.rs
const-oid/tests/lib.rs
der/src/asn1/oid.rs
der/src/byte_slice.rs
der/src/encoder.rs

This commit changes the internal representation of `ObjectIdentifier` to be the BER/DER encoding, rather than the root OID byte plus an array of decoded arc values (i.e. u32).
The `Arcs` iterator is likewise changed to decode the BER/DER representation on-the-fly.
Since the BER/DER encoding uses base 128, it's much more compact, allowing the representation of more potential OIDs while simultaneously reducing the total size in memory (now 24 bytes).
Making this work also involved the addition of a `const fn` OID encoder which is also included in this commit. From a `const fn` context OIDs are now parsed from strings and then subsequently BER/DER encoded into a byte array.

const-oid: change internal repr to BER/DER w\ const encoder

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/README.md
const-oid/src/lib.rs
der/Cargo.toml

- `ObjectIdentifier::as_bytes` method ([#317])
- Internal representation changed to BER/DER ([#317])
- Deprecated `ObjectIdentifier::ber_len`, `::write_ber`, and `::to_ber` ([#317])
[#317]: https://github.com/RustCrypto/utils/pull/317

const-oid v0.4.4

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- Impl `From<ObjectIdentifier>` for `Any` ([#317], [#319])
- Bump minimum `const-oid` dependency to v0.4.4 ([#318])
[#317]: https://github.com/RustCrypto/utils/pull/317
[#318]: https://github.com/RustCrypto/utils/pull/318
[#319]: https://github.com/RustCrypto/utils/pull/319

der v0.2.10

---

const-oid/src/lib.rs

Allows keying map-like data structures using ObjectIdentifiers

const-oid: derive Hash and Ord

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- `Hash` and `Ord` impls on `ObjectIdentifier` ([#323])
[#323]: https://github.com/RustCrypto/utils/pull/323

const-oid v0.4.5

---

Cargo.lock
base64ct/CHANGELOG.md
base64ct/Cargo.toml
base64ct/src/lib.rs

- MSRV docs ([#328])
[#328]: https://github.com/RustCrypto/utils/pull/328

base64ct v0.2.1

---

.github/workflows/base64ct.yml
base64ct/README.md
base64ct/src/encoding.rs
base64ct/src/lib.rs

All of the TODOs except for one are because `const fn` support for various methods isn't available until 1.47, and the previous MSRV was 1.46 instead.
Therefore, this commit bumps MSRV from 1.46 to 1.47 (which will entail a minor version bump too)

base64ct: MSRV 1.47 and TODO fixes it enables

---

.github/workflows/const-oid.yml
.github/workflows/der.yml
Cargo.lock
const-oid/Cargo.toml
const-oid/README.md
const-oid/src/arcs.rs
const-oid/src/encoder.rs
const-oid/src/lib.rs
const-oid/src/parser.rs
const-oid/tests/lib.rs
der/Cargo.toml
der/README.md
der/src/asn1/oid.rs
der/src/lib.rs
pkcs5/Cargo.toml
pkcs5/src/lib.rs
pkcs5/src/pbes1.rs
pkcs5/src/pbes2.rs
pkcs8/Cargo.toml
pkcs8/src/lib.rs
spki/Cargo.toml
spki/src/lib.rs

Every crate in RustCrypto that actually consumes `const-oid` is now MSRV 1.47+ (edit: `der` is still MSRV 1.46+ so I'll bump that too) so it makes sense to bump this one too, particularly because it presently contains workarounds for the lack of `const fn` support for certain functions which were stabilized in 1.47+.
Per our MSRV policy this comes with a minor version bump (which has been bumped to v0.5.0-pre for now, edit: also need to bump `der`), and as this is a breaking release we can go ahead and remove all of the deprecated methods.
The following changes are also included:
- Renames `ObjectIdentifier::parse` => `ObjectIdentifier::new` (going forward we can use that exclusively in const contexts)
- Adapts the former `TryFrom<&[Arc]>` impl to an inherent `ObjectIdentifier::from_arcs` …

const-oid: MSRV 1.47+; remove workarounds and deprecations

---

der/src/asn1/any.rs
der/src/asn1/big_uint.rs
der/src/asn1/boolean.rs
der/src/asn1/generalized_time.rs
der/src/asn1/ia5_string.rs
der/src/asn1/integer.rs
der/src/asn1/null.rs
der/src/asn1/oid.rs
der/src/asn1/printable_string.rs
der/src/asn1/utc_time.rs
der/src/asn1/utf8_string.rs
der/src/decodable.rs
der/src/length.rs
der/src/lib.rs
der/tests/derive.rs
pkcs8/src/encrypted_private_key_info.rs
pkcs8/src/private_key_info.rs
spki/src/algorithm.rs
spki/src/spki.rs

Use a more specific name to avoid potential conflicts with e.g. inherent methods (which came up in practice with `ObjectIdentifier::from_der`)

der: name Decodable::from_bytes => Decodable::from_der

---

der/src/asn1.rs
der/src/asn1/choice.rs
der/src/asn1/sequence.rs
der/src/encoder.rs
der/src/lib.rs
der/src/message.rs
pkcs5/src/lib.rs
pkcs5/src/pbes1.rs

Closes #286
Adds a lower-level `SEQUENCE` API to `Encoder` which spawns a nested encoder and passes it to a closure, similar to the corresponding `Decoder` API.
Renames the previous "sequence"-related functionality which acts on a slice of `Encodable` trait objects which represent the fields to `message`.
Finally, removes `reserve` as part of the public API of `Encoder`, since the new `SEQUENCE` API handles the previous use cases that required it.

der: separate `sequence` and `message`

---

der/src/error.rs

...to distinguish it from `UnknownOid`

der: rename ErrorKind::Oid to ::MalformedOid

---

der/src/asn1/any.rs
der/src/encodable.rs
pkcs5/src/pbes2.rs
spki/src/algorithm.rs
spki/src/lib.rs

Now that an `&'a ObjectIdentifier` can be converted to `Any<'a>`, there is no longer a need for the workaround this enum provided and it can be removed.
This better aligns the definition of `AlgorithmIdentifier` with the ASN.1 schema.

spki: remove AlgorithmParameters enum

---

der/src/asn1.rs
der/src/asn1/sequence.rs
der/src/asn1/set_of.rs
der/src/lib.rs
der/src/tag.rs

Initial support for ASN.1 `SET OF`, adding the following:
- `SetOf` trait which can support multiple backing stores. The longer term goal is to support e.g. `BTreeSet`.
- `SetOfRef` which can decode `SET OF` from a byte slice (`no_std`-friendly)

der: add support for SET OF

---

der/src/asn1/sequence.rs

It doesn't validate that the SEQUENCE is well-formed, so it should only be used in contexts where that happens as a separate step

der: make sequence constructor private

---

der/src/asn1/any.rs
der/src/asn1/oid.rs
der/src/decoder.rs
der/src/encodable.rs
der/src/encoder.rs
der/src/length.rs

The current restriction of `Length` being at most 65535 is actually just an artifact of its inability to decode/encode lengths which are greater than that limit, rather than an explicit design decision.
It would still be good to maintain a maximum document length, but ideally it would be larger than 65535 (e.g. 128kB or 256kB).
This commit keeps the maximum length at its present value, but changes the internal representation of the `Length` type to use `u32` to futureproof it for a potential increase whenever the work is done to support decoding/encoding larger lengths.

der: make Length use u32 internally

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/README.md
const-oid/src/lib.rs
der/Cargo.toml

- `TryFrom<&[u8]>` impl on `ObjectIdentifier` ([#338])
- MSRV 1.47+ ([#338])
- Renamed the following methods ([#338]):
- `ObjectIdentifier::new` => `ObjectIdentifier::from_arcs`
- `ObjectIdentifier::parse` => `ObjectIdentifier::new`
- `ObjectIdentifier::from_ber` => `ObjectIdentifier::from_bytes`
- Deprecated methods ([#338])
- `alloc` feature - only used by aforementioned deprecated methods ([#338])
- `TryFrom<&[Arc]>` impl on `ObjectIdentifier` - use `::from_arcs` ([#338])
[#338]: https://github.com/RustCrypto/utils/pull/338

const-oid v0.5.0

---

der/src/asn1/any.rs
der/src/asn1/big_uint.rs
der/src/asn1/bit_string.rs
der/src/asn1/boolean.rs
der/src/asn1/generalized_time.rs
der/src/asn1/integer.rs
der/src/asn1/utc_time.rs
der/src/length.rs
der/src/tag.rs

The latter specifically simplifies calculations for a TLV-encoded value (i.e. with tag byte and length prefix) given an inner length.

der: add `Length::one` and `Length::for_tlv`

---

der/src/asn1/choice.rs
der/src/asn1/set_of.rs
der/src/lib.rs

When `alloc` is available, `BTreeSet` is an ideal data structure for DER-encoded ASN.1 `SET OF`, as DER carries the canonicalization requirement that the elements are ordered, and `BTreeSet` is bounded on an `Ord` impl and provides ordering as a first-class property.

der: impl SetOf for BTreeSet

---

Cargo.lock
der/Cargo.toml
der/derive/CHANGELOG.md
der/derive/Cargo.toml
der/derive/src/lib.rs

- `choice::Alternative` and duplicate tracking ([#300])
- Auto-derive `From` impls for variants when deriving `Choice` ([#345])
[#300]: https://github.com/RustCrypto/utils/pull/300
[#345]: https://github.com/RustCrypto/utils/pull/345

der_derive v0.3.0

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs
pkcs5/Cargo.toml
pkcs8/Cargo.toml
spki/Cargo.toml

- Impl `Decode`/`Encoded`/`Tagged` for `String` ([#344])
- `Length::one` and `Length::for_tlv` ([#351])
- `SET OF` support with `SetOf` trait and `SetOfRef` ([#346], [#352])
- Rename `Decodable::from_bytes` => `Decodable::from_der` ([#339])
- Separate `sequence` and `message` ([#341])
- Rename `ErrorKind::Oid` => `ErrorKind::MalformedOid` ([#342])
- Auto-derive `From` impls for variants when deriving `Choice` ([#345])
- Make `Length` use `u32` internally ([#349])
- Make `Sequence` constructor private ([#348])
- Bump `const_oid` to v0.5 ([#350])
- Bump `der_derive` to v0.3 ([#353])
- Deprecated methods ([#340])
- `BigUIntSize` ([#347])
[#339]: https://github.com/RustCrypto/utils/pull/339
[#340]: https://github.com/RustCrypto/utils/pull/340
[#341]: …

der v0.3.0

---

Cargo.lock
pkcs5/Cargo.toml
pkcs8/Cargo.toml
spki/CHANGELOG.md
spki/Cargo.toml
spki/src/algorithm.rs
spki/src/lib.rs

- Bump `der` to v0.3 ([#354])
- `AlgorithmParameters` enum ([#343])
[#343]: https://github.com/RustCrypto/utils/pull/343
[#354]: https://github.com/RustCrypto/utils/pull/354

spki v0.3.0

---

Cargo.lock
der/src/lib.rs
pkcs5/CHANGELOG.md
pkcs5/Cargo.toml
pkcs5/src/lib.rs
pkcs8/Cargo.toml

- Bump `der` to v0.3 ([#354])
- Bump `spki` to v0.3 ([#355])
[#354]: https://github.com/RustCrypto/utils/pull/354
[#355]: https://github.com/RustCrypto/utils/pull/355

pkcs5 v0.2.0

---

pkcs8/CHANGELOG.md
pkcs8/src/lib.rs

- Bump `der` dependency to v0.3 ([#354])
- Bump `spki` dependency to v0.3 ([#355])
- Bump `pkcs5` dependency to v0.2 ([#356])
[#354]: https://github.com/RustCrypto/utils/pull/354
[#355]: https://github.com/RustCrypto/utils/pull/355
[#356]: https://github.com/RustCrypto/utils/pull/356

pkcs8 v0.6.0

---

der/src/asn1/any.rs
der/src/asn1/big_uint.rs
der/src/asn1/bit_string.rs
der/src/asn1/generalized_time.rs
der/src/asn1/ia5_string.rs
der/src/asn1/null.rs
der/src/asn1/octet_string.rs
der/src/asn1/printable_string.rs
der/src/asn1/sequence.rs
der/src/asn1/utc_time.rs
der/src/asn1/utf8_string.rs
der/src/byte_slice.rs
der/src/str_slice.rs
der/src/tag.rs

This permits usage in a `SetOf` context which requires ordering.

der: add PartialOrd + Ord impls to all ASN.1 types

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- `PartialOrd` + `Ord` impls to all ASN.1 types ([#363])
[#363]: https://github.com/RustCrypto/utils/pull/363

der v0.3.1

---

der/src/asn1/generalized_time.rs
der/src/asn1/utc_time.rs
der/src/length.rs

Removes `pub(crate)` from the inner `u32` which the `Length` type wraps.
This ensures upholding the invariant that the inner length is less than `Length::max` only needs to happen in the `length` module, and builds on the work from #367 to ensure that `TryFrom<u32> for Length` is the one place where this check occurs.

der: make inner integer wrapped by Length fully private

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/README.md
der/src/lib.rs

- Non-critical bug allowing `Length` to exceed the max invariant ([#367])
[#367]: https://github.com/RustCrypto/utils/pull/367

der v0.3.2

---

der/src/asn1/bit_string.rs
der/src/asn1/boolean.rs
der/src/asn1/generalized_time.rs
der/src/asn1/integer.rs
der/src/asn1/oid.rs
der/src/asn1/set_of.rs
der/src/asn1/utc_time.rs
der/src/byte_slice.rs
der/src/decoder.rs
der/src/encoder.rs
der/src/length.rs
der/src/message.rs
der/src/str_slice.rs
der/src/tag.rs

Adds the following constants:
- `Length::ZERO`
- `Length::ONE`
- `Length::MAX`
- `GeneralizedTime::LENGTH`
- `UtcTime::LENGTH`
Deprecates the `const fn`s that previously provided the same values.

der: add length constants

---

const-oid/src/encoder.rs
const-oid/src/lib.rs
der/src/asn1/oid.rs

Deprecates the const `ObjectIdentifier::max_len()` function and replaces it with a proper constant value.

const-oid: add ObjectIdentifier::MAX_LENGTH constant

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs
der/Cargo.toml

- `ObjectIdentifier::MAX_LENGTH` constant ([#372])
- Deprecate `ObjectIdentifier::max_len()` function ([#372])
[#372]: https://github.com/RustCrypto/utils/pull/372

const-oid v0.5.1

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- `Length` constants ([#371])
- Deprecate `const fn` methods replaced by `Length` constants ([#371])
[#371]: https://github.com/RustCrypto/utils/pull/371

der v0.3.3

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs

- Expand README.md ([#376])
[#376]: https://github.com/RustCrypto/utils/pull/376

const-oid v0.5.2

---

const-oid/src/encoder.rs
const-oid/src/lib.rs
der/src/asn1/big_uint.rs
der/src/asn1/null.rs
der/src/byte_slice.rs
der/src/lib.rs

Uses Clippy to forbid use of `unwrap()` on both `Option` and `Result`.
Also fixes the few lingering uses of unwrap (in one case replacing it with panic-free code)

const-oid+der: forbid unwrap

---

.github/workflows/pkcs5.yml
.github/workflows/pkcs8.yml
.github/workflows/workspace.yml
Cargo.lock
pkcs5/Cargo.toml
pkcs5/README.md
pkcs5/src/lib.rs
pkcs5/src/pbes2/encryption.rs

Bumps the following crate dependencies:
- `aes` v0.7
- `block-modes` v0.8
- `hmac` v0.11
- `pkbdf2` v0.8

pkcs5: bump `aes`, `block-modes`, `hmac`, and `pbkdf2`

---

Cargo.lock
pkcs5/CHANGELOG.md
pkcs5/Cargo.toml
pkcs5/src/lib.rs

- Bump `aes` to v0.7 ([#388])
- Bump `block-modes` to v0.8  ([#388])
- Bump `hmac` to v0.11  ([#388])
- Bump `pbkdf2` to v0.8  ([#388])
[#388]: https://github.com/RustCrypto/utils/pull/388

pkcs5 v0.2.1

---

.github/workflows/cpufeatures.yml
Cargo.lock
cpufeatures/Cargo.toml
cpufeatures/src/aarch64.rs
cpufeatures/src/lib.rs
cpufeatures/src/x86.rs
cpufeatures/tests/aarch64.rs
cpufeatures/tests/x86.rs

Adds preliminary support for runtime feature detection on `aarch64` targets, presently restricted to the following set of target features which are present on both `aarch64-unknown-linux-gnu` and `aarch64-apple-darwin` targets:
- `aes`: AES support
- `sha2`: SHA1 and SHA256 support
- `sha3`: SHA512 and SHA3 support
Closes #378

cpufeatures: aarch64 support (Linux and macOS/M4)

---

cpufeatures/src/aarch64.rs

The `__detect_target_features` macro was expanding into code that directly referenced `libc::getauxval`.
This commit adds a small helper function for querying `AT_HWCAP` using `getauxval` similar to the `sysctlbyname` helper function used on MacOS, and then has the macro invoke it using `$crate::`.

cpufeatures: fix Linux/aarch64 support

---

cpufeatures/src/aarch64.rs
cpufeatures/src/x86.rs

As in #398, the `libc` symbol is still being emitted from a macro, in this case to reference the individual hwcaps.
This commit re-exports them all from the `cpufeatures::aarch64` module and has the macro reference them that way.

cpufeatures: fix access to hwcaps on Linux/aarch64

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/lib.rs

- `aarch64` support for Linux and macOS/M4 targets ([#393])
[#393]: https://github.com/RustCrypto/utils/pull/393

cpufeatures v0.1.1

---

cpufeatures/src/aarch64.rs

The `libc` crate doesn't presently define Linux's `HWCAP_*` in Musl-based environments:
https://github.com/rust-lang/libc/issues/2171
This PR (temporarily) copies the presently supported `HWCAP_*` constants directly into this crate.
Additionally, it adds support for the `neon` target feature.

cpufeatures: fix usage on Musl environments; add NEON support

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/lib.rs

- `neon` feature detection on `aarch64` targets ([#403])
- Support for `musl`-based targets ([#403])
[#403]: https://github.com/RustCrypto/utils/pull/403

cpufeatures v0.1.2

---

cpufeatures/src/aarch64.rs
cpufeatures/tests/aarch64.rs

The `neon` feature is enabled by default on all `aarch64` targets, so there is no need for runtime detection on these targets.
Runtime detection might be interesting on 32-bit ARM targets, however this crate's ARM support is presently `aarch64`-only.

cpufeatures: remove `neon` on `aarch64` targets

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/lib.rs

- `neon` on `aarch64` targets: already enabled by default ([#406])
[#406]: https://github.com/RustCrypto/utils/pull/406

cpufeatures v0.1.3

---

cpufeatures/src/aarch64.rs
cpufeatures/src/lib.rs

ARM CPU feature detection is unfortunately tied to OS APIs, as the registers containing information about CPU features are not accessible to unprivileged userspace programs.
However, the previous setup which gated support on Linux/macOS only means that OS-specific gating needs to be repeated in every downstream consumer of `cpufeatures`, and also that if support for new environments is added in `cpufeatures` that downstream consumers don't receive it automatically.
This commit adds a fallback for non-Linux/macOS aarch64 environments, similarly to how we handle SGX, which always returns `false` unless the corresponding `target_feature`(s) are explicitly enabled in `RUSTFLAGS`. This allows `cpufeatures` to provide the mechanism for `target_feature`-based gating on these other platforms, …

cpufeatures: support compiling on non-Linux/macOS aarch64 targets

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/lib.rs

- Support compiling on non-Linux/macOS aarch64 targets ([#408])
[#408]: https://github.com/RustCrypto/utils/pull/408

cpufeatures v0.1.4

---

der/README.md
der/src/length.rs
der/src/lib.rs

Adds support for 4-byte DER-encoded lengths.
While this could potentially support lengths up to 16 MiB (2 << 24) the library maintains a more conservative cap of 1 MiB as this should be sufficient for the security-oriented cases this library is intended to be used for.
This can be re-examined if there is a legitimate use case.
Closes #370.

der: support `Length` of up to 1 MiB

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- Support `Length` of up to 1 MiB ([#411])
[#411]: https://github.com/RustCrypto/utils/pull/411

der v0.3.4

---

.github/workflows/crypto-bigint.yml
.github/workflows/workspace.yml
Cargo.lock
Cargo.toml
crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/LICENSE-APACHE
crypto-bigint/LICENSE-MIT
crypto-bigint/README.md
crypto-bigint/src/lib.rs
crypto-bigint/src/ops.rs
crypto-bigint/src/traits.rs
crypto-bigint/src/uint.rs

This commit adds an experimental prototype const generics-based big integer library targeting cryptographic use cases.
It's an extraction of some of the code from the `elliptic-curve` crates, modified to use const generics.
The immediate intended use case is being able to use it for elliptic curve constants, such as a curve's `Order`:
https://docs.rs/elliptic-curve/0.9.11/elliptic_curve/trait.Order.html
As such, it's been written with liberal usage of `const fn`. This allows safe usage in const scenarios which isn't possible with `generic-array`.
All that said, in general I think we could benefit from a library like this for several applications, including things like `rsa` and `dsa`.

crypto-bigint

---

crypto-bigint/src/lib.rs
crypto-bigint/src/macros.rs
crypto-bigint/src/uint.rs
crypto-bigint/src/uint/decoder.rs

Support for decoding `UInt` from hexadecimal strings, including in const contexts.

crypto-bigint: const-capable hex decoding support for UInt

---

.github/workflows/crypto-bigint.yml
crypto-bigint/README.md

Additionally runs tests on:
- 32-bit Linux/x86
- 32-bit Linux/PPC (via cross), providing a big endian target
- 64-bit ARM (via cross)

crypto-bigint: expanded CI config

---

der/src/asn1/any.rs
der/src/tag.rs

Adds `::context_specific` and `::context_specific_optional` methods to the `Any` type to simplify decoding fields with context-specific tags.

der: add helper methods for context-specific fields to Any

---

der/src/asn1/any.rs
der/src/decoder.rs

Adds helper methods to `Decoder` for parsing fields with context-specific tags:
- `context_specific`
- `context_specific_optional`

der: add context-specific methods to `Decoder`

---

pkcs8/src/attributes.rs
pkcs8/src/lib.rs
pkcs8/src/one_asymmetric_key.rs
pkcs8/src/private_key_info.rs
pkcs8/src/version.rs

Exposes raw `Attributes` for the `OneAsymmetricKey` struct.
No attempt is made to parse them as a `SET OF Attribute`. Instead it exposes an inner `Any` value for the context-specific tag 0.
The main use case for this is likely to be an optional certificate field, possibly used in the context of PKCS#12, however we presently have no examples with attributes which makes it difficult to model them any more specifically than a wrapper for an `Any` value.
This should be enough that if someone actually needs access to the attributes that they're exposed and available.
cc @ShadowJonathan

pkcs8: expose Attributes

---

pkcs8/src/one_asymmetric_key.rs

Encodes attributes into the `OneAsymmetricKey` message if present, and includes them in the Debug output if present.

pkcs8: fix attribute encoding and Debug impl

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/asn1/any.rs
der/src/lib.rs
pkcs8/Cargo.toml

- Helper methods for context-specific fields ([#422], [#423], [#428], [#429])
- `ContextSpecific` field wrapper ([#428])
- Decoder position tracking for errors during `Any<'a>` decoding (#431)
- `From` conversion for `BitString` into `Any` ([#428])
[#422]: https://github.com/RustCrypto/utils/pull/422
[#423]: https://github.com/RustCrypto/utils/pull/423
[#428]: https://github.com/RustCrypto/utils/pull/428
[#429]: https://github.com/RustCrypto/utils/pull/429

der v0.3.5

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Support for RFC5958's `OneAsymmetricKey` ([#424], [#425])
- Bump `der` to v0.3.5 ([#430])
[#424]: https://github.com/RustCrypto/utils/pull/424
[#425]: https://github.com/RustCrypto/utils/pull/425
[#430]: https://github.com/RustCrypto/utils/pull/430

pkcs8 v0.6.1

---

cpufeatures/src/aarch64.rs

All Apple ARM64 hardware has the same baseline set of statically known capabilities which can be assumed on all iOS (and macOS) platforms.
This commit adds support for those statically known capabilities on iOS.
Unfortunately it does not appear to be possible to access the `sysctl(3)` namespace on iOS in order to determine the availability of other CPU features which aren't part of this baseline set the same way we can on macOS, so a static capability set is the best we can do.
See this issue for more information: #378

cpufeatures: add iOS support (static ARM64 capabilities only)

---

.github/workflows/pkcs5.yml
pkcs5/src/pbes2.rs
pkcs5/src/pbes2/encryption.rs
pkcs5/src/pbes2/kdf.rs
pkcs8/tests/encrypted_private_key.rs

Adds support for encrypting keys using PKCS#5 when using scrypt as the password-based KDF.
Additionally integration tests the `pkcs8` crate against a full OpenSSL-generated scrypt + AES-256-CBC test vector, including ensuring that it's possible to reproduce the original test vector by encrypting the plaintext key using the original IV/salt/scrypt params inputs.

pkcs5: support scrypt as a KDF for encryption

---

Cargo.lock
pkcs5/CHANGELOG.md
pkcs5/Cargo.toml
pkcs5/src/lib.rs
pkcs8/Cargo.toml

- `scrypt` support as specified in RFC 7914 ([#434], [#436], [#437])
[#434]: https://github.com/RustCrypto/utils/pull/434
[#436]: https://github.com/RustCrypto/utils/pull/436
[#437]: https://github.com/RustCrypto/utils/pull/437

pkcs5 v0.2.2

---

.github/workflows/crypto-bigint.yml
Cargo.lock
crypto-bigint/Cargo.toml
crypto-bigint/src/array.rs
crypto-bigint/src/lib.rs
crypto-bigint/src/uint.rs

There is one interop strategy that is possible between `generic-array` and const generics today, and it's similar to the one already used by `typenum` (and, as it were, `crypto-bigint` itself): avoid any sort of const-generic parameterization when dealing with traits, and provide an impl of a trait for each desired size, with a macro to write them.
This commit adds a (currently decode-only) `ArrayEncoding` trait with a `ByteSize` parameter which must be an `ArrayLength<u8>`.
It uses the macros for defining type aliases for `UInt` to add an impl of this new trait.
As it were, `typenum` doesn't support all of the sizes that were previously defined, however it seems like the sizes that `typenum` does support are actually the sensible ones for a cryptographic bignum library, so this commit …

crypto-bigint: optional `generic-array` interop

---

crypto-bigint/src/array.rs
crypto-bigint/src/lib.rs
crypto-bigint/src/uint.rs

Tests deserialization from `ByteArray` when the `generic-array` crate feature is enabled.

crypto-bigint: add deserialization tests for `generic-array`

---

crypto-bigint/README.md
crypto-bigint/src/array.rs
crypto-bigint/src/uint.rs

Support generic array serialization which outputs `GenericArray<u8, N>`.
Unfortunately the array size bound necessary to pull this off can only be accomplished with `GenericArray` today (it requires non-min const generics at the very least)

crypto-bigint: `to_*_byte_array`

---

crypto-bigint/src/lib.rs
crypto-bigint/src/wrapping.rs

Adds a type analogous to `core::num::Wrapping` which always performs wrapping arithmetic on the inner value.
Initial support is provided for `UInt`, but like the `core`/`std` type it's designed to be generic and provides some generic implementations as well, in case we ever add a signed integer type to this library.

crypto-bigint: add `Wrapping` wrapper type

---

crypto-bigint/Cargo.toml
crypto-bigint/src/checked.rs
crypto-bigint/src/lib.rs

Adds a wrapper type which always performs checked arithmetic, and internally stores the result as a `CtOption`.
This enables an ergonomic way to describe arithmetic expressions which check for overflow in constant time.

crypto-bigint: add `Checked` wrapper type

---

crypto-bigint/src/macros.rs
crypto-bigint/src/uint.rs

Adds a macro which can compute the number of limbs required to store an n-bit number at compile time.
This is intended as a stop gap until a forthcoming Rust feature like `const_evaluatable_checked` allows it to be replaced with something such as a `const fn`.
For now it's needed to compute various const generic parameters however, so a macro is the only option available.

crypto-bigint: add `nlimbs!` macro

---

crypto-bigint/src/uint.rs

Allows splitting by using a `From` conversion to a 2-tuple of a half-width value.

crypto-bigint: add From impl for splitting

---

crypto-bigint/src/uint.rs
crypto-bigint/src/uint/ct.rs

Also adds `Ord` and `PartialOrd` impls that use the subtle-based comparisons internally.

crypto-bigint: impl ConstantTimeGreater/ConstantTimeLess for UInt

---

crypto-bigint/src/uint.rs
crypto-bigint/src/uint/from.rs

These will make it much easier to incrementally retrofit `UInt` into the `elliptic-curve` crate and the respective curve implementations.
From an encapsulation perspective, it's a bit problematic because it's exposing the internal representation used by `UInt`, so it additionally adds TODOs to eventually remove these as they're a bit of a hack.

crypto-bigint: add `From` conversions between `UInt` and limb arrays

---

crypto-bigint/src/array.rs

Matches the previous bounds used by `elliptic_curve::FieldSize` so we can easily migrate the `elliptic-curve` crate to use this as the basis of all `ArrayLength` computations.

crypto-bigint: additional ArrayEncoding::ByteSize bounds

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/src/lib.rs
der/Cargo.toml

- Modernize and remove deprecations; MSRV 1.51+ ([#458])
[#458]: https://github.com/RustCrypto/utils/pull/458

const-oid v0.6.0

---

der/derive/src/choice.rs
der/src/asn1/context_specific.rs
der/src/lib.rs
der/src/tag.rs
pkcs8/src/one_asymmetric_key.rs

Adds a `TagNumber` type for representing the lower 5 bits of a Tag, where bits 8/7 identify the class and bit 6 identifies primitive vs constructed forms.
Changes `Tag` from being `repr(u8)` to a structured representation with `Application`, `ContextSpecific`, and `Private` variants, each of which includes a `TagNumber`. This enables support for all of these classes for tag numbers up to 30, which is the maximum value which can be represented with a single leading identifier octet.
This change enables the `ContextSpecific` struct to have public members, as the tag number invariant can now be maintained by the `TagNumber` type instead.

der: add `TagNumber` type, make `Tag` structured

---

cpufeatures/Cargo.toml
cpufeatures/src/aarch64.rs

Closes #395
The HWCAPs provided by Linux are finer-grained than LLVM target features. This crate is trying to detect the latter, so we need to group together these finer grained features detected via HWCAPs.
This commit attempts to group together finer grained HWCAPs into coarser grained target features, ensuring all of the relevant HWCAPs for a given target feature are available.
Additionally, this adds support for the `crypto` target feature, which implies `aes` (and with it PMULL), along with `sha2` and `neon` (although the latter is always present on `aarch64`)

cpufeatures: map `aarch64` HWCAPs to target features; add `crypto`

---

der/src/decoder.rs
pkcs8/src/one_asymmetric_key.rs
pkcs8/tests/one_asymmetric_key.rs

Changes the `der::Decoder::context_specific` helper method to accept a `TagNumber` as a parameter and attempt to locate a particular context-specific field within a message.
Skips over lower-numbered unknown fields. If the expected field is encountered, it returns the value (as a `der::Any`) directly.
Updates the `pkcs8` crate to use these new methods, which dramatically simplifies the decoding of `OneAsymmetricKey`.

der: refactor context-specific field decoding

---

der/src/asn1/any.rs
der/src/asn1/boolean.rs
der/src/asn1/integer.rs
der/src/asn1/integer/uint.rs
der/src/asn1/set_of.rs
der/src/error.rs
der/src/length.rs
der/src/lib.rs

This is another take on #325, but using const generics as a way to provide a common implementation for Rust's unsigned integer primitives.
This commit replaces the existing DER decoder/encoder implementations for integer primitives with a core const generic implementation, and uses macros to write implementations of `TryFrom<Any>`, `Encodable`, and the `Tagged` traits for each of the integer primitives.
This commit extends support to `u32`, `u64`, and `u128` using:
impl_uint_encoding!(u8, u16, u32, u64, u128);

der: const generic unsigned integer decoder with u32/u64/u128 support

---

.github/workflows/der.yml
Cargo.lock
der/Cargo.toml
der/src/asn1.rs
der/src/asn1/bigint.rs
der/src/decoder.rs
der/src/lib.rs

Renames the previous `big-uint` feature to simply `bigint`, so as to better match the name of the `crypto-bigint` crate.
Adds impls of `TryFrom<Any>`, `Encodable`, and `Tagged` for the `crypto_bigint::UInt` type. These aren't particularly well-implemented or efficient yet, but at least PoC the functionality.
The previous `BigUInt` type is still preserved, for now, but ideally it can eventually go away and be completely replaced by
`crypto_bigint::UInt` longer-term.

der: rename `big-uint` feature to `bigint`; `crypto-bigint` support

---

der/src/asn1.rs
der/src/asn1/bigint.rs
der/src/asn1/integer/uint.rs
der/src/decoder.rs
der/src/lib.rs

Previously the following names were used:
- `BigUInt`: serialized big integer
- `UInt`: big integer type from the `crypto-bigint` crate
This is a bit confusing because the "Big" prefix didn't really disambiguate what `BigUInt` was: a serialized big endian integer.
This commit changes its name to reflect that.

der: rename `BigUInt` => `UIntBytes`

---

Cargo.lock
der/Cargo.toml
der/src/asn1/bigint.rs
der/src/asn1/integer.rs
der/src/asn1/integer/int.rs
der/src/asn1/integer/uint.rs
der/src/decoder.rs

Removes the size bounds on `UIntBytes`, and makes it a simple wrapper over the decoder/encoder functions already implemented in the `der::asn1::integer::uint` module.
Since the sized (and const generic) `UInt` type can now handle the previous use cases where a size bound is necessary, it's no longer needed and can be removed.

der: simplify UIntBytes

---

der/src/asn1/integer/int.rs
der/src/asn1/integer/uint.rs

Flattens out and simplifies the logic

der: use slice patterns to decode unsigned integers

---

der/src/asn1.rs
der/src/asn1/integer.rs
der/src/asn1/integer/bigint.rs
der/src/asn1/integer/int.rs
der/src/asn1/integer/uint.rs

Now that typenum is only being used as a transitive dependency of `crypto-bigint` (which is conditionally gated on the `bigint` feature) it's possible for `UIntBytes` to always be available.
Also factors `bigint` under `asn1::integer::bigint`.

der: remove `bigint` feature gating on `UIntBytes`

---

der/src/tag.rs
der/src/tag/class.rs
der/src/tag/number.rs

Performs some internal refactoring of the `tag` module, splitting out `class` and `number` submodules.
Adds helper methods to `TagNumber` for creating specific classes of tags with a given number.

der: refactor `tag` module; add tag number helpers

---

const-oid/src/error.rs
der/derive/src/choice.rs
der/src/asn1/boolean.rs
der/src/asn1/generalized_time.rs
der/src/asn1/ia5_string.rs
der/src/asn1/integer.rs
der/src/asn1/integer/uint.rs
der/src/asn1/printable_string.rs
der/src/asn1/set_of.rs
der/src/asn1/utc_time.rs
der/src/datetime.rs
der/src/decoder.rs
der/src/encoder.rs
der/src/tag.rs
pkcs5/src/pbes1.rs
pkcs5/src/pbes2.rs
pkcs5/src/pbes2/kdf.rs
pkcs8/src/lib.rs
pkcs8/src/private_key_info.rs
pkcs8/src/traits.rs
pkcs8/src/version.rs

Adds a `Tag::value_error()` helper method which simplifies returning errors about invalid values for a given tag.

der: add ErrorKind::Value encoding helpers

---

crypto-bigint/src/uint.rs

The intended use case is initializing the existing `MODULUS` constants for the various `Scalar` impls in the elliptic curve crates.
Longer term we should be able to migrate to an entirely `UInt`-based implementation of scalar (ideally adding reusable `Field` types as well), but for now this is being added to simplify the initial retrofit.

crypto-bigint: add UInt::into_limbs

---

spki/src/algorithm.rs

Adds a one-shot helper method for asserting that the algorithm and parameters OIDs are an expected set of values.

spki: add `AlgorithmIdentifier::assert_oids`

---

der/src/asn1/any.rs
der/src/decodable.rs
der/src/decoder.rs

...instead of a `Result`.
The original goal was to avoid having to write `Err(...)` but the result is a bit awkward and clumsy instead.

der: have `Decoder::error()` return an `Error`

---

Cargo.lock
crypto-bigint/Cargo.toml
crypto-bigint/src/array.rs
crypto-bigint/src/lib.rs
crypto-bigint/src/traits.rs
crypto-bigint/src/uint.rs
crypto-bigint/src/uint/array.rs
crypto-bigint/src/uint/encoding.rs
crypto-bigint/src/uint/macros.rs
der/Cargo.toml
der/src/asn1/integer/bigint.rs
pkcs1/Cargo.toml

Extracts byte encoding functionality into an `Encoding` trait that acts on an associated `Encoding::Repr` type.
Breaking change, so it also bumps the version to v0.2.0-pre.

crypto-bigint: add/extract `Encoding` trait

---

Cargo.lock
crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs
crypto-bigint/src/uint/array.rs
crypto-bigint/src/uint/macros.rs
der/Cargo.toml

- `ConstantTimeGreater`/`ConstantTimeLess` impls for UInt ([#459])
- `From` conversions between `UInt` and limb arrays ([#460])
- `zeroize` feature ([#461])
- Additional `ArrayEncoding::ByteSize` bounds ([#462])
- `UInt::into_limbs` ([#484])
- `Encoding` trait ([#488])
- `NumBits`/`NumBytes` traits; use `Encoding` instead ([#488])
[#459]: https://github.com/RustCrypto/utils/pull/459
[#460]: https://github.com/RustCrypto/utils/pull/460
[#461]: https://github.com/RustCrypto/utils/pull/461
[#462]: https://github.com/RustCrypto/utils/pull/462
[#484]: https://github.com/RustCrypto/utils/pull/484
[#488]: https://github.com/RustCrypto/utils/pull/488

crypto-bigint v0.2.0

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/derive/CHANGELOG.md
der/derive/Cargo.toml
der/src/lib.rs
pkcs1/Cargo.toml
pkcs5/Cargo.toml
pkcs8/Cargo.toml
spki/Cargo.toml
x509/Cargo.toml

- `TagNumber` type ([#464])
- Const generic integer de/encoders with support for all of Rust's integer
primitives ([#469], [#470])
- `crypto-bigint` support ([#472])
- `Tag` number helpers ([#477])
- `Tag::octet` ([#479])
- `ErrorKind::Value` helpers ([#481])
- `SequenceIter` ([#483])
- Bump `const-oid` crate dependency to v0.6 ([#463])
- Make `Tag` structured ([#464])
- Namespace ASN.1 types in `asn1` module ([#465])
- Refactor context-specific field decoding ([#466])
- MSRV 1.51 ([#469], [#470])
- Rename `big-uint` crate feature to `bigint` ([#472])
- Rename `BigUInt` to `UIntBytes` ([#473])
- Have `Decoder::error()` return an `Error` ([#487])
- Deprecated methods replaced by associated constants ([#458])
[#458]: https://github.com/RustCrypto/utils/pull/458
[#463]: …

der v0.4.0

---

Cargo.lock
pkcs5/Cargo.toml
pkcs8/Cargo.toml
spki/CHANGELOG.md
spki/Cargo.toml
spki/src/lib.rs
x509/Cargo.toml

- `AlgorithmIdentifier::assert_oids` ([#485], [#486])
- Bump `der` to v0.4 ([#490])
[#485]: https://github.com/RustCrypto/utils/pull/485
[#486]: https://github.com/RustCrypto/utils/pull/486
[#490]: https://github.com/RustCrypto/utils/pull/490

spki v0.4.0

---

Cargo.lock
pkcs5/CHANGELOG.md
pkcs5/Cargo.toml
pkcs5/src/lib.rs
pkcs8/Cargo.toml

- Bump `der` crate dependency to v0.4 ([#490])
- Bump `spki` crate dependency to v0.4 ([#491])
[#490]: https://github.com/RustCrypto/utils/pull/490
[#491]: https://github.com/RustCrypto/utils/pull/491

pkcs5 v0.3.0

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- ASN.1 error improvements ([#478])
- Merge `OneAsymmetricKey` into `PrivateKeyInfo` ([#467])
- Use scrypt as the default PBES2 KDF ([#468])
- Return `Result`(s) when encoding ([#478]) 
- Bump `der` to v0.4 ([#490])
- Bump `spki` to v0.4 ([#491])
- Bump `pkcs5` to v0.3 ([#492])
[#467]: https://github.com/RustCrypto/utils/pull/467
[#468]: https://github.com/RustCrypto/utils/pull/468
[#478]: https://github.com/RustCrypto/utils/pull/478
[#490]: https://github.com/RustCrypto/utils/pull/490
[#491]: https://github.com/RustCrypto/utils/pull/491
[#492]: https://github.com/RustCrypto/utils/pull/492

pkcs8 v0.7.0

---

pkcs5/src/pbes2/kdf.rs
pkcs8/src/lib.rs

- Fixes scrypt RFC number in `pkcs5` (was 8914, should be 7914)
- Notes `pkcs8` uses scrypt as the default PBKDF

pkcs5+pkcs8: documentation improvements

---

cpufeatures/src/aarch64.rs

This commit encodes the assumption that every ARMv8 CPU ever produced by Apple which is capable of running iOS supports the Cryptography Extensions for AES, PMULL, and SHA2.

cpufeatures: whitelist ARMv8 `crypto` feature on iOS

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/README.md
cpufeatures/src/lib.rs

- iOS support ([#435], [#501])
- Map `aarch64` HWCAPs to target features; add `crypto` ([#456])
[#435]: https://github.com/RustCrypto/utils/pull/435
[#456]: https://github.com/RustCrypto/utils/pull/456
[#501]: https://github.com/RustCrypto/utils/pull/501

cpufeatures v0.1.5

---

Cargo.lock
crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs

- `Limb` newtype ([#499])
- Target-specific rustdocs ([#500])
[#499]: https://github.com/RustCrypto/utils/pull/499
[#500]: https://github.com/RustCrypto/utils/pull/500

crypto-bigint v0.2.1

---

crypto-bigint/src/lib.rs
crypto-bigint/src/limb.rs
crypto-bigint/src/limb/encoding.rs
crypto-bigint/src/macros.rs
crypto-bigint/src/uint/encoding.rs
crypto-bigint/src/uint/from.rs

Now that we have a `Limb` newtype, we can use the associated constants `Limb::BYTE_SIZE` and `Limb::BIT_SIZE` instead.

crypto-bigint: deprecate `LIMB_BYTES` constant

---

crypto-bigint/src/limb.rs

This is mostly needed for `const fn` use as we can't use traits

crypto-bigint: make `Limb`'s `Inner` value public

---

Cargo.lock
crypto-bigint/Cargo.toml
crypto-bigint/src/limb.rs
crypto-bigint/src/limb/rand.rs
crypto-bigint/src/uint.rs
crypto-bigint/src/uint/rand.rs

Adds initial support for random number generation, for both `UInt` and `Limb`.
Also adds a `UInt::random_mod` function which generates a random number within the range of a provided modulus using rejection sampling.

crypto-bigint: add `rand` feature

---

Cargo.lock
crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs

- `Limb::is_odd` and `UInt::is_odd` ([#505])
- `UInt::new` ([#506])
- `rand` feature ([#508])
- Deprecate `LIMB_BYTES` constant ([#504])
- Make `Limb`'s `Inner` value public ([#507])
[#504]: https://github.com/RustCrypto/utils/pull/504
[#505]: https://github.com/RustCrypto/utils/pull/505
[#506]: https://github.com/RustCrypto/utils/pull/506
[#507]: https://github.com/RustCrypto/utils/pull/507
[#508]: https://github.com/RustCrypto/utils/pull/508

crypto-bigint v0.2.2

---

hex-literal/src/comments.rs
hex-literal/src/lib.rs

Closes #511
Closes #365 ('#' prefixed comments)
I kept the comment removal as a separate module so that the tests can be scoped to just removing commented parts of a string. There only needed to be a few documentation tests to show the macro was working as intended.
I decided to do `/* */` style comments too because it was not much more work, but I can remove those states from the machine easily enough if you really do not want them.

Line and block comments.

---

pkcs8/src/error.rs

Adds an error variant which makes it easy to relay that raw octet-encoded key data is malformed/invalid.

pkcs8: add `Error::KeyMalformed` variant

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- `Error::KeyMalformed` variant ([#521])
[#521]: https://github.com/RustCrypto/utils/pull/521

pkcs8 v0.7.1

---

pkcs8/src/error.rs

Adds a variant for relaying that `AlgorithmIdentifier::parameters` are in some way malformed.
This is useful in cases where parameters are expected to be something other than an OID, for example `None` or ASN.1 NULL.

pkcs8: add `Error::ParamatersMalformed` variant

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- `Error::ParametersMalformed` variant ([#523])
[#523]: https://github.com/RustCrypto/utils/pull/523

pkcs8 v0.7.2

---

.github/workflows/pem-rfc7468.yml
pem-rfc7468/src/grammar.rs

CRLF handling can potentially touch secret data.
Unfortunately in the trailing CRLF case this is somewhat unavoidable, as looking at the previous byte before a LF is needed to disambiguate CRLF from LF.
However, for a leading EOL, if LF is examined first we can skip the CRLF check, and avoid branching on potentially secret data.
This should reduce the total number of secret bytes potentially branched on in the happy path to just 1-byte: handling the EOL that separates the encapsulated text from the post-encapsulation boundary.

pem-rfc7468: increase LF precedence in EOL stripping functions

---

Cargo.lock
pem-rfc7468/CHANGELOG.md
pem-rfc7468/Cargo.toml
pem-rfc7468/README.md
pem-rfc7468/src/lib.rs

- Increase LF precedence in EOL stripping functions ([#532])
- Bug in the size calculation for `decode_vec` ([#530])
[#530]: https://github.com/RustCrypto/utils/pull/530
[#532]: https://github.com/RustCrypto/utils/pull/532

pem-rfc7468 v0.1.1

---

pem-rfc7468/Cargo.toml
pkcs8/src/document/encrypted_private_key.rs
pkcs8/src/document/private_key.rs
pkcs8/src/document/public_key.rs
pkcs8/src/encrypted_private_key_info.rs
pkcs8/src/error.rs
pkcs8/src/private_key_info.rs

Ensures that the `expect` message for PEM encoding failures is consistent.
Separately, it might make sense to move to a fallible encoding API eventually to ensure code is panic-free, but for now this at least ensures consistency.

pkcs8: add `error::PEM_ENCODING_MSG` constant

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Use `pem-rfc7468` crate ([#530])
[#530]: https://github.com/RustCrypto/utils/pull/530

pkcs8 v0.7.3

---

.github/workflows/pkcs1.yml
pkcs1/src/lib.rs

Helpful for accessing these types without having to also import the `der` crate.

pkcs1: re-export `der` crate and `der::UIntBytes`

---

pkcs1/src/error.rs
pkcs8/src/error.rs

Replaces opaque variants for decoding/encoding errors with one which propagates the underlying `der::Error`.
Technically a breaking change, but the initial release was today, so it's possible to just nuke it and publish a replacement.

pkcs1: replace Error::{Decode, Encode} with Error::Asn1

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml
pkcs1/src/lib.rs

- Re-export `der` crate and `der::UIntBytes` ([#537])
- Replace `Error::{Decode, Encode}` with `Error::Asn1` ([#538])
[#537]: https://github.com/RustCrypto/utils/pull/537
[#538]: https://github.com/RustCrypto/utils/pull/538

pkcs1 v0.1.1

---

pkcs1/src/lib.rs
pkcs1/src/traits.rs

Adds traits similar to the ones in the `pkcs8` crate for decoding and encoding RSA private/public keys, including loading and saving them from disk when the `std` feature is enabled.

pkcs1: add From*/To* traits for RsaPrivateKey/RsaPublicKey

---

pkcs1/src/document/private_key.rs
pkcs1/src/document/public_key.rs
pkcs1/src/error.rs
pkcs1/src/private_key.rs
pkcs1/src/public_key.rs
pkcs1/src/traits.rs

This commit impls the decoding/encoding traits for `RsaPrivateKey`/`RsaPublicKey` on the serialized `RsaPrivateKeyDocument`/`RsaPublicKeyDocument` types.

pkcs1: use `FromRsa*`/`ToRsa*` traits with `*Document` types

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml
pkcs1/src/lib.rs

- `From*`/`To*` traits for `RsaPrivateKey`/`RsaPublicKey` ([#540])
- Use `FromRsa*`/`ToRsa*` traits with `*Document` types ([#541])
[#540]: https://github.com/RustCrypto/utils/pull/540
[#541]: https://github.com/RustCrypto/utils/pull/541

pkcs1 v0.2.0

---

.github/workflows/pkcs8.yml
Cargo.lock
pkcs8/Cargo.toml
pkcs8/src/error.rs
pkcs8/src/lib.rs
pkcs8/src/traits.rs

Adds an optional `pkcs1` feature to the `pkcs8` crate, which provides blanket impls of the `pkcs8` key decoding/encoding traits for any type which impls the corresponding traits from the `pkcs1` crate.

pkcs8: PKCS#1 support

---

pkcs1/src/error.rs

Add a variant for relaying cryptographic errors, e.g. a key component which was expected to be a prime is not a prime.

pkcs1: add `Error::Crypto` variant

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml
pkcs1/src/lib.rs

- `Error::Crypto` variant ([#544])
[#544]: https://github.com/RustCrypto/utils/pull/544

pkcs1 v0.2.1

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- PKCS#1 support ([#543])
[#543]: https://github.com/RustCrypto/utils/pull/543

pkcs8 v0.7.4

---

pkcs1/src/version.rs
pkcs8/src/version.rs

Uses the `u8` encoder to encode version numbers

pkcs1+pkcs8: simplify/fix version encoder

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml
pkcs1/src/lib.rs

- `Version` encoder ([#547])
[#547]: https://github.com/RustCrypto/utils/pull/547

pkcs1 v0.2.2

---

pem-rfc7468/src/encoder.rs
pem-rfc7468/src/lib.rs
pem-rfc7468/tests/encode.rs
pkcs1/src/document/private_key.rs
pkcs1/src/document/public_key.rs
pkcs1/src/private_key.rs
pkcs1/src/public_key.rs
pkcs8/src/document/encrypted_private_key.rs
pkcs8/src/document/private_key.rs
pkcs8/src/document/public_key.rs
pkcs8/src/encrypted_private_key_info.rs
pkcs8/src/private_key_info.rs

Makes line endings used for PEM encoding explicit, with the option of using `Default::default` to use the current operating system's line endings, or otherwise picking from CR, LF, or CRLF.

pem-rfc7468: support for customizing PEM line endings

---

Cargo.lock
pem-rfc7468/CHANGELOG.md
pem-rfc7468/Cargo.toml
pkcs1/Cargo.toml
pkcs8/Cargo.toml

- Support for customizing PEM line endings ([#551])
[#551]: https://github.com/RustCrypto/utils/pull/551

pem-rfc7468 v0.2.0

---

pkcs1/src/document/private_key.rs
pkcs1/src/document/public_key.rs
pkcs1/src/private_key.rs
pkcs1/src/public_key.rs
pkcs1/src/traits.rs

Adds `*pem_with_le` methods that support customizing the `LineEnding` used when encoding PEM.

pkcs1: support for customizing PEM `LineEnding`

---

pem-rfc7468/src/encoder.rs
pem-rfc7468/src/error.rs
pkcs1/src/document/private_key.rs
pkcs1/src/document/public_key.rs
pkcs1/src/lib.rs
pkcs1/src/private_key.rs
pkcs1/src/public_key.rs
pkcs1/src/traits.rs
pkcs8/src/document/encrypted_private_key.rs
pkcs8/src/document/private_key.rs
pkcs8/src/document/public_key.rs
pkcs8/src/encrypted_private_key_info.rs
pkcs8/src/lib.rs
pkcs8/src/private_key_info.rs
pkcs8/src/traits.rs

Adds `*pem_with_le` methods that support customizing the `LineEnding` used when encoding PEM.
See also #553.

pkcs8: support for customizing PEM `LineEnding`

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml
pkcs1/src/lib.rs

- Support for customizing PEM `LineEnding` ([#553])
- Bump `pem-rfc7468` dependency to v0.2 ([#552])
[#552]: https://github.com/RustCrypto/utils/pull/552
[#553]: https://github.com/RustCrypto/utils/pull/553

pkcs1 v0.2.3

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
pkcs8/src/lib.rs

- Support for customizing PEM `LineEnding` ([#554])
- Bump `pem-rfc7468` dependency to v0.2 ([#552])
[#552]: https://github.com/RustCrypto/utils/pull/552
[#554]: https://github.com/RustCrypto/utils/pull/554

pkcs8 v0.7.5

---

base64ct/Cargo.toml
const-oid/Cargo.toml
der/Cargo.toml
pem-rfc7468/Cargo.toml
pkcs1/Cargo.toml
pkcs5/Cargo.toml
pkcs8/Cargo.toml

Adds this category to all crates which implement format parsers

Add `parser-implementations` category to parser Cargo.toml(s)

---

.github/workflows/crypto-bigint.yml
.gitignore
crypto-bigint/proptests/Cargo.toml
crypto-bigint/proptests/tests/equivalence.rs
crypto-bigint/src/uint/mul.rs

Adds an initial set of property-based tests to check equivalence between `crypto_bigint::U256` and `num_bigint::BigUint`.
I mostly want these for #561, but I figured I could push up an initial integration separately.

crypto-bigint: add initial proptests for equivalence with num-bigint

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
der/src/lib.rs

- Encoding `UTCTime` for dates with `20xx` years ([#569])
[#569]: https://github.com/RustCrypto/utils/pull/569

der v0.4.1

---

base64ct/src/encoding.rs
base64ct/tests/standard.rs

When `Variant::PADDED` is `true`, ensure that the decoded data round-trips back to the padded input. If the padding is malformed, returns `Error::InvalidEncoding`.
Note that this commit only impls this check for the non-in-place `decode` method, not for `decode_in_place` yet. Instead, it documents that `decode_in_place` does not yet perform this check, and leaves it to be implemented in a followup. However, it does document that the `decode_in_place` method does not (yet) perform this check
Closes #575.

base64ct: make `Encoding::decode` reject invalid padding

---

Cargo.lock
base64ct/CHANGELOG.md
base64ct/Cargo.toml
base64ct/src/lib.rs

- Make `Encoding::decode` reject invalid padding ([#577])
[#577]: https://github.com/RustCrypto/utils/pull/577

base64ct v1.0.1

---

crypto-bigint/src/limb.rs
crypto-bigint/src/uint.rs

We probably should implement other `std` traits as well.
@tarcieri 
Are there other traits in your opinion in addition to `Eq` with which we should be careful?

crypto-bigint: implement Hash

---

crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs

After pushing this release to crates.io I will yank v0.2.1 and v0.2.2.

crypto-bigint v0.2.3

---

cpufeatures/src/aarch64.rs

`CStr` is doing exactly what the assert is meant to do, and gives the right char type by default.

Use from_bytes_with_nul for string check

---

Cargo.lock
crypto-bigint/src/lib.rs
crypto-bigint/src/limb.rs

This allows the `nlimbs!` macro to work, but also can provide the basis for expanded limb-related conversions, such as converting to an array of the inner integers.
cc @dignifiedquire

crypto-bigint: expose `limb` module

---

crypto-bigint/src/uint.rs
crypto-bigint/src/uint/shr.rs

Supports bitwise right shifts either as a `const fn` or using the `core::ops::Shr` trait.
This implementation is adapted from the one in the `k256` crate.

crypto-bigint: bitwise right shift support for `UInt`

---

crypto-bigint/src/uint/shr.rs

Renames this function to note that it's constant-time with respect to the `self` value, but variable-time with respect to the amount the `self` value is being shifted by.

crypto-bigint: rename `UInt::shr` to `UInt::shr_vartime`

---

Cargo.lock
crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs

- Expose `limb` module ([#584])
- `[limb::Inner; LIMBS]` conversions for `UInt` ([#585])
- Bitwise right shift support for `UInt` ([#586], [#590])
[#584]: https://github.com/RustCrypto/utils/pull/584
[#585]: https://github.com/RustCrypto/utils/pull/585
[#586]: https://github.com/RustCrypto/utils/pull/586
[#590]: https://github.com/RustCrypto/utils/pull/590

crypto-bigint v0.2.4

---

cpufeatures/src/aarch64.rs

This was removed in #594, however this is some remaining support code for it.

cpufeatures: remove vestigial code around `crypto` target feature

---

Cargo.lock
pkcs5/CHANGELOG.md
pkcs5/Cargo.toml
pkcs5/src/lib.rs

- Bump `scrypt` dependency to 0.8 ([#601])
- Bump `pbkdf2` dependency to v0.9 ([#605])
[#601]: https://github.com/RustCrypto/utils/pull/601
[#605]: https://github.com/RustCrypto/utils/pull/605

pkcs5 v0.3.1

---

crypto-bigint/src/uint.rs
crypto-bigint/src/uint/cmp.rs

It was only assigning the first limb, causing it to miscompute results.
While it had a test, it was a naive test that didn't ensure the limbs were unique.
The bug has been fixed and the test has been improved.

crypto-bigint: fix `ConditionallySelectable` impl on `UInt`

---

crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs
crypto-bigint/src/traits.rs
crypto-bigint/src/uint.rs
crypto-bigint/src/uint/rand.rs

Adds a trait encompassing the interesting bounds of `UInt`.
Since traits like `elliptic_curve::Curve` can't yet be generic over `const LIMBS`, this trait provides a convenient way of wrapping up `UInt` behavior such that it's still usable without spelling out all of these bounds explicitly.

crypto-bigint: `Integer` trait

---

Cargo.lock
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs
crypto-bigint/src/traits.rs
crypto-bigint/src/uint.rs
crypto-bigint/src/uint/encoding.rs
crypto-bigint/src/uint/encoding/decoder.rs
crypto-bigint/src/uint/encoding/rlp.rs

Adds an off-by-default optional `rlp` crate feature which adds RLP encoding/decoding support for `UInt`.

crypto-bigint: Recursive Length Prefix (RLP) encoding support

---

Cargo.lock
crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs
crypto-bigint/src/uint.rs

- `Integer` trait ([#612])
- `ShrAssign` impl for `UInt` ([#615])
- Recursive Length Prefix (RLP) encoding support for `UInt` ([#616])
[#612]: https://github.com/RustCrypto/utils/pull/612
[#615]: https://github.com/RustCrypto/utils/pull/615
[#616]: https://github.com/RustCrypto/utils/pull/616

crypto-bigint v0.2.6

---

crypto-bigint/proptests/tests/equivalence.rs
crypto-bigint/src/uint/add_mod.rs

For an as yet undetermined reason I can't implement scalar arithmetic for the `k256`/`p256` crates using the current `add_mod` implementation (or rather, the test vectors fail).
It appears to have something to do with overflow handling, and how the current implementation unconditionally subtracts the modulus regardless of whether or not the `adc` operation overflowed.
However, while the implementation in this commit allows the `k256`/`p256` tests to pass, it fails all of the current proptests.
cc @dignifiedquire @fjarri @str4d @tuxxy

crypto-bigint: fix `add_mod` overflow handling

---

Cargo.lock
crypto-bigint/CHANGELOG.md
crypto-bigint/Cargo.toml
crypto-bigint/src/lib.rs

- `UInt::shl_vartime` ([#622]) 
- `add_mod` overflow handling ([#619])
[#619]: https://github.com/RustCrypto/utils/pull/619
[#622]: https://github.com/RustCrypto/utils/pull/622

crypto-bigint v0.2.7

---

Cargo.lock
x509/Cargo.toml
x509/src/lib.rs

This is effectively a bug in `cargo audit` where it sees a yanked `x509` crate published to crates.io and confuses it with the workspace member.
To work around the issue, this commit bumps the version of the `x509` crate in the workspace to v0.0.1, which hasn't been yanked.

x509: `cargo audit` workaround

---

pkcs1/src/lib.rs
pkcs8/src/lib.rs

Describes what PKCS#8 actually is and gives examples of the "BEGIN" pre-encapsulation boundaries

pkcs8: add "About PKCS#8" intro section to rustdoc

---

pkcs5/src/pbes2.rs

The toplevel crate feature already takes care of it

pkcs5: remove unnecessary `doc_cfg` directive

---

base64ct/README.md
const-oid/README.md
crypto-bigint/README.md
der/README.md
pem-rfc7468/README.md
pkcs1/README.md
pkcs5/README.md
pkcs8/README.md
spki/README.md
x509/README.md

...and `crypto-bigint`
These crates have been moved to new repos:
- https://github.com/rustcrypto/crypto-bigint
- https://github.com/rustcrypto/formats

Delete "Moved" README.mds for formats crates

---

.github/workflows/zeroize.yml
Cargo.lock
Cargo.toml
zeroize/CHANGELOG.md
zeroize/Cargo.toml
zeroize/LICENSE-APACHE
zeroize/LICENSE-MIT
zeroize/README.md
zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml
zeroize/derive/LICENSE-APACHE
zeroize/derive/LICENSE-MIT
zeroize/derive/README.md
zeroize/derive/src/lib.rs
zeroize/src/lib.rs
zeroize/src/x86.rs
zeroize/tests/zeroize_derive.rs

Moves the source code for the `zeroize` and `zeroize_derive` crates into this repository. History is not preserved.
Sources are imported with some minor modifications to URLs and documentation as of this commit:
https://github.com/iqlusioninc/crates/commit/880f4569f652cf2804d8130e718b59497ff75c85
Author: Tony Arcieri (iqlusion) <tony@iqlusion.io>
Date:   Thu Nov 4 18:10:33 2021 -0700
Remove `harp` crate (#905)

Import `zeroize` and `zeroize_derive`

---

zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml

- `#[zeroize(skip)]` attribute ([#654])
[#654]: https://github.com/RustCrypto/utils/pull/654

zeroize_derive v1.2.2

---

zeroize/derive/src/lib.rs
zeroize/src/lib.rs

This actually documents the `#[zeroize(skip)]` functionality in the zeroize crate, until now it was only documented in the `zeroize_derive` crate.

Document `#[zeroize(skip)]` in the zeroize crate

---

hex-literal/CHANGELOG.md
hex-literal/src/lib.rs
hex-literal/tests/basic.rs
hex-literal/tests/comments.rs

Thanks for making the `hex-literal` crate! I was using it with an escaped hex string I'd copied from a C program, but ran into a panic because I'd accidentally left a semicolon after the strings I was calling `hex!()` on. It took me an embarrassing amount of time to discover the mistake, but I thought the panic messages might be able to provide a bit more info about what caused the failure.
This PR does only a few small things:
-  I added a bit more info to the panic messages when you encounter a non-literal, invalid character, or odd number of hex characters, to give you context about what's causing the issue. 
- I also added some internal documentation on some of the `TokenTreeIter` functions. 
- Lastly, I added some tests for the core `hex!()` macro functionality in the `tests/` …

Improve `panic!` messages in `hex-literal`

---

zeroize/derive/src/lib.rs
zeroize/src/lib.rs
zeroize/tests/zeroize_derive.rs

À la [`#[serde(bound = "T: MyTrait")]`](https://serde.rs/container-attrs.html#bound).

Implement `#[zeroize(bound = "T: MyTrait")]`

---

hex-literal/CHANGELOG.md
hex-literal/src/comments.rs

Hello again,
I noticed that, because the way comment exclusion works, having a single forward slash `/` as the last byte given to `hex!()` causes no error to be given where there should be one. For instance, the following program compiles without error:
```rust
let _: [u8; 0] = hex!("/");
```
Note that this doesn't happen if there are bytes after the `/` (in which a case it errors).
My fix adds a check in the implementation of `Iterator` for `ExcludingComments` for if there are no more bytes and we're in the `PotentialComment` state. In this case it simply yields the previous byte (which was the foward slash) so that `next_hex_val()` will try to parse it as hex and panic with "invalid character". This has the nice property that it's consistent with the error you get currently if a single …

`hex-literal`: ensure '/' as last byte causes error in `hex!()`

---

dbl/src/lib.rs

`MACs/cmac` benchmarks were used to evaluate the refactoring, as `dbl` does not contain its own. The refactoring of `dbl` seems to have no effect on the `MACs/cmac` performance.
Benchmarks results with `dbl` refactored:
```
$ git checkout 90c46e717ab2321022104ead2f9060b1327f5710; rustup run nightly cargo bench
Previous HEAD position was 9d876cb Bump digest from 0.10.0 to 0.10.1 (#100)
HEAD is now at 90c46e7 Test dbl safe code
Finished bench [optimized] target(s) in 0.02s
Running unittests (/home/alwagner/working_directory/tests/MACs/target/release/deps/cmac-5a75094f2021ff95)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running unittests (/home/alwagner/working_directory/tests/MACs/target/release/deps/aes128_cmac-7ce19bbcc576e …
```

dbl: Refactor to avoid unsafe

---

zeroize/derive/src/lib.rs
zeroize/src/lib.rs
zeroize/tests/zeroize_derive.rs

Implement `ZeroizeOnDrop`

---

zeroize/src/lib.rs

This implements `ZeroizeOnDrop` for the following containers if all elements in that container also implement `ZeroizeOnDrop`:
- `[Z; N]`
- `Option<Z>`
- `Vec<Z>`
- `Box<[Z]>`
- `(A, )` up to ten elements
Additionally implemented for the following zero-sized types:
- `PhantomData<Z>`
- `PhantomPinned`
- `()`
This required to remove the `Drop` constraint from `ZeroizeOnDrop`.

Implement `ZeroizeOnDrop` for containers

---

zeroize/derive/src/lib.rs
zeroize/src/lib.rs

This changes nothing from the users perspective, but will enable to implement `ZeroizeOnDrop` for fields that implement it replacing the need to `skip` them instead.
This will also validate that these fields types implement `ZeroizeOnDrop`.
See #652 for further discussion.
Builds on top of #699.
Fixes #652.

`ZeroizeOnDrop` auto-deref

---

Cargo.lock
zeroize/Cargo.toml
zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml

- `#[zeroize(bound = "T: MyTrait")]` ([#663])
- Custom derive for `ZeroizeOnDrop` ([#699], [#700])
[#663]: https://github.com/RustCrypto/utils/pull/663
[#699]: https://github.com/RustCrypto/utils/pull/699
[#700]: https://github.com/RustCrypto/utils/pull/700

zeroize_derive v1.3.0

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml
zeroize/src/lib.rs

- `Zeroize` impls for `PhantomData`, `PhantomPinned`, and tuples with 0-10 elements ([#660])
- `#[zeroize(bound = "T: MyTrait")]` ([#663])
- `ZeroizeOnDrop` trait and custom derive ([#699], [#700], [#703])
[#660]: https://github.com/RustCrypto/utils/pull/660
[#663]: https://github.com/RustCrypto/utils/pull/663
[#699]: https://github.com/RustCrypto/utils/pull/699
[#700]: https://github.com/RustCrypto/utils/pull/700
[#703]: https://github.com/RustCrypto/utils/pull/703

zeroize v1.5.0

---

Cargo.lock
zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml

- `ZeroizeOnDrop` implementation for `#[zeroize(drop)]` ([#715])
[#715]: https://github.com/RustCrypto/utils/pull/715

zeroize_derive v1.3.1

---

zeroize/src/lib.rs
zeroize/tests/zeroize_derive.rs

I found that this doesn't work. I hope this is not considered a breaking change?

Fix double `mut` on `AssertZeroizeOnDrop`

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml
zeroize/src/lib.rs

- Double `mut` on `AssertZeroizeOnDrop` ([#719])
[#719]: https://github.com/RustCrypto/utils/pull/719

zeroize v1.5.1

---

zeroize/src/lib.rs
zeroize/tests/zeroize_derive.rs

I added another level of indirection to fix #724 and a couple of tests to make sure.
I believe the edge-cases arisen so far are because autoref-specialization is usually not applied on methods needing `&mut self`, so I was lacking a bit of experience here.
I hope we covered all edge-cases now.

Fix ambiguous method for `AssertZeroizeOnDrop`

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml
zeroize/src/lib.rs

- Ambiguous method for `AssertZeroizeOnDrop` ([#725])
[#725]: https://github.com/RustCrypto/utils/pull/725

zeroize v1.5.2

---

block-buffer/src/lib.rs

The [documentation for `slice::as_mut_ptr`](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.as_ptr) says:
> The caller must also ensure that the memory the pointer (non-transitively) points to is never written to (except inside an UnsafeCell) using this pointer or any pointer derived from it. If you need to mutate the contents of the slice, use as_mut_ptr.
This PR _technically_ fixes UB per the documentation. The existing code also produces an error under Miri with `-Zmiri-tag-raw-pointers`:
```
test test_eager_set_data ... error: Undefined Behavior: trying to reborrow for Unique at alloc81264, but parent tag <215117> does not have an appropriate item in the borrow stack
--> /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src …
```

Use as_mut_ptr to get a pointer for mutation

---

Cargo.lock
block-buffer/CHANGELOG.md
block-buffer/Cargo.toml
block-buffer/src/lib.rs
block-buffer/src/sealed.rs

With the previous code the compiler was unable to infer that `tail_len` is always smaller or equal to block size.

block-buffer: eliminate unreachable panic in LazyBuffer::digest_blocks

---

.github/workflows/inout.yml
Cargo.lock
Cargo.toml
README.md
block-padding/CHANGELOG.md
block-padding/src/lib.rs
inout/CHANGELOG.md
inout/Cargo.toml
inout/LICENSE-APACHE
inout/LICENSE-MIT
inout/src/errors.rs
inout/src/inout.rs
inout/src/inout_buf.rs
inout/src/lib.rs
inout/src/reserved.rs

Split-off from #566
This crate aims to generalize over in-place and buffer-to-buffer modes of operation and it's designed to be used in our cipher crates, i.e. block/stream ciphers, block modes, AE(AD)s.

Add inout crate and prepare block-padding v0.3

---

zeroize/src/lib.rs
zeroize/tests/zeroize_derive.rs

Took some help to figure this one out. Specifically this allows deriving `ZeroizeOnDrop` for items containing `GenericArray`.

Fixed deriving `ZeroizeOnDrop` on `DerefMut`

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml
zeroize/src/lib.rs

- Deriving `ZeroizeOnDrop` on `DerefMut` ([#739])
[#739]: https://github.com/RustCrypto/utils/pull/739

zeroize v1.5.3

---

.github/workflows/cmov.yml
.github/workflows/workspace.yml
Cargo.lock
Cargo.toml
cmov/Cargo.toml
cmov/LICENSE-APACHE
cmov/LICENSE-MIT
cmov/README.md
cmov/src/lib.rs
dbl/src/lib.rs
wycheproof2blb/src/aes_siv.rs
wycheproof2blb/src/ecdsa.rs
wycheproof2blb/src/ed25519.rs
wycheproof2blb/src/hkdf.rs
wycheproof2blb/src/main.rs

Implements safe wrappers for the `cmovz` and `cmovnz` instructions which work on `x86` and `x86_64`, implemented using inline assembly.
Using inline assembly allows us to provide a sort of black box which LLVM will not interfere with, which is otherwise problematic when using anything besides ASM.
It's otherwise not possible to correctly emit CMOV instructions on x86 platforms with LLVM because the `x86-cmov-conversion` pass which will potentially rewrite them as branches.
For more details, see:
https://dsprenkels.com/cmov-conversion.html

Initial `cmov` crate

---

cmov/Cargo.toml
cmov/README.md
cmov/src/lib.rs

This passes tests and I _believe_ it works, but I also have the assembly programming experience of your average kindergartner, so a second opinion would be worth getting.
Running `cargo rustc --release -- --emit asm` on the portable `cmovz` yields this:
```
neg     w8, w0
orr     w8, w8, w0
ubfx    x8, x8, #7, #1
ldr     x9, [x2]
neg     x10, x8
and     x9, x9, x10
sub     x8, x8, #1
and     x8, x8, x1
orr     x8, x9, x8
str     x8, [x2]
ret
```
And a naive, branching version of `cmovz` yields this:
```
cbz     x0, LBB1_2
ret
LBB1_2:
str     x1, [x2]
ret
```
Which makes me think `cmp`/`csel` is the right choice.

Add cmovz/cmovnz support for aarch64.

---

Cargo.lock
cmov/CHANGELOG.md
cmov/Cargo.toml
cmov/README.md

- `cmovz`/`cmovnz`-alike support for AArch64 targets ([#744])
[#744]: https://github.com/RustCrypto/utils/pull/744

cmov v0.1.1

---

cmov/src/lib.rs

Those options tell the compiler that ASM statements do not read or write memory, can be removed if the dst ends up unused during compilation, and that they don't push data to the stack.
This can help compiler generate more optimal code. See https://doc.rust-lang.org/nightly/reference/inline-assembly.html#options for documentation of those options.

cmov: Set asm options

---

block-padding/CHANGELOG.md
block-padding/Cargo.toml
block-padding/src/lib.rs

This PR adds assert which prevents potential unsoundness in cases when the `Padding` trait is implemented incorrectly. For correct implementations compiler should be able to remove the panic branch.

block-padding: add sanity assert

---

.github/workflows/zeroize.yml
zeroize/Cargo.toml
zeroize/src/aarch64.rs
zeroize/src/lib.rs

Similar to the implementation for `x86`/`x86_64`, this commit adds nightly-only support for zeroizing ARM64 SIMD registers.
Support is gated behind an `aarch64` feature so as to avoid breaking compilation on stable Rust. The feature is a no-op on non-`aarch64` targets.

zeroize: add support for ARM64 SIMD registers (nightly-only)

---

cpufeatures/Cargo.toml
cpufeatures/src/aarch64.rs

Checking against [google/cpu_features](/google/cpu_features) it looks like Android follows Linux exactly in how it defines `getauxval`, so it really is just turning it on in aarch64.rs.
I have not actually tried *running* this on a 64-bit Android device yet; I'll get to that a bit later today. (Have to get that development environment set up again.) It does pass `cargo build --target aarch64-linux-android`, though (unsurprisingly).
Fixes #751.

cpufeatures: Add support for AArch64 Android (essentially a Linux variant)

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/README.md
cpufeatures/src/lib.rs

- Support for Android on `aarch64` ([#752])
- Vestigial code from removed ARMv8 `crypto` target feature ([#600])
[#600]: https://github.com/RustCrypto/utils/pull/600
[#752]: https://github.com/RustCrypto/utils/pull/752

cpufeatures v0.2.2

---

.github/workflows/zeroize.yml

It was pinned due to issues around `aarch64_target_feature` stabilization, but those have been resolved upstream.

CI: unpin `zeroize` nightly for `aarch64` testing

---

inout/src/inout_buf.rs

Running [salsa20](https://github.com/RustCrypto/stream-ciphers/blob/master/salsa20)'s tests under MIRI with the flags `$ENV:MIRIFLAGS="-Zmiri-symbolic-alignment-check -Zmiri-check-number-validity -Zmiri-tag-raw-pointers -Zmiri-disable-isolation -Zmiri-ignore-leaks -Zmiri-backtrace=full"` results in the following: 
<details>
<summary>miri output</summary>
```
running 1 test
error: Undefined Behavior: type validation failed at .value: encountered uninitialized bytes, but expected initialized plain (non-pointer) bytes
--> D:\dev\stream-ciphers\salsa20\utils\inout\src\inout_buf.rs:20:59
|
20  |     fn from(buf: &'a mut [T]) -> Self {let x: u8 = unsafe{core::mem::uninitialized()};
|                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed at …
```

Fix MIRI error in inout_buf.rs

---

zeroize/src/lib.rs

Sometimes libraries want to be generic across types like `Vec<u8>` and
`Box<[u8]>`. Therefore, they use bounds like `T: AsRef<[u8]>`. The
`Zeroizing<Vec<u8>>` type should be transparently equivalent to
`Vec<u8>` in this regard. This allows `Zeroizing` to be used with all
such bounds.
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

feat: make `Zeroizing` transparent for cheap conversions

---

.github/workflows/zeroize.yml
zeroize/Cargo.toml
zeroize/src/lib.rs

> Commit Msg:
> This implements Zeroize for std::ffi::CString. As CString is not in
allocate but in std, a new optional std feature is added to depend
on the std library.
I'm not quite sure if my implementation is correct and secure. In the issue linked in #650, it was mentioned that it likely is not possible to implement `Zeroize` for `CString`, due to the requirement that there must be no null bytes in the buffer. One of the comments stated that this problem could maybe be solved in "hacky" way:
>We could do something slightly wacky and overwrite internal bytes with `0xFF` or something, so as to obliterate the data while preserving the "no internal NUL bytes" guarantee.
_Originally posted by @cyberia-ng in https://github.com/iqlusioninc/crates/issues/509#issuecomment-766408309_
However, …

zeroize: Implement Zeroize for CString (#650)

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml

- Impl `Zeroize` for `std::ffi::CString` ([#759])
- `AsRef<T>` and `AsMut<T>` impls for `Zeroizing` ([#761])
[#759]: https://github.com/RustCrypto/utils/pull/759
[#761]: https://github.com/RustCrypto/utils/pull/761

zeroize v1.5.5

---

wycheproof2blb/src/ecdsa.rs
wycheproof2blb/src/main.rs

Adds support for extracting secp384r1 test vectors from Wycheproof, in order to test the `p384` crate.

wycheproof2blb: secp384r1 support

---

.github/workflows/fiat-constify.yml
Cargo.lock
Cargo.toml
fiat-constify/CHANGELOG.md
fiat-constify/Cargo.toml
fiat-constify/LICENSE-APACHE
fiat-constify/LICENSE-MIT
fiat-constify/README.md
fiat-constify/src/main.rs

This crate is a tool for transforming `fiat-crypto`-generated field arithmetic into `const fn` form.
It performs mechanical translation to the parsed AST of the code, making some assumptions about how it's structured and rewriting the usages of mutable references into a functional form.
Manual tests confirm the output from the p386 base field compiles.

fiat-constify: initial crate

---

fiat-constify/src/main.rs

Adds `allow` directives for the following:
- `clippy::identity_op`
- `clippy::unnecessary_cast`

fiat-constify: add clippy allows

---

zeroize/tests/zeroize.rs

This test relies on UB and is flaking out in certain cases: https://github.com/RustCrypto/utils/issues/774
It's unclear if the test failure indicates a genuine bug in the implementation, or is the result of a test with UB.
However, in the meantime it shouldn't block users who would just like the test suite to run reliably.

zeroize: add `#[ignore]` to flaky CString test

---

Cargo.lock
zeroize/Cargo.toml
zeroize/src/lib.rs

This (optional) feature implements Serialize/Deserialize for Zeroizing when
the inner type implements these traits. This makes it possible to use
Zeroizing in serde contexts.
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

feat: add serde support

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml

- Optional `serde` support ([#780])
[#780]: https://github.com/RustCrypto/utils/pull/780

zeroize v1.5.7

---

cpufeatures/Cargo.toml

Fixes https://github.com/RustCrypto/utils/issues/788. I'm not sure if all targets need to be updated or just `aarch64` (probably just `aarch64`). If so I can remove bumping the version in other targets
HWCAP_* consts for aarch64 were added to libc in https://github.com/rust-lang/libc/pull/2172 and released in [v0.2.95](https://github.com/rust-lang/libc/releases/tag/0.2.95)
It looks like these constants were imported into cpufeatures in https://github.com/RustCrypto/utils/pull/456 and the libc version was bumped to 0.2.95 accordingly. But then in https://github.com/RustCrypto/utils/pull/732 libc version was bumped down. I think the minimum libc version should be bumped back up to 0.2.95 to include these constants

Update libc deps to 0.2.95

---

zeroize/derive/src/lib.rs
zeroize/tests/zeroize_derive.rs

I don't actually know how to test this, because you can't access the dropped memory of a `Box` without a custom allocator I suppose (EDIT: same for `Vec`). So I just made sure it builds.
I'm also not a 100% sure my assumption is correct, but as far as I understand any `Drop` bounds are truly unnecessary in this case.
Fixes #786.

Fix deriving `ZeroizeOnDrop` on items with generics

---

cpufeatures/src/lib.rs
cpufeatures/src/miri.rs

~~[miri](https://github.com/rust-lang/miri) is an interpreter and doesn't support inline assembly. Fortunately, we already have precedent for an x86 target without cpuid: SGX. Treat miri like SGX: only features that are enabled at compile time are available at run time.~~
[miri](https://github.com/rust-lang/miri) is an interpreter, and though it tries to emulate the target CPU it does not support any target features.
Fixes #778.

cpufeatures: Disable all target features under miri

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/x86.rs

We must do it according to the [Intel manual](https://www.intel.com/content/dam/develop/external/us/en/documents/36945). Our non-conformance has [caused](https://github.com/RustCrypto/hashes/pull/386) issues with the `sha2` crate.
Strictly speaking, during detection of AVX we also should use XGETBV to check whether XMM and YMM states are enabled by OS, but I think it's worth to do it later in a separate PR.
cc @brocaar

cpufeatures: check AVX availability when detecting AVX2 and FMA

---

.github/workflows/zeroize.yml
zeroize/src/aarch64.rs

The required APIs are stable as of Rust 1.59.
Unfortunately we can't yet enable it by default as the overall crate's MSRV is 1.51. It will be possible if we bump MSRV to >=1.59.
This commit also adjusts the CI job to test the `aarch64` feature works on `1.59.0` and `stable` compilers.

zeroize: note `aarch64` crate feature works on stable

---

block-padding/src/lib.rs

I noticed a small typo while reading the documentation.

Small typo in docstring

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/x86.rs

Relevant issues: https://github.com/rust-lang/rust/issues/101346, https://github.com/RustCrypto/stream-ciphers/issues/304
Forbidding inlining of the CPUID intrinsics should force compiler to generate correct assembly since it can not perform incorrect optimization with register reuse.

Add workaround for CPUID bug in std

---

block-buffer/src/lib.rs
block-buffer/tests/mod.rs

try_new creates BlockBuffer or returns an error.
Requested in https://github.com/RustCrypto/traits/pull/1078

block-buffer: add try_new method

---

Cargo.lock
block-buffer/CHANGELOG.md
block-buffer/Cargo.toml

- `try_new` method ([#799])
[#799]: https://github.com/RustCrypto/utils/pull/799

Release block-buffer v0.10.3

---

cpufeatures/CHANGELOG.md

The reason for yanking is the CPUID intrinsics bug which was worked around in v0.2.5.

cpufeatures: yank old v0.2.x releases

---

zeroize/derive/CHANGELOG.md

These releases misspecified their version requirement for `synstructure` and are not compatible with releases prior to v0.12.2.
This breaks `-Z minimal-versions` builds for downstream dependencies.
See dalek-cryptography/ed25519-dalek#219

zeroize_derive: yank 1.1.1, 1.2.0, 1.2.1, 1.2.2

---

Cargo.lock
zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml

- Deriving `ZeroizeOnDrop` on items with generics ([#787])
[#787]: https://github.com/RustCrypto/utils/pull/787

zeroize_derive v1.3.3

---

.github/workflows/cpufeatures.yml
.github/workflows/zeroize.yml

There are currently build failures on `master` for `cpufeatures` and `zeroize`, which test on macOS runners:
https://github.com/RustCrypto/utils/actions/runs/3733690805/jobs/6594187401#step:6:13
= note: ld: in /Users/runner/.rustup/toolchains/1.40.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgetopts-1988d9ef7be544ff.rlib(rust.metadata.bin), archive member 'rust.metadata.bin' with length 198423 is not mach-o or llvm bitcode file '/Users/runner/.rustup/toolchains/1.40.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgetopts-1988d9ef7be544ff.rlib'
It seems these older rustc versions do not support linking with the latest macOS compiler toolchain.
The build on `stable` works, so we can continue to test macOS, just not that these two crates are MSRV compatible on …

CI: disable macOS builds on MSRV

---

dbl/src/lib.rs

This fixes a small typo I noticed.

Fix typo in documentation of `dbl`

---

Cargo.lock
cmov/Cargo.toml
cmov/src/aarch64.rs
cmov/src/lib.rs
cmov/src/portable.rs
cmov/src/x86.rs
cmov/tests/lib.rs

Replaces the existing API with a `Cmov` trait which is impl'd for all of the unsigned integer types.
On x86 platforms this adds support for using both EAX and RAX integer operands.
Support for `u8` is impl'd generically via upcasting, and support for `u128` is impl'd generically by splitting the value into two `u64`s and doing two selections.
Platform-by-platform support is now split into `aarch64`, `x86`, and `portable` backend modules.

cmov: redesigned trait-based API

---

fiat-constify/src/main.rs

The link to the utils repo should be angle-bracketed to make the rustdoc linter happy.

fiat-constify: fix rustdoc lint warning in output

---

.github/workflows/workspace.yml
fiat-constify/src/main.rs
inout/src/inout.rs

This is primarily to unblock #839

CI: use Rust 1.67 for `clippy`

---

.github/workflows/cmov.yml
Cargo.lock
cmov/CHANGELOG.md
cmov/Cargo.toml
cmov/README.md
cmov/src/lib.rs

- `Condition` alias for `u8` ([#830])
- Redesigned trait-based API ([#830])
- Built around a `Cmov` trait
- Trait is impl'd for `u8`, `u16`, `u32`, `u64`, `u128`
- Accepts a `Condition` (i.e. `u8`) as a predicate
- MSRV 1.60 ([#839])
[#830]: https://github.com/RustCrypto/utils/pull/830
[#839]: https://github.com/RustCrypto/utils/pull/839

cmov v0.2.0

---

.github/workflows/cpufeatures.yml
.github/workflows/zeroize.yml
Cargo.lock
block-buffer/CHANGELOG.md
block-buffer/Cargo.toml
block-buffer/src/lib.rs

Closes #843 
The current `master` tracks `block-buffer v0.11`, so post-v0.10.3 releases will be tracked in the `block-buffer/v0.10` branch.

block-buffer: fix unsoundness triggered by zero block size

---

cpufeatures/Cargo.toml
cpufeatures/src/aarch64.rs

This PR adds support for dynamic feature detection on iOS, watchOS, and tvOS, bringing full support to all of Apple's platforms and following up https://github.com/RustCrypto/utils/pull/435.
I'm not entirely sure what the previous comment about lack of `sysctl(3)` support meant, FWIW. iOS supports the same kernel calls that macOS does (for the most part, but especially low-level ones like this) because they're based on the same kernel and, more importantly, the function appears in the public headers inside each platform's SDK.
To confirm/prove that there wasn't any problematic filtering occurring on iOS, I ran these changes on both the iOS simulator and on a real device (iPad Pro 3rd gen). The results make sense AFAICT because this specific model runs a full-fledged M1 processor in it. …

cpufeatures: Support dynamic feature detection on iOS and derivative platforms

---

.github/workflows/blobby.yml
.github/workflows/block-buffer.yml
.github/workflows/block-padding.yml
.github/workflows/cmov.yml
.github/workflows/cpufeatures.yml
.github/workflows/dbl.yml
.github/workflows/fiat-constify.yml
.github/workflows/hex-literal.yml
.github/workflows/hybrid-array.yml
.github/workflows/inout.yml
.github/workflows/opaque-debug.yml
.github/workflows/workspace.yml
.github/workflows/zeroize.yml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/utils/actions/runs/4456456880:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …

Replace unmaintained actions-rs/* actions in CI workflows

---

cmov/src/lib.rs

I'm not too sure if these `cfg`s are the most optimised - feel free to request any adjustments!
Currently `miri` doesn't have support for inline ASM, so any usage of the `cmov` crate (on inline ASM-utilising architectures) causes a failure. I scoured `miri`'s docs for a solution, but this also works.
I have tested these changes locally - all architectures build, and `miri` works too!
I'm unsure whether or not this should be included in the README, it wasn't [here](https://github.com/RustCrypto/utils/commit/8e74aa5b4bd2d1f7c3428649b7c9578592f10f0b) but it's no hassle either way.

cmov: add `miri` support by forcing the `portable` backend

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/README.md
cpufeatures/src/lib.rs

- Support dynamic feature detection on iOS and derivative platforms ([#848])
- Support for detecting AVX-512 target features ([#862])
[#848]: https://github.com/RustCrypto/utils/issues/848
[#862]: https://github.com/RustCrypto/utils/pull/862

cpufeatures v0.2.6

---

.github/workflows/zeroize.yml
Cargo.lock
zeroize/Cargo.toml
zeroize/README.md
zeroize/derive/Cargo.toml
zeroize/derive/README.md

Since #858 needs MSRV 1.56 anyway, this goes ahead and bumps the edition for `zeroize` and `zeroize_derive` to 2021.
This also lets us remove a number of hacks in CI, including commented-out tests.

zeroize: 2021 edition upgrade; MSRV 1.56

---

Cargo.lock
cmov/Cargo.toml
cmov/src/aarch64.rs
cmov/src/lib.rs
cmov/src/portable.rs
cmov/src/x86.rs
cmov/tests/lib.rs

This makes it easier to implement the `Cmov` trait for foreign types.
It additionally makes the `value` argument an `&Self` reference, which should make it easier to impl the trait for non-`Copy` types where it's desirable to avoid a move.
Note: breaking change

cmov: make `Cmov::cmovz` a provided method

---

Cargo.lock
fiat-constify/Cargo.toml
fiat-constify/src/main.rs
zeroize/derive/Cargo.toml
zeroize/derive/src/lib.rs

This won't test cleanly or go in yet, as it depends on synstructure updating to support syn-2 (this is [trivial](https://github.com/mystor/synstructure/pull/57), but hasn't landed yet).
Uploading the code for review in case you have feedback before it's landable.

Update to syn-2

---

.github/workflows/cmov.yml
.github/workflows/zeroize.yml

Adds PPC32, which should be useful for checking that any optional ASM-based features will still work on platforms where ASM has not yet been stabilized.

zeroize: add `cross` tests to CI

---

Cargo.lock
zeroize/Cargo.toml
zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml
zeroize/derive/LICENSE-MIT

- 2021 edition upgrade; MSRV 1.56 ([#869])
- Bump `syn` to v2 ([#858])
- `synstructure` dependency ([#858])
[#858]: https://github.com/RustCrypto/utils/pull/858
[#869]: https://github.com/RustCrypto/utils/pull/869

zeroize_derive v1.4.0

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml

- Impl `Zeroize` for `core::num::Wrapping` ([#818])
- Impl `Zeroize` for `str` and `Box<str>` ([#842])
- 2021 edition upgrade; MSRV 1.56 ([#869])
[#818]: https://github.com/RustCrypto/utils/pull/818
[#842]: https://github.com/RustCrypto/utils/pull/842
[#869]: https://github.com/RustCrypto/utils/pull/869

zeroize v1.6.0

---

Cargo.lock
zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml

- Do not automatically inject bounds ([#879])
[#879]: https://github.com/RustCrypto/utils/pull/879

zeroize_derive v1.4.1

---

zeroize/derive/Cargo.toml
zeroize/derive/src/lib.rs
zeroize/tests/zeroize_derive.rs

The where clauses I was previously injecting *were* load bearing, but they needed to be filtered for skipped fields.
Fixes #878

zeroize_derive: Inject where clauses; skip unused

---

Cargo.lock
zeroize/derive/CHANGELOG.md
zeroize/derive/Cargo.toml

- Inject where clauses; skip unused ([#882])
[#882]: https://github.com/RustCrypto/utils/pull/882

zeroize_derive v1.4.2

---

cmov/src/aarch64.rs
cmov/src/lib.rs
cmov/src/portable.rs
cmov/src/x86.rs
cmov/tests/lib.rs

Following on from #872, this is heavily a WIP, and a lot of the implementation is sub-par.
I cleaned the macro usage up, although it seemed intentionally designed that way so I can revert those changes if needs be.
I'm not 100% sure on the portable implementation, nor am I sure that `EOR` is the most suitable instruction for Aarch64 (but it works).
Additionally, I think we should note that direct usage won't provide the most ideal outcomes - I believe the compiler will still attempt to optimise in some places, although I'm not 100% sure on that. Using this crate within `subtle` (or similar) sounds the most suitable to me.
Adding benches via `dudect_bencher` could be very handy, just as a sanity-check (but I'd be happy to hear any ideas regarding that).
Edit: in hindsight, I'm not sure …

cmov: implement constant-time equality comparisons

---

block-padding/CHANGELOG.md
block-padding/Cargo.toml
block-padding/src/lib.rs

Closes #860 
The existing `Padding` trait is automatically implemented using `raw_pad` and `raw_unpad` from `RawPadding`.
Because all implementations are inlined, code generation for users of `Padding` is the same as before. I checked this by defining some functions (see below) to monomorphize the `Padding` trait for an instance of `Padding` and comparing the generated assembly (using e.g. `cargo asm block_padding::concrete_pad --build-type release`) before and after this change. I observed no differences.
``` rust
pub fn concrete_pad(block: &mut Block<generic_array::typenum::U128>, pos: usize) {
Iso7816::pad(block, pos);
}
pub fn concrete_unpad(block: &mut Block<generic_array::typenum::U128>) -> Result<&[u8], UnpadError> {
Iso7816::unpad(block)
}
```
I'm not attached to `RawPadding` as a …

Add RawPadding trait to block-padding for padding blocks of arbitrary size

---

Cargo.lock
hex-literal/CHANGELOG.md
hex-literal/Cargo.toml

- Disallow comments inside hex strings ([#816])
- Migrate to 2021 edition and bump MSRV to 1.57 ([#816])
- Use CTFE instead of proc macro ([#816])
[#816]: https://github.com/RustCrypto/utils/pull/816

hex-literal: release v0.4.0

---

Cargo.lock
cmov/CHANGELOG.md
cmov/Cargo.toml

- `miri` support by forcing the `portable` backend ([#864])
- Constant-time equality comparisons ([#873])
- Make `Cmov::cmovz` a provided method ([#871])
- Builds on `x86` (32-bit) targets ([#863])
[#863]: https://github.com/RustCrypto/utils/pull/863
[#864]: https://github.com/RustCrypto/utils/pull/864
[#871]: https://github.com/RustCrypto/utils/pull/881
[#873]: https://github.com/RustCrypto/utils/pull/883

cmov v0.3.0

---

.github/workflows/blobby.yml
.github/workflows/block-buffer.yml
.github/workflows/block-padding.yml
.github/workflows/cmov.yml
.github/workflows/cpufeatures.yml
.github/workflows/dbl.yml
.github/workflows/fiat-constify.yml
.github/workflows/hex-literal.yml
.github/workflows/hybrid-array.yml
.github/workflows/inout.yml
.github/workflows/opaque-debug.yml
.github/workflows/security-audit.yml
.github/workflows/workspace.yml
.github/workflows/zeroize.yml

For most jobs we only need to read the contents to run tests. But I am not sure which permissions should be used for the security audit job. I think it should be something like:
```yaml
permissions:
contents: read
checks: write
issues: write
```
For now I will leave the default permissions.
Relevant issues: https://github.com/actions-rs/audit-check/issues/218, https://github.com/actions-rs/audit-check/issues/220

Use minimal permissions for CI jobs

---

Cargo.lock
hex-literal/CHANGELOG.md
hex-literal/Cargo.toml
hex-literal/README.md
hex-literal/src/lib.rs

The previous version may not be const evaluated as [noticed](https://github.com/RustCrypto/utils/pull/816#discussion_r1157499048) by @Nugine.

hex-literal: enforce const evaluation

---

cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml

- Support freestanding/UEFI `x86` targets ([#821])
[#821]: https://github.com/RustCrypto/utils/issues/821

cpufeatures v0.2.7

---

.github/workflows/hybrid-array.yml
Cargo.lock
hybrid-array/Cargo.toml
hybrid-array/README.md
hybrid-array/src/lib.rs

It's quite annoying to have to add a generic parameter to `ArraySize`, particularly when notating it in bounds.
GATs provide a solution to this problem, moving the type parameter to the associated type so bounds are simply `N: ArraySize`.

hybrid-array: use GATs for `ArraySize`

---

zeroize/src/aarch64.rs
zeroize/src/lib.rs

If I understood it correctly the `zeroize` crate has now overall a MSRV of 1.56 since https://github.com/RustCrypto/utils/pull/869. There were just two places left where it was still stated that the MSRV is 1.51.

zeroize: Update comments on MSRV

---

hybrid-array/src/lib.rs

Adds a set of reference conversions to `Array<T, U>` as well as the `ArrayOps` trait:
- `&Array<T, U>`: `From<&[T, N]>` + TryFrom<&[T]>
- `&mut Array<T, U>`: `From<&mut [T, N]>` + `TryFrom<&mut [T]>`
The implementation uses an unsafe pointer cast to convert a slice into the corresponding reference newtype.
Additionally it adds the following panicking inherent methods to `Array<T, U>` to ease migrating code based on `GenericArray`:
- `Array::ref_from_slice`: alternative to `GenericArray::from_slice`
- `Array::ref_from_mut_slice`: alternative to `GenericArray::from_mut_slice`
- `Array::clone_from_slice`: alternative to `GenericArray::clone_from_slice`
These methods are marked with TODOs to deprecate them before a final v0.2.0 release, however for now they're not deprecate to ease a …

hybrid-array: reference conversion support

---

hybrid-array/src/lib.rs

This makes porting existing `generic-array` code easier, and also means deref coercion will allow `&Array<T, _>` to deref to `&[T]`, making it usable anywhere a slice is.

hybrid-array: change `Deref::Target` to `[T]`

---

hybrid-array/src/lib.rs

It's used when checking the lengths of slices match an array size prior to using a pointer cast to convert types.
If someone were to make their own `typenum::Unsigned` type and impl `ArraySize` for it with an `ArrayType` whose size does not match `Unsigned::USIZE`, that would be UB.
Really `ArraySize` is not intended for downstream crates to impl anyway, but making it an `unsafe trait` at least captures the UB potential.
Additionally this adds more debug checks to `check_slice_length` to ensure that if there is a length mismatch, it's at least caught in debug builds.

hybrid-array: make `ArraySize` an `unsafe trait`

---

hybrid-array/src/lib.rs

Renames the following methods of the `ArrayOps` trait:
- `as_array_ref` -> `as_core_array`
- `as_array_mut` -> `as_mut_core_array`
- `from_core_array_ref` -> `ref_from_core_array`
- `from_core_array_mut` -> `ref_from_mut_core_array`
- `map` -> `map_to_core_array`

hybrid-array: rename `ArrayOps` methods

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/x86.rs

cpufeatures: check OS register support

---

cpufeatures/src/x86.rs

This has only been tested on my machine (R7 7950X), but the values seem correct to me - I was following [this chart](https://en.wikichip.org/wiki/x86/avx-512#Detection) and a PR from the other month.

cpufeatures: add support for `avx512vbmi(2)`

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml

- Support for `avx512vbmi` and `avx512vbmi2` target features ([#926])
[#926]: https://github.com/RustCrypto/utils/pull/926

cpufeatures: release v0.2.9

---

cmov/src/aarch64.rs
cmov/src/lib.rs
cmov/src/portable.rs
cmov/src/x86.rs

Related to [this comment](https://github.com/RustCrypto/utils/issues/920#issuecomment-1606146848), this PR changes all `[inline(always)]` to just `[inline]`.
I'm not sure what the scope of these changes should be as I imagine there's a lot of them, but it's a start.

cmov: use `#[inline]` instead of `#[inline(always)]`

---

zeroize/src/aarch64.rs
zeroize/src/x86.rs

Remove unnecessary cfgs on SIMD type impls

---

.github/workflows/zeroize.yml
README.md
zeroize/Cargo.toml
zeroize/README.md
zeroize/src/aarch64.rs
zeroize/src/lib.rs

This PR contains a few things:
1. Implements Zeroize for `MaybeUninit<Z>` for any `Z`.
2.  Uses a const to create the `1` in   `impl_zeroize_for_non_zero` instead of using `unsafe` there.
3. For `Vec<T>` uses `spare_capacity_mut()` instead of manually creating a slice via unsafe. (This bumps MSRV to 1.60, So I understand if it's not wanted right now)
4. Uses the existing macros to generate more implementations.
5. On `CString` use `into_bytes_with_nul` instead of `into_bytes` as the latter pops the null character for no reason.
6. Use the `ptr::cast` method to cast types
If anything here is controversial I can drop some of the commits and/or split this into multiple PRs.

Zeroize: Implement Zeroize for MaybeUninit, and remove some unsafe

---

Cargo.lock
wycheproof2blb/CHANGELOG.md
wycheproof2blb/Cargo.toml

`serde v1.0.172` and later include pre-compiled binaries which is a security hazard. So until the decision gets reverted, I believe it's worth to pin upper version of `serde`. This approach may cause issues if a different crate in someone's dependency tree will depend on a post-1.0.172 version of `serde`, but I think this issue is small enough when compared to the security concerns. Also, a number of other crates in the ecosystem follow this approach, so we are not alone.
More information and discussion about the `serde` change can be found in https://github.com/serde-rs/serde/issues/2538.

Pin upper version of serde to <1.0.172

---

block-padding/src/lib.rs

`slice.fill()` has been stabilized since rust 1.50 (`block-padding` currently require rust >= 1.56).

block-padding: replace block iteration with fill()

---

Cargo.lock
wycheproof2blb/CHANGELOG.md
wycheproof2blb/Cargo.toml

In 1.0.184 `serde` was [un-blobbed](https://github.com/serde-rs/serde/releases/tag/v1.0.184). To prevent accidental pulling of the blobbed versions 1.0.184 will be used as a min version.
Relevant PR: #933

Set min version of serde to 1.0.184

---

cpufeatures/README.md

Support for `avx512vbmi` and `avx512vbmi2` was added in #926, but the README was not updated appropriately.

cpufeatures: add missing target features to readme

---

hybrid-array/src/lib.rs

Switches from derived impls of `Clone` and `Copy` to handwritten ones which use the minimal required bounds for the underlying types.

hybrid-array: looser `Clone` and `Copy` bounds on `Array`

---

hybrid-array/src/lib.rs

Removes the `U::ArrayType<T>: Debug` bound, leveraging the `Debug` impl on `[T]` instead.

hybrid-array: looser `Debug` impl on `Array`

---

hybrid-array/src/lib.rs

The target type on the pointer cast is incorrect: it should be `*const Array<T, U>` but instead it's `*const &Array<T, U>`.
This is a memory safety error. It was introduced in #904 and thus has never been in anything but v0.2 prereleases, so it isn't particularly security-relevant.

hybrid-array: fix reference conversions

---

hybrid-array/src/lib.rs

Allows for converting a hybrid array to its inner core array.

hybrid-array: impl `From<Array<T, U>>` for `[T; N]`

---

hybrid-array/src/lib.rs

Switches from a special case impl per size to one which is generic over all array sizes, similar to what #956 did for the owning implementation of `IntoIterator`.

hybrid-array: impl `IntoIterator` for references to all `ArraySize`s

---

hybrid-array/src/lib.rs

These traits add convenient methods for concatenation and splitting. The size of the result is calculated in the compile time.
This implementation was inspired by `GenericArray` implementation of relevant traits.
This change is necessary for https://github.com/RustCrypto/traits/pull/1078

hybrid-array: implement concat and split methods

---

Cargo.lock
cmov/CHANGELOG.md
cmov/Cargo.toml

- `CmovEq` impl for slices ([#954])
- Use `#[inline]` instead of `#[inline(always)]` ([#924])
- `CmovEq` now invokes XOR within the ASM block ([#925])
[#924]: https://github.com/RustCrypto/utils/pull/924
[#925]: https://github.com/RustCrypto/utils/pull/925
[#954]: https://github.com/RustCrypto/utils/pull/954

cmov v0.3.1

---

hybrid-array/src/lib.rs

This change is needed to test https://github.com/RustCrypto/traits/pull/1361

Cherry-pick to migrate-to-hybrid-array branch concat and split

---

.github/workflows/cpufeatures.yml
Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml

- LoongArch64 target support ([#955])
[#955]: https://github.com/RustCrypto/utils/pull/955

cpufeatures: release v0.2.10

---

cpufeatures/src/aarch64.rs
cpufeatures/src/lib.rs
cpufeatures/tests/aarch64.rs

Only supported on Linux platform with HWCAP_SM3 | HWCAP_SM4.
fix #970 .

cpufeatures: add support of armv8.2-a sm3, sm4 (#970)

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml

- Support for AArch64's `sm4` target feature ([#972])
[#972]: https://github.com/RustCrypto/utils/pull/972

cpufeatures: release v0.2.11

---

.github/workflows/block-buffer.yml
.github/workflows/block-padding.yml
.github/workflows/dbl.yml
.github/workflows/inout.yml
Cargo.lock
Cargo.toml
block-buffer/Cargo.toml
block-buffer/README.md
block-buffer/src/lib.rs
block-buffer/src/sealed.rs
block-buffer/tests/mod.rs
block-padding/Cargo.toml
block-padding/src/lib.rs
dbl/Cargo.toml
dbl/src/lib.rs
inout/Cargo.toml
inout/src/inout.rs
inout/src/inout_buf.rs
inout/src/reserved.rs

Builds on RustCrypto/traits#1319.
Migrates the following crates away from using `generic-array` to using `hybrid-array` instead:
- `block-buffer`
- `block-padding`
- `dbl`
- `inout`

Migrate to `hybrid-array`; MSRV 1.65

---

hybrid-array/src/impls.rs
hybrid-array/src/lib.rs
hybrid-array/tests/mod.rs

As discussed [here](https://github.com/RustCrypto/traits/pull/1358#discussion_r1373973004) these functions will allow us to remove a bit of `unsafe` from downstream crates and it will be useful for users who would like to work with blocks of data.

hybrid-array: add slice_as_chunks(_mut) methods, minor refactoring

---

hybrid-array/src/lib.rs

The `'static` bound is already [present](https://docs.rs/typenum/latest/typenum/marker_traits/trait.Unsigned.html) in the `Unsigned` trait since `typenum` v1.14.
Closes #975

hybrid-array: tweak ArraySize docs, remove static bound

---

wycheproof2blb/src/ecdsa.rs
wycheproof2blb/src/main.rs

Adds support for extracting secp521r1 test vectors from Wycheproof, in order to test the `p521` crate.

wycheproof2blb: secp521r1 support

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml

- Impl `Zeroize` for `MaybeUninit` ([#900])
- Unnecessary `cfg`s on SIMD type impls ([#930])
[#900]: https://github.com/RustCrypto/utils/pull/900
[#930]: https://github.com/RustCrypto/utils/pull/930

zeroize v1.6.1

---

Cargo.toml

Gets rid of this warning:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```

Cargo.toml: set `workspace.resolver = "2"`

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml

- Bump MSRV to 1.60 ([#900])
[#900]: https://github.com/RustCrypto/utils/pull/900

zeroize v1.7.0

---

.github/workflows/fiat-constify.yml
fiat-constify/Cargo.toml
fiat-constify/README.md

This is a simple command line utility intended for internal use only.
There's no need to have an MSRV policy around it, and having one was breaking the build of #984

fiat-constify: remove MSRV

---

Cargo.lock
hybrid-array/CHANGELOG.md
hybrid-array/Cargo.toml
hybrid-array/README.md
hybrid-array/src/impls.rs

Let me know if you wanna feature gate this.

hybrid-array: Impl Zeroize for Array

---

cmov/src/lib.rs

cmovnz moves when condition is **not** 0. Basically just a typo.

Fix cmovnz documentation

---

fiat-constify/Cargo.toml
fiat-constify/src/main.rs
fiat-constify/src/outputs.rs
fiat-constify/src/type_registry.rs

fiat-crypto introduced new types instead of just type aliases, this causes the generated code to no longer compile. This is a breaking change since this will no longer compile code generated by fiat-crypto version < 0.0.21
Tests:
* All `fiat-crypto` rust crate can be compiled using rustc
```rust
#[inline]
pub fn fiat_p224_divstep(out1: &mut u64, out2: &mut [u64; 5], out3: &mut [u64; 5], out4: &mut [u64; 4], out5: &mut [u64; 4], arg1: u64, arg2: &[u64; 5], arg3: &[u64; 5], arg4: &[u64; 4], arg5: &[u64; 4]) {
// <snipped>
*out1 = x112;
out2[0] = x7;
out2[1] = x8;
out2[2] = x9;
out2[3] = x10;
out2[4] = x11;
out3[0] = x114;
out3[1] = x115;
out3[2] = x116;
out3[3] = x117;
out3[4] = x118;
out4[0] = x119;
out4[1] = x120;
out4[2] = x121;
out4[3] = x122;
out5[0] = x123;
out5[1] = x124;
out5[2] = …
```

fiat-constify: Fix implementation for fiat-crypto >= 0.0.21

---

Cargo.lock
hybrid-array/src/lib.rs
hybrid-array/tests/mod.rs

It's longer than `Array<u8, _>` and provides little value other than needless indirection.
Closes #987

hybrid-array: remove `ByteArray` alias

---

Cargo.lock
Cargo.toml
block-padding/Cargo.toml
dbl/Cargo.toml
inout/Cargo.toml

Due to a cyclical dependency with `crypto-common` this has to be done as part of a 2-part process and can't be done at release-time.

Bump `hybrid-array` depenency to v0.2.0-pre.6

---

hybrid-array/src/impls.rs
hybrid-array/src/lib.rs

...and asserts as much by impl'ing the trait for core arrays.
The main notable change is bounding on `AsRef<[T]>`/`AsMut<[T]>`, which core arrays do impl, however they *don't* actually impl `AsRef<[T; N]>`/`AsMut<[T; N]>`.
Those impls are retained on `Array`, but new ones added for `AsRef<[T]>`/`AsMut<[T]>`, providing better parity with core arrays.

hybrid-array: make `ArrayOps` better resemble core arrays

---

hybrid-array/src/lib.rs

Adds thunks for the `slice_to_chunks`/`slice_to_chunks_mut` static functions as provided methods of the `SliceOps` trait.

Add `SliceOps::as_array_chunks(_mut)`

---

hybrid-array/src/impls.rs
hybrid-array/src/lib.rs

Adds a type for associating a `typenum`-based size with a given array type, which can be either `[T; N]` or `Array<T, U>`.
This subsumes the previous `IntoArray` trait, which can be replaced by a simple `Into` bound instead.

hybrid-array: `AssociatedArraySize` trait

---

hybrid-array/src/lib.rs

Specifically to `ArraySize::ArrayType`

hybrid-array: add `From<Array<T, U>>` bound to `ArraySize`

---

hybrid-array/src/lib.rs

Also impls `FromFn` for `Array`.
Now that this trait has a single method, it can be renamed to match that single method's functionality.
It also changes the implementation to use `core::array::from_fn` now that it's stable.

hybrid-array: rename `ArrayExt` to `FromFn`

---

hybrid-array/src/impls.rs
hybrid-array/src/lib.rs

Uses a const generic implementation bounded on `ArrayOps<T, N>` rather than using a macro to write a separate one for each array size.

Impl `From<Array<T, U>>` for `[T; N]` generically

---

hybrid-array/src/lib.rs

If the latter is named specifically as an associated type, then it can simply be moved out of the `Array` newtype.

hybrid-array: simplify `From<Array<T, U>>` impl for `[T; N]`

---

hybrid-array/src/lib.rs

Provides more effective debugging in the event the wrong size is used

hybrid-array: use `assert_ne!` in `slice_as_chunks(_mut)`

---

hybrid-array/src/lib.rs
hybrid-array/tests/mod.rs

Adds a type alias for `Array` which uses const generics instead of `typenum`.

hybrid-array: add `ArrayN` type alias

---

hybrid-array/src/lib.rs

hybrid-array: remove `Array::from_slice`

---

hybrid-array/src/lib.rs

hybrid-array: use `Clone` bound for `TryFrom<&[T; N]>`

---

hybrid-array/README.md

There are several usages of `unsafe` now

hybrid-array: remove `unsafe: forbidden` badge from README.md

---

hybrid-array/src/lib.rs

This reverts commit 49e9d6869c8333522ef598c11c6f048f9475ec6c.
The extra bounds turn out to be rather problematic with e.g. `crypto-common`, so revert this even though `check_slice_length` is a hack.

Revert "hybrid-array: get rid of `check_slice_length` (#1020)"

---

hybrid-array/src/lib.rs

Simplified comparisons with core arrays

hybrid-array: add `PartialEq` impls for core array

---

hybrid-array/src/lib.rs

...instead of `AsRef`/`AsMut`, which allows inference to work for those traits.
Notably `[T; N]` doesn't impl `AsRef`/`AsMut` for itself, only for slices, so this is more consistent.

hybrid-array: use `From` for `Array`<->`[T; N]` reference conversions

---

Cargo.lock
Cargo.toml
block-padding/Cargo.toml
dbl/Cargo.toml
inout/Cargo.toml

Due to a cyclical dependency with `crypto-common` this has to be done as part of a 2-part process and can't be done at release-time.

Bump `hybrid-array` depenency to v0.2.0-pre.7

---

Cargo.lock
block-buffer/Cargo.toml
block-padding/Cargo.toml
dbl/Cargo.toml
inout/Cargo.toml

Cuts the following prereleases, which include a bump to `hybrid-array` v0.2.0-pre.7:
- `block-buffer` v0.11.0-pre.2
- `block-padding` v0.4.0-pre.2
- `dbl` v0.4.0-pre.2
- `inout` v0.2.0-pre.2

Release *-pre.2 prereleases

---

hybrid-array/src/lib.rs

These were removed in #1026 for more consistency with core arrays and so inference would work by eliminating overlapping impls.
However, `generic-array` provides these impls, which makes removing them problematic when migrating `generic-array`-based code, so it's easier to keep them around, even if it breaks inference due to overlapping impls.

hybrid-array: re-add `AsRef<[T; N]>`/`AsMut<[T; N]>` impls

---

cpufeatures/src/x86.rs

This PR adds support for the following features for x86_64:
`GFNI`
`VAES`
`VPCLMULQDQ`
`AVX512_BITALG`
`AVX512_VPOPCNTDQ`

cpufeatures: support more AVX512-related features

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml

- Support for x86-64 AVX-512 target features: `gfni`, `vaes`, `vpclmulqdq`, `avx512bitalg`, `avx512vpopcntdq` ([#1035])
[#1035]: https://github.com/RustCrypto/utils/pull/1035

Release cpufeatures v0.2.12

---

hybrid-array/src/lib.rs

Use the same names `GenericArray` did:
- `Array::from_slice`
- `Array::from_mut_slice`
The goal is to deprecate these methods anyway, so we should use the same names as `GenericArray` to ease migrating off of it.

hybrid-array: remove `Array::ref_*` prefixes

---

Cargo.lock
hybrid-array/Cargo.toml
hybrid-array/src/lib.rs
hybrid-array/src/sizes.rs

The added methods will help to remove `unsafe` functions like [this](https://github.com/RustCrypto/hashes/blob/f5a07e6bfdd69afda90769587b6b88debd1a5b84/md5/src/lib.rs#L114-L120).
Closes #951

hybrid-array: add slice cast methods to ArrayOps

---

hybrid-array/src/lib.rs
hybrid-array/tests/mod.rs

For feature parity with `GenericArray`.
It would be nice to have a fallible version of this which returns an error instead of panicking on length mismatch, but we'd first need to add `FromFn::try_from_fn` or thereabouts.
This is enough to cover the immediate use cases in the meantime.

hybrid-array: add `FromIterator` impl

---

Cargo.lock
hybrid-array/Cargo.toml

I'm happy enough with the current state of `hybrid-array` that I think we can commit to making only additive changes from here on.
Upgrading it with the current `=0.2.0-pre.N` requirements is a huge pain, and it seems like we may want to add some more features before release.
So if we call this an "RC" we can change the requirements to be `0.2.0-rc.0` without the leading `=` which will allow us to publish new versions with additive feature changes without having to republish everything else (which is what will currently be required)

hybrid-array v0.2.0-rc.0

---

Cargo.lock
block-buffer/Cargo.toml
block-padding/Cargo.toml
dbl/Cargo.toml
inout/Cargo.toml

Bumps the following dependencies:
- `crypto-common` => v0.2.0-pre.4
- `hybrid-array` => v0.2.0-rc.0
Also prepares the following releases:
- `block-buffer` v0.11.0-pre.4
- `block-padding` v0.4.0-pre.4
- `dbl` v0.4.0-pre.4
- `inout` v0.2.0-pre.4

Bump `crypto-common` and `hybrid-array`

---

zeroize/src/lib.rs

For reducing zeroize code in chacha20, as per @newpavlov's [suggestion](https://github.com/RustCrypto/stream-ciphers/issues/336#issuecomment-1880346171)
I'm unsure of the name, documentation, and whether it should be a method instead of a function.

Adding a zeroize function for flat types

---

opaque-debug/src/lib.rs
opaque-debug/tests/mod.rs

This PR adds support for opaque debug impls on structs with generics. It does not support structs with trait bounds as working with them using macro_rules! is not possible as far as I can tell.
It also wasn't obvious how to avoid exporting the `format_params` macro which is required to build the format template without a trailing comma eg `Foo<T, U, V,> { ... }`.

feat(opaque-debug): support generics

---

.github/workflows/workspace.yml
.github/workflows/zeroize.yml
zeroize/Cargo.toml
zeroize/src/x86.rs

This PR adds `Zeroize` impls for `__m512` types. It also bumps the MSRV to `1.72.0` since that was when these types were stabilized (according to godbolt).

Add Zeroize impls for __m512 types

---

zeroize/src/aarch64.rs
zeroize/src/lib.rs
zeroize/src/x86.rs

Replaces manual `doc_cfg` annotations with automatic ones powered by `doc_auto_cfg`.

zeroize: use `doc_auto_cfg`

---

zeroize/Cargo.toml
zeroize/src/lib.rs

Now that our MSRV is high enough we don't need to feature-gate `aarch64` support anymore, and instead it can be always-on when compiling for `aarch64` targets.
The `aarch64` feature is retained as a noop since removing it would be a breaking change.

zeroize: always enable AArch64 support

---

cpufeatures/src/aarch64.rs

The "sm4" token wasn't being handled. To fix the bleeding, this adds it but hardcoded to disabled.
See build failure here: https://github.com/RustCrypto/utils/actions/runs/8818083683/job/24206057206?pr=1065
```
Compiling cpufeatures v0.2.12 (/Users/runner/work/utils/utils/cpufeatures)
error: no rules expected the token `"sm4"`
--> tests/aarch64.rs:5:51
|
5   | cpufeatures::new!(armcaps, "aes", "sha2", "sha3", "sm4");
|                                                   ^^^^^ no rules expected this token in macro call
|
note: while trying to match `"aes"`
--> /Users/runner/work/utils/utils/cpufeatures/src/aarch64.rs:107:6
|
107 |     ("aes") => {
|      ^^^^^
```

cpufeatures: fix macOS build

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml
zeroize/README.md
zeroize/src/lib.rs

- Unsafe `zeroize_flat_type` function ([#1045])
- `Zeroize` impls for `__m512` types on `x86`/`x86_64` targets ([#1052])
- Bump MSRV to 1.72 ([#1052])
- Always enable AArch64 support ([#1064])
- Nightly warnings ([#1055])
[#1045]: https://github.com/RustCrypto/utils/pull/1045
[#1052]: https://github.com/RustCrypto/utils/pull/1052
[#1055]: https://github.com/RustCrypto/utils/pull/1055
[#1064]: https://github.com/RustCrypto/utils/pull/1064

zeroize 1.8.0

---

zeroize/CHANGELOG.md

It was yanked over MSRV-related concerns. See #1067.

zeroize: note v1.8.0 was yanked in CHANGELOG.md

---

.github/workflows/zeroize.yml
zeroize/Cargo.toml
zeroize/README.md
zeroize/src/x86.rs

Restores MSRV 1.60 by feature-gating AVX-512 support on x86(_64) targets, which is the only thing which required the previous MSRV of 1.72.
Using a generic `simd` name (unlike the previous `aarch64` feature name) allows us to provide more feature-gated SIMD register support in the future without giving architecture-specific targets to each one, while also avoiding MSRV bumps in such cases.
When we bump overall MSRV, such support can be moved out from under the feature gate.

zeroize: feature-gate AVX-512 under `simd`; MSRV 1.60

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml

- Feature-gate AVX-512 support under `simd`; restores MSRV 1.60 ([#1073])
[#1073]: https://github.com/RustCrypto/utils/pull/1073

zeroize v1.8.1

---

zeroize/Cargo.toml
zeroize_derive/Cargo.toml

Also fixes it for `zeroize_derive`.
Now:
- `repository` points to a valid git repository: the `utils` repo
- `homepage` points to the GitHub URL for the crate's subdirectory

zeroize: fix `homepage`/`repository` in Cargo.toml

---

cmov/Cargo.toml
fiat-constify/Cargo.toml

This tweaks the `repository` fields in Cargo metadata in order to use the correct (i.e. git clonable) URL. The existing GitHub webUI URLs for each package have been retained and moved to `homepage` fields.

cargo: point `repository` metadata to clonable URLs

---

block-buffer/src/lib.rs
block-buffer/src/sealed.rs
block-buffer/tests/mod.rs

Marks private `unchecked` methods as `unsafe` and documents their safety requirements. Adds `SAFETY` comment for all `unsafe` uses. Use of `copy_nonoverlapping` ensures that compiler will not generate unreachable panic branches. Use of `MaybeUninit` removes unnecessary initialization and helps to test that we do not read bytes which were not written by us.
The code successfully passes MIRI tests, but I plan to test this implementation more thoroughly later.

block-buffer: improve safety comments, use `MaybeUninit` for internal buffer

---

cmov/src/portable.rs

`size_of` is now in the prelude, so on older versions it needs to be imported explicitly.

cmov: fix `size_of` warning on Rust 1.80

---

wycheproof2blb/src/ecdsa.rs
wycheproof2blb/src/main.rs

parsing ecdsa_secp256k1_sha256_p1363_test.json

wycheproof2blb: secp256k1 with P1363 format

---

Cargo.lock
cpufeatures/Cargo.toml
cpufeatures/src/lib.rs

This change should make generated code slightly more efficient after `STORAGE` was initialized.

cpufeatures: use `#[cold]` for initialization code

---

cpufeatures/src/aarch64.rs

Adds support for detecting Data Independent Timing (DIT) support which is available on Apple silicon (e.g. M1/M2/M3).
This uses the `hw.optional.arm.FEAT_DIT` sysctl for detection.
For more information, see:
https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Enable-DIT-for-constant-time-cryptographic-operations

cpufeatures: add support for DIT detection on Apple silicon

---

cpufeatures/src/aarch64.rs

On Linux, availability of FEAT_DIT can be detected via `HWCAP_DIT`.

cpufeatures: add DIT support for AArch64 Linux targets

---

.github/workflows/aarch64-dit.yml
.github/workflows/workspace.yml
Cargo.lock
Cargo.toml
aarch64-dit/CHANGELOG.md
aarch64-dit/Cargo.toml
aarch64-dit/LICENSE-APACHE
aarch64-dit/LICENSE-MIT
aarch64-dit/README.md
aarch64-dit/src/lib.rs

Adds a crate with wrappers for the Data-Independent Timing (DIT) feature of AArch64 CPUs.
The implementation is largely a translation of Apple's guide of how to write wrappers for enabling/disabling DIT: https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Enable-DIT-for-constant-time-cryptographic-operations
It would be nice to wrap that all up into an RAII guard which can first use `cpufeatures` to check for `FEAT_DIT` and, if available, enable it for the current thread, while also first querying the processor status register and restoring the previous state on `Drop`, which is necessary for proper nested usage of DIT.
But for now, this just wraps the barebones functionality in an `unsafe` API.

aarch64-dit: initial crate

---

aarch64-dit/Cargo.toml

This hopefully allows the docs to generate on docs.rs.
Closes #1106

aarch64-dit: set docs.rs default-target

---

aarch64-dit/Cargo.toml
aarch64-dit/src/lib.rs

Removes the previous low-level unsafe API and wraps it up instead in a safe API which automatically performs runtime CPU feature detection and RAII guards for enabling DIT and restoring its previous state when done.

aarch64-dit: safe, high-level API

---

.github/workflows/block-buffer.yml
.github/workflows/block-padding.yml
.github/workflows/dbl.yml
.github/workflows/inout.yml
.github/workflows/workspace.yml
Cargo.lock
block-buffer/Cargo.toml
block-padding/CHANGELOG.md
block-padding/Cargo.toml
dbl/CHANGELOG.md
dbl/Cargo.toml
inout/CHANGELOG.md
inout/Cargo.toml

This also bumps MSRV to 1.81 for `block-buffer`, `block-padding`, `dbl`, and `inout`, following the MSRV bump in `hybrid-array`.

Bump `hybrid-array` to v0.2.0-rc.10

---

block-padding/Cargo.toml
block-padding/src/lib.rs
inout/Cargo.toml
inout/src/errors.rs
inout/src/lib.rs

Leverages the `error_in_core` feature stabilized in Rust 1.81 to allow `Error` trait impls in `no_std` contexts.
This was the only dependency on `std`, so this also removes the `std` feature, which is no longer necessary.

block-padding+inout: remove `std` feature

---

inout/src/errors.rs
inout/src/lib.rs
inout/src/reserved.rs

Removes manual rustdoc feature annotations and performs them automatically

inout: use `doc_auto_cfg`

---

inout/Cargo.toml

We need to instruct it to build with the `block-padding` feature to ensure that's properly documented.
This commit re-adds `all-features = true`

inout: re-add `package.metadata.docs.rs` to Cargo.toml

---

Cargo.lock
block-buffer/Cargo.toml
block-padding/Cargo.toml
dbl/Cargo.toml
inout/Cargo.toml

Cuts new `-rc.*` releases of the following:
- `block-buffer` v0.11.0-rc.3
- `block-padding` v0.4.0-rc.2
- `dbl` v0.4.0-rc.1
- `inout` v0.2.0-rc.2
These all depend on `hybrid-array` v0.2 (final)

Cut new release candidates

---

Cargo.lock
Cargo.toml

Compiling the crate on non-AArch64 targets results in a compilation error, so having it in workspace can be problematic on other target arches.

Exclude `aarch64-dit` from root workspace

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/src/x86.rs

The check was too conservative and caused false negatives on some targets. This change follows the `is_x86_feature_detected!` macro (see: https://docs.rs/crate/std_detect/latest/source/src/detect/os/x86.rs).
Closes #1129

cpufeatures: relax XSAVE checks

---

inout/CHANGELOG.md
inout/src/inout.rs
inout/src/inout_buf.rs
inout/src/reserved.rs

`InOutBuf::into_out` already exists.

inout: add `InOut::into_out` and `InOutBufReserved::into_out`

---

cpufeatures/CHANGELOG.md
cpufeatures/src/x86.rs

Previously we were using an empty string for `target_os` to indicate freestanding targets which is incorrect. We should use `none` instead.
Closes #1136

cpufeatures: fix cfg for freestanding x86 targets

---

cpufeatures/Cargo.toml

On AArch64, we link the `libc` crate to provide access to system call wrappers which can query available CPU features from the kernel, since those calls are protected on that CPU architecture.
We don't need `std` though, and it seems we're inadvertently linking it on Linux, Android, and macOS.

cpufeatures: don't link `std` when linking `libc`

---

Cargo.lock
cpufeatures/CHANGELOG.md
cpufeatures/Cargo.toml
cpufeatures/LICENSE-MIT
cpufeatures/README.md

- Don't link `std` when linking `libc` ([#1142])
[#1142]: https://github.com/RustCrypto/utils/pull/1142

cpufeatures: release v0.2.17

---

inout/CHANGELOG.md
inout/Cargo.toml
inout/src/lib.rs
inout/src/reserved.rs

This PR is a backport of #1147 for inout v0.1.
Fixes #1146

inout: fix `InOutBufReserved::get_out_len`

---

hybrid-array/README.md

The crate was moved into a separate repository more than a year ago, so I think we can remove the notification directory.

Remove the hybrid-array dir

---

hex-literal/src/lib.rs

Also includes minor code tweaks.

hex-literal: use `const` block to force const promotion

---

Cargo.lock
hex-literal/CHANGELOG.md
hex-literal/Cargo.toml

- Edition changed to 2024 and MSRV bumped to 1.85 ([#1149])
- Relax MSRV policy and allow MSRV bumps in patch releases
[#1149]: https://github.com/RustCrypto/utils/pull/1149

hex-literal: release v1.0.0

---

Cargo.toml

Cargo does not respect this setting in Cargo.toml, instead it has to be provided in config.toml. I [requested](https://internals.rust-lang.org/t/22439) for this to change, so until the situation is clarified the setting is removed.

Temporary remove `resolver.incompatible-rust-versions`

---

cpufeatures/src/x86.rs

The workaround is no longer needed since we have bumped MSRV to 1.85.

cpufeatures: remove `#[inline(never)]` workaround for CPUID intrinsics

---

inout/CHANGELOG.md
inout/src/inout.rs
inout/src/inout_buf.rs

The methods can be useful in cases where we want to support `inout` APIs, but algorithm implementation supports only the in-place mode.

inout: add `into_out_with_copied_in` methods

---

inout/src/inout.rs
inout/tests/split-inout.rs

This is meant to be used in https://github.com/RustCrypto/AEADs/pull/667

inout: split a buffer in equal chunks

---

.github/workflows/digest-io.yml
Cargo.lock
Cargo.toml
digest-io/CHANGELOG.md
digest-io/Cargo.toml
digest-io/LICENSE-APACHE
digest-io/LICENSE-MIT
digest-io/README.md
digest-io/src/io_wrapper.rs
digest-io/src/lib.rs
digest-io/src/reader.rs
digest-io/src/writer.rs

This crate contains `std::io`-compatibility wrappers which are moved from the `digest` crate.

digest-io: initial implementation

---

README.md
digest-io/Cargo.toml
digest-io/README.md

Fixes badges in the crate README and moves hash crates used in examples to dev dependencies.

digest-io: minor fixes

---

zeroize/Cargo.toml

The flag is passed automatically by docs.rs.

zeroize: remove explicit passing of the docsrs configuration flag

---

.github/workflows/dbl.yml

The `minimal-versions` job was missing the `uses` key

dbl: fix CI

---

cpufeatures/README.md
cpufeatures/src/x86.rs

https://en.wikipedia.org/wiki/CPUID#EAX=7,_ECX=1:_Extended_Features
Add supports of `sha512`, `sm3` and `sm4` in x86.
Rust support: https://github.com/rust-lang/rust/issues/126624

cpufeatures: x86 support of sha512, sm3, sm4

---

Cargo.lock
fiat-constify/Cargo.toml

Also adds `publish = "false"` as this tool is not intended for release (ideally we can eventually get rid of it), but the version bump denotes a major notable change to the codegen

fiat-constify v0.1.0

---

zeroize/Cargo.toml

This is useful for `-Z minimal-versions` to ensure derived code builds without warnings on recent Rust versions, which complain about the earlier custom derive:
```
error: non-local `impl` definition, `impl` blocks should be written at the same level as their item
```

zeroize: bump `zeroize_derive` dep to v1.4

---

Cargo.lock
dbl/CHANGELOG.md
dbl/Cargo.toml
dbl/README.md

- Migrated from `generic-array` to `hybrid-array` ([#944])
- Edition changed to 2024 and MSRV bumped to 1.85 ([#1149])
- Seal the `Dbl` trait ([#1198])
Closes #1077 
[#944]: https://github.com/RustCrypto/utils/pull/944
[#1149]: https://github.com/RustCrypto/utils/pull/1149
[#1198]: https://github.com/RustCrypto/utils/pull/1198

dbl v0.4.0

---

cpufeatures/Cargo.toml

I propose that, on aarch64-linux-android, cpufeatures/Cargo.toml should use `cfg(all(...))` instead of full target name "aarch64-linux-android", just like the other target-specific deps on libc do.
Motivation for this change is building with a custom rustc target like "aarch64-foobar-linux-android". Cargo/Rustc (and consequently the #[cfg] check in src/aarch64.rs) correctly interpret that as target_arch="aarch64", target_os="android", but the current Cargo.toml fails to include the dependency on libc.

cpufeatures: use cfg() to detect aarch64 android instead of [target.aarch64-linux-android]

---

Cargo.lock
block-buffer/Cargo.toml
block-padding/Cargo.toml
inout/Cargo.toml

Releases the following:
- `block-buffer` v0.11.0-rc.5
- `block-padding` v0.4.0-rc.4
- `inout` v0.2.0-rc.6

Cut prereleases with `hybrid-array` v0.4 support

---

Cargo.lock
blobby/Cargo.toml

This includes the binary file format changes included in #1207
This release is to remove the various `[patch.crates-io]` we have to support the new format.

blobby: 0.4.0-pre.1

---

block-buffer/src/sealed.rs

This PR simplifies implementations and removes `unsafe` by leveraging `Array::slice_as_chunks`. The resulting code is still panic-free, as can be seen here: https://rust.godbolt.org/z/43xMT3ExP

block-buffer: improve `split_blocks` implementations

---

Cargo.lock
zeroize/CHANGELOG.md
zeroize/Cargo.toml

v1.8.2. was released in #1229.
Also bumps the version down to `1.9.0-pre` to note that v1.9.0 has not yet been released.

zeroize: add v1.8.2 changelog entry

---

Cargo.lock
block-padding/CHANGELOG.md
block-padding/Cargo.toml
inout/Cargo.toml

- `Padding::pad_detached` method ([#1225])
- Migrated from `generic-array` to `hybrid-array` ([#944])
- Edition changed to 2024 and MSRV bumped to 1.85 ([#1149])
- Merged `RawPadding` and `Padding` traits ([#1217])
- Renamed `UnpadError` to `Error` ([#1225])
- `Block` type alias ([#1217])
- `PadType` enum and associated type on the `Padding` trait ([#1225])
[#944]: https://github.com/RustCrypto/utils/pull/944
[#1149]: https://github.com/RustCrypto/utils/pull/1149
[#1217]: https://github.com/RustCrypto/utils/pull/1217
[#1225]: https://github.com/RustCrypto/utils/pull/1225

Release block-padding v0.4.0

---

Cargo.lock
inout/CHANGELOG.md
inout/Cargo.toml

- Migrated from `generic-array` to `hybrid-array` ([#944])
- Edition changed to 2024 and MSRV bumped to 1.85 ([#1149])
- `InOut::into_out` and `InOutBufReserved::into_out` methods ([#1132])
- `InOutBufReserved::split_reserved` method ([#1133])
- `InOut::into_out_with_copied_in` and `InOutBuf::into_out_with_copied_in` methods ([#1169])
[#944]: https://github.com/RustCrypto/utils/pull/944
[#1132]: https://github.com/RustCrypto/utils/pull/1132
[#1133]: https://github.com/RustCrypto/utils/pull/1133
[#1149]: https://github.com/RustCrypto/utils/pull/1149
[#1169]: https://github.com/RustCrypto/utils/pull/1169

Release inout v0.2.0
