RustCrypto/utils

block-buffer/src/lib.rs
This is needed in some variants where the prefix of the length padding is a
`0x01` byte, for example in [Tiger Hash](https://en.wikipedia.org/wiki/Tiger_(cryptography)).
I left `0x80` as the default padding byte for backwards compatibility.
Note that this is required for RustCrypto/hashes#50.
=> Add len_padding_with to specify the prefix byte

block-buffer/src/lib.rs
Needed for Skein. Description in comments.
=> Lazy flush

hex-literal/hex-literal-impl/src/lib.rs
Loop is more readable as a 'while let'.
Thanks for creating this crypto related projects. Very interesting :)
=> Use while let

block-padding/src/lib.rs
Currently bad input causes panic.
=> fix substraction overflow

block-padding/src/lib.rs
Added a NoPadding option for block-padding crate. Relates to https://github.com/RustCrypto/utils/issues/34
Note that I had to reimplement the `pad()` function for this one since the original function created a new block when `data_size % block_size == 0`, which is not intended for this mode. This makes the pad_block function useless, but I kept it instead of using an `unreachable!()` since the function is publicly exposed, giving it the same implementation as `pad`.
=> NoPadding for block-padding

collectable/CHANGELOG.md, collectable/Cargo.toml
=> collectable v0.0.1

.github/workflows/blobby.yml, .github/workflows/block-buffer.yml, .github/workflows/block-padding.yml, .github/workflows/cpuid-bool.yml, .github/workflows/dbl.yml, .github/workflows/opaque-debug.yml
Without this option MSRV runs can use incorrect version.
=> CI add "override: true"

cpuid-bool/LICENSE-APACHE, cpuid-bool/LICENSE-MIT
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
=> Add LICENSE-* into cpuid-bool

Cargo.lock, const-oid/CHANGELOG.md, const-oid/Cargo.toml, const-oid/src/lib.rs
=> const-oid 0.1.0

.github/workflows/workspace.yml
CI config wasn't overriding the Rust toolchain
=> Fix clippy errors

pkcs8/src/asn1.rs
Rejects some cases that were previously accepted but MUST be rejected by ASN.1 DER when parsing lengths:
- When the length is between 0 and 127, the short form of length must be used
- Ensures a minimum number of octets are used by disallowing 3-byte lengths for values less than 256 (per X.690 Section 10.1)
- Rejects a leading length byte of 128 (0x80), as it is reserved for indefinite lengths (per X.690 Section 8.1.3.6.1)
Note: per RFC 5208, PKCS#8 is technically BER encoded (despite what things like the OpenSSL's `-outform DER` would lead you to believe).
Despite that, this PR attempts to accept only valid DER, as that's how PKCS#8 keys are typically described and hopefully, in practice, most PKCS#8 keys *are* actually valid DER. We can revisit this if it turns out we're rejecting valid …
=> pkcs8: length handling improvements

Cargo.lock, pkcs8/CHANGELOG.md, pkcs8/Cargo.toml, pkcs8/src/lib.rs
=> pkcs8 v0.1.0

Cargo.lock, const-oid/CHANGELOG.md, const-oid/Cargo.toml, const-oid/src/lib.rs
- Improve description in Cargo.toml/README.md (#110)
[#110]: https://github.com/RustCrypto/utils/pull/110
=> const-oid v0.3.3

pkcs8/src/algorithm.rs, pkcs8/src/asn1/encoder.rs, pkcs8/src/private_key_info.rs, pkcs8/src/spki.rs, pkcs8/tests/public_key.rs
Support for encoding SubjectPublicKeyInfo as ASN.1 DER
=> pkcs8: SPKI encoder

pkcs8/src/lib.rs, pkcs8/src/traits.rs
Traits for serializing private and public keys
=> pkcs8: add `ToPrivateKey`/`ToPublicKey` traits

pkcs8/src/lib.rs
Expands the intro section of the rustdoc
=> pkcs8: rustdoc improvements

Cargo.lock, pkcs8/CHANGELOG.md, pkcs8/Cargo.toml, pkcs8/src/lib.rs
- `AlgorithmParameters` enum ([#138])
[#138]: https://github.com/RustCrypto/utils/pull/138
=> pkcs8 v0.3.0

const-oid/src/lib.rs
Replaces the previous `AsRef<[u32]>` impl on `ObjectIdentifier` with an iterator type: `Nodes`.
This allows for using a more compact internal representation for the `ObjectIdentifier` struct, because it no longer requires that the first two nodes are represented as u32 (they can be encoded in a single byte).
This is preliminary work for moving to such a layout.
=> const-oid: add `Nodes` iterator

const-oid/src/lib.rs
Stores the first two arcs of an OID as a `u8`, rather than `[u32; 2]`.
The range of values of these nodes is constrained such that this is possible. The ASN.1 DER encoding takes advantage of this optimization.
With this change, it's possible to store an additional two arcs in the same amount of space on 64-bit architectures (48-bytes).
=> const-oid: layout optimization

const-oid/src/lib.rs
Adds documentation for arc length limits (3..=12) along with a `MIN_LENGTH` constant, which is used throughout the implementation now.
Also adds additional tests and fixes a big with parsing underlength OIDs from strings.
=> const-oid: refactor and improve arc length limits

const-oid/README.md
Make sure the title fits on crates.io
=> const-oid: README.md header fixup

der/src/decode.rs, pkcs8/src/algorithm.rs
Also uses the new support to simplify the `AlgorithmParameters` decoder.
=> der: support for decoding `OPTIONAL` fields

der/src/decoder.rs, der/src/encoder.rs
The `Length` type provides checked arithmetic with overflow handling and simple conversions to `usize`.
This simplifies the previously verbose boilerplate for doing checked arithmetic using `checked_add`, and also encapsulates values such that it precludes performing unchecked arithmetic.
=> der: use `Length` as the position cursor for `Decoder`/`Encoder`

der/src/asn1.rs, der/src/asn1/boolean.rs, der/src/asn1/integer.rs, der/src/lib.rs
Adds support for the ASN.1 `BOOLEAN` type.
=> der: add `Boolean` type

der/src/tag.rs
Context-specific types are specific to a particular structure.
They're needed to properly implement PKCS#8 decoding.
=> der: add support for context-specific types

der/src/asn1/any.rs, der/src/decoder.rs, der/src/encoder.rs, der/src/length.rs, der/src/traits.rs
Adds an inherent method for converting `Length` to `usize`.
=> der: add `Length::to_usize`

Cargo.lock, der/CHANGELOG.md, der/Cargo.toml, der/derive/CHANGELOG.md, der/derive/Cargo.toml, der/src/lib.rs, pkcs8/Cargo.toml
=> der v0.1.0

Cargo.lock, der/Cargo.toml, der/src/lib.rs, pkcs8/Cargo.toml
=> der v0.2.0-pre

der/src/asn1/big_uint.rs
Allows parsing of `BigUInt` values up to 512-bytes long.
This corresponds to 4096-bits and should be sufficient for practical cryptographic purposes (at least for now).
=> der: expand allowed BigUInt sizes; additional comments

der/src/asn1/integer.rs, der/src/lib.rs
Adds basic support for encoding/decoding signed 16-bit integers.
=> der: i16 support

Cargo.lock, b64ct/CHANGELOG.md, b64ct/Cargo.toml
=> b64ct v0.1.0

b64ct/src/lib.rs
Number of `unsafe` blocks in `decode_in_place` can be minimized to two. Panic-free property was verified using [godbolt](https://rust.godbolt.org/z/jTYjzq). To be extra safe I also run the tests via MIRI and it didn't find any issues. We probably should add MIRI runs to CI for every crate which contains `unsafe` code. Also it could be worth to run fuzzing after #205 will be fixed.
This modification also significantly improves performance of `decode_in_place` from 150 MB/s to 205 MB/s on my laptop, now it's slightly faster than `decode` which results in 200 MB/s.
=> b64ct: modify decode_in_place to be panic-free

.github/workflows/b64ct.yml, b64ct/src/lib.rs, b64ct/tests/mod.rs
=> b64ct: fix overflow bug, add alloc-gated tests

Cargo.lock, base64ct/Cargo.toml, pkcs8/Cargo.toml
Fix version number and description
=> base64ct: fixups

base64ct/src/lib.rs
This commit contains a number of small improvements:
- Removes the remaining data-dependent branches
- Fixes overflow in padded `decoded_len` calculation
- Replaces use of `isize` with `i16` (the specific needed type)
- Extracts methods for constant-time pseudo-branch operations
=> base64ct: cleanups

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/LICENSE-MIT, base64ct/src/lib.rs, pkcs8/Cargo.toml
=> base64ct v0.1.0

base64ct/src/encoding.rs, base64ct/src/encoding/crypt.rs, base64ct/src/lib.rs, base64ct/tests/crypt.rs, base64ct/tests/standard.rs
=> base64ct: crypt(3) encoding

der/derive/src/lib.rs, der/src/asn1.rs, der/src/asn1/printable_string.rs, der/src/asn1/utf8_string.rs, der/src/decoder.rs, der/src/encoder.rs, der/src/error.rs, der/src/lib.rs, der/src/str_slice.rs, der/src/tag.rs
Also impls `Decodable`/`Encodable` traits for `str`
=> der: add support for PrintableString and Utf8String

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/lib.rs, der/derive/src/sequence.rs, der/derive/src/types.rs, der/src/asn1/any.rs, der/src/decoder.rs, der/src/encoder.rs, der/src/lib.rs, der/tests/derive.rs
Adds custom derive support for mapping ASN.1 `CHOICE` to Rust enums.
=> der_derive: custom derive support for enums

Cargo.lock, der/derive/CHANGELOG.md, der/derive/Cargo.toml
- Custom derive support for enums ([#254])
[#254]: https://github.com/RustCrypto/utils/pull/254
=> der_derive v0.2.1

Cargo.lock, der/CHANGELOG.md, der/Cargo.toml, der/src/lib.rs
- `Any::is_null` method ([#262])
- Deprecate `Any::null` method ([#262])
[#262]: https://github.com/RustCrypto/utils/pull/262
=> der v0.2.4

Cargo.lock, pkcs8/Cargo.toml, pkcs8/tests/encrypted_private_key.rs, spki/CHANGELOG.md, spki/Cargo.toml, spki/src/lib.rs
=> spki v0.1.0

der/src/error.rs
Adds an error variant for propagating OIDs as discussed in #272.
It's a little awkward for a few reasons:
- There's already a unit `ErrorKind::Oid` variant. Since that's a little ambiguous, there's also a TODO to rename that variant to the more specific `ErrorKind::OidMalformed` in the next breaking release
- Since `const-oid` is an optional dependency, the presence of this variant is conditional upon that feature being enabled. Fortunately the whole enum is marked `#[non_exhaustive]` (which is what even allows adding new variants in a non-breaking way), so hopefully the conditional presence of this variant won't be too problematic for downstream users
The other problem is the `ObjectIdentifier` type is somewhat large. On a 64-bit machine, this increases the size of the overall `Error` …
=> der: add ErrorKind::OidInvalid

spki/src/algorithm.rs
Returning a result makes for simpler error handling with `?` in functions which also return a `Result`, and also makes it possible to propagate incompatible DER tags encountered when using these methods.
=> spki: return `Result` from `AlgorithmIdentifier::params_*`

Cargo.lock, pkcs5/Cargo.toml, pkcs8/Cargo.toml, spki/CHANGELOG.md, spki/Cargo.toml, spki/src/lib.rs
- Return `Result` from `AlgorithmIdentifier::params_*` ([#274])
[#274]: https://github.com/RustCrypto/utils/pull/274
=> spki v0.2.0

der/src/encoder.rs, pkcs5/src/lib.rs, pkcs5/src/pbes1.rs, pkcs5/src/pbes2.rs, pkcs5/tests/pbes2.rs
Adds support for re-encoding the parsed `Scheme` as ASN.1 DER
=> pkcs5: add encoding support

Cargo.lock, pkcs5/CHANGELOG.md, pkcs5/Cargo.toml, pkcs5/src/lib.rs, pkcs8/Cargo.toml
=> pkcs5 v0.1.0

der/derive/src/choice.rs, der/derive/src/lib.rs, der/derive/src/message.rs, der/src/lib.rs, der/tests/derive.rs
Adds support for deriving the `Choice` macro for enums
=> der_derive: custom derive support for `Choice`

Cargo.lock, der/derive/CHANGELOG.md, der/derive/Cargo.toml
- Custom derive support for the `Choice` trait ([#296])
[#296]: https://github.com/RustCrypto/utils/pull/296
=> der_derive v0.2.2

Cargo.lock, der/CHANGELOG.md, der/Cargo.toml, der/src/lib.rs, spki/Cargo.toml
- `Choice` trait ([#295])
[#295]: https://github.com/RustCrypto/utils/pull/295
=> der v0.2.8

Cargo.lock, spki/CHANGELOG.md, spki/Cargo.toml, spki/src/lib.rs
- Impl `Choice` for `AlgorithmParameters` ([#295])
[#295]: https://github.com/RustCrypto/utils/pull/295
=> spki v0.2.1

Cargo.lock, pkcs5/CHANGELOG.md, pkcs5/Cargo.toml, pkcs5/src/lib.rs
- Encryption support ([#293], [#295])
[#293]: https://github.com/RustCrypto/utils/pull/293
[#295]: https://github.com/RustCrypto/utils/pull/295
=> pkcs5 v0.1.1

der/src/asn1/oid.rs
The `ObjectIdentifier` type has a small maximum length when serialized as BER/DER, presently defined as `const_oid::MAX_LENGTH`.
This means that unless this were raised significantly such that it were larger than `der::Length::max()`, infallible conversions should always be possible. Such conversions are significantly more convenient, especially in code that heavily leverages OIDs (e.g. the `pkcs5` crate)
This change opts for a potential panic in the event that the invariant `const_oid::MAX_LEN <= Length::max()` were to be violated, but permits an infallible conversion. Presently the invariant has the constants `23 < 65535`. In the future it would probably make sense to *raise* `Length::max`.
To ensure future changes/refactorings don't cause this invariant to be violated, this commit …
=> der: make From<ObjectIdentifier> conversion for Any infallible

base64ct/README.md, base64ct/src/lib.rs, der/src/lib.rs
=> base64ct: properly note MSRV

der/src/asn1/utf8_string.rs, der/src/lib.rs
=> der: impl Decode/Encoded/Tagged for String

der/src/asn1/big_uint.rs, der/src/decoder.rs, der/src/lib.rs
The same concept can be expressed as `Unsigned + NonZero`
=> der: remove BigUIntSize

der/src/length.rs
In PR #349, the internal representation of a Length was changed from `u16` to `u32` to make it easier to support documents larger than 64kB in the future.
However, this added a `Length::max` invariant which wasn't getting properly checked when doing addition (it was only checking that the primitive `u32` integer addition operation didn't overflow).
This change adds a test which captured the overflow behavior, and also adds a `TryFrom<u32> for Length` impl which ensures the length is in-range, and changes the rest of the length-related code to always use this impl to instantiate `Length` types.
=> der: fix length overflow on add

const-oid/README.md
Add more information about root OID namespaces
=> const-oid: expand README.md

block-buffer/src/buffer.rs, block-buffer/src/lazy.rs, block-buffer/src/lib.rs
Also adds the `get_full_block` method to `LazyBlockBuffer`.
=> block-buffer: add block_mode_processing methods

.github/workflows/cpufeatures.yml, Cargo.lock, cpufeatures/CHANGELOG.md, cpufeatures/Cargo.toml, cpufeatures/README.md, cpufeatures/src/lib.rs
=> cpufeatures v0.1.0

cpufeatures/src/lib.rs
Adds a list of the supported target features for each supported CPU type.
=> cpufeatures: document supported target features

cpufeatures/tests/aarch64.rs, cpufeatures/tests/x86.rs
Adds `neon` to the armcaps used in the test
=> cpufeatures: test NEON

.github/workflows/x509.yml, Cargo.lock, Cargo.toml, spki/src/spki.rs, x509/CHANGELOG.md, x509/Cargo.toml, x509/LICENSE-APACHE, x509/LICENSE-MIT, x509/README.md, x509/src/attribute.rs, x509/src/lib.rs, x509/src/rdn.rs, x509/src/time.rs
Initial boilerplate for an `x509` crate.
Also includes some preliminary types:
- `AttributeTypeAndValue`
- `RelativeDistinguishedName`
- `Time`
=> `x509` crate

der/src/decoder.rs
Allows retrieving an OPTIONAL ANY value.
=> der: add Decoder::any_optional() method

der/src/lib.rs, der/src/tag.rs
Adds an enum for the various ASN.1 tag classes.
=> der: add `Class` enum

pkcs8/src/one_asymmetric_key.rs
The ellipsis `...` in the ASN.1 schema was previously interpreted as allowing duplicate fields for `attributes` and `public_key`, however it seems that it should correctly be interpreted as an extension marker which allows extension fields to exist after `attributes` and `public_key`.
It seems that, properly handled, extension fields should be ignored, which we're not doing yet, so this is marked as a TODO for now. The `der` crate should likely provide a better mechanism for skipping over unknown extension fields.
cc @ShadowJonathan
=> pkcs8: add TODO for proper extension handling; fix dups

der/src/asn1/any.rs, der/src/asn1/context_specific.rs
Makes the methods match what are available on `Decoder`.
=> der: update `ContextSpecific` helper methods for `Any`

der/src/asn1/any.rs
Adds error context information from the `Decoder` to the errors that occur in the `Decodable` impl for `Any`.
These show the position offset at the *end* of the erroneous field, which is inaccurate, but better than 0.
Further improving this likely requires some refactoring of the `Decoder::error` method.
=> der: add decoder positions to TryFrom<Any<'a>> decoding

crypto-bigint/src/limb.rs, crypto-bigint/src/uint.rs
Implements `sbb`, `wrapping_sub`, and `checked_sub` functions on `UInt`.
=> crypto-bigint: subtraction support

Cargo.lock, crypto-bigint/CHANGELOG.md, crypto-bigint/Cargo.toml, crypto-bigint/README.md, crypto-bigint/src/lib.rs
=> crypto-bigint v0.1.0

.github/workflows/crypto-bigint.yml, Cargo.lock, crypto-bigint/Cargo.toml, crypto-bigint/src/uint.rs
Adds an optional `Zeroize` impl on `UInt`.
=> crypto-bigint: add `zeroize` feature

der/src/asn1/integer.rs, der/src/asn1/integer/int.rs, der/src/asn1/integer/uint.rs, der/src/lib.rs
This PR is a corollary to #469, but implements signed integer decoding
=> der: const generic signed integer decoder with i32/i64/i128 support

der/src/tag.rs
Inherent method for encoding `Tag` as a byte
=> der: add `Tag::octet`

der/src/asn1/integer/bigint.rs
The encoded length was being miscomputed as it omitted the header.
This commit fixes that and adds a regression test.
=> der: fix UIntBytes encoding regression; add tests

der/src/asn1.rs, der/src/asn1/sequence.rs, der/src/asn1/sequence/iter.rs, der/src/tag/class.rs
Adds an iterator over the encoded values in a homogenously typed `Sequence`.
=> der: add `SequenceIter`

crypto-bigint/src/limb/cmp.rs, crypto-bigint/src/uint.rs, crypto-bigint/src/uint/cmp.rs
=> crypto-bigint: add `Limb::is_odd` and `UInt::is_odd`

Cargo.lock, hex-literal/CHANGELOG.md, hex-literal/Cargo.toml, hex-literal/src/lib.rs
=> hex-literal: accept sequence of literals

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml, pkcs1/src/lib.rs
=> pkcs1 v0.1.0

der/src/asn1/utc_time.rs
Closes #568
UTCTime uses a 2-digit year, ranging from 1950 to 2049.
Encoding for years after 1999 was being mishandled, because they rolled over to 100, resulting in a three digit year when only 2 digits are supported by the encoder.
This commit ensures dates with years 2000 to 2049 are encoded as `0..=49`, and adds tests similar to the ones in `DateTime` which ensure samples within the entire supported range round trip.
=> der: fix encoding for 20xx UTCTime dates

der/src/tag.rs
=> fix: set constructed bit in SET

crypto-bigint/src/uint/from.rs
Adds `const fn` functions `from_uint_array` and `to_uint_array` for converting `UInt` from/to the inner word-sized unsigned integer that the `Limb` newtype wraps.
Also adds `From` trait impls which wrap these functions.
=> crypto-bigint: add `[limb::Inner; LIMBS]` conversions for `UInt`

Cargo.lock, crypto-bigint/CHANGELOG.md, crypto-bigint/Cargo.toml, crypto-bigint/src/lib.rs
- `ConditionallySelectable` impl for `UInt` ([#609])
[#609]: https://github.com/RustCrypto/utils/pull/609
=> crypto-bigint v0.2.5

crypto-bigint/src/limb.rs, crypto-bigint/src/uint.rs, crypto-bigint/src/uint/bits.rs, crypto-bigint/src/uint/shl.rs
Also fixes issue when shift % BIT_SIZE == 0.
=> more tests for shl

crypto-bigint/proptests/Cargo.toml, crypto-bigint/proptests/tests/equivalence.rs, crypto-bigint/src/limb.rs, crypto-bigint/src/limb/cmp.rs, crypto-bigint/src/uint.rs, crypto-bigint/src/uint/bits.rs, crypto-bigint/src/uint/cmp.rs, crypto-bigint/src/uint/div.rs
Implements Constant Time Divide and Remainder (Modulo) operations for BigInt
=> Implement Divide and Modulo crypto-bigint

Cargo.lock, zeroize/derive/CHANGELOG.md, zeroize/derive/Cargo.toml, zeroize/derive/README.md
- Moved to `RustCrypto/utils` repository
=> zeroize_derive v1.2.1

Cargo.lock, zeroize/CHANGELOG.md, zeroize/Cargo.toml, zeroize/README.md, zeroize/derive/README.md, zeroize/src/lib.rs
- Implement `Zeroize` for `NonZeroX`
- Moved to `RustCrypto/utils` repository
=> zeroize v1.4.3

zeroize/src/lib.rs
This adds Zeroize implementations for the following types:
* PhantomData<T>
* PhantomPinned
* Tuples from length 0, to 10
This fixes issue #651.
=> zeroize: Add Zeroize implementations for common types.

block-padding/src/lib.rs
=> Contributing iso-10126

zeroize/src/lib.rs
I've experimented with zeroize v1.5.0-pre and just stumbled upon some minor doc typos.
=> zeroize: Fix docs

zeroize/src/lib.rs
See https://github.com/RustCrypto/utils/pull/709
=> zeroize: Fix typo in doctests

zeroize/derive/src/lib.rs
=> Remove `ZeroizeOnDrop` implementation for `#[zeroize(drop)]`

Cargo.lock
Supersedes #718.
Context: https://github.com/dtolnay/quote/issues/204
=> Bump `quote` to v1.0.11

cpufeatures/Cargo.toml, wycheproof2blb/Cargo.toml, zeroize/derive/Cargo.toml
=> Fix min deps versions

Cargo.lock, cmov/CHANGELOG.md, cmov/Cargo.toml, cmov/README.md
=> cmov v0.1.0

inout/CHANGELOG.md, inout/Cargo.toml, inout/src/inout.rs, inout/src/inout_buf.rs, inout/src/lib.rs, inout/src/reserved.rs
Also improves consistency of pointer handling a bit.
=> inout: release v0.1.3

Cargo.lock, hybrid-array/CHANGELOG.md, hybrid-array/Cargo.toml, hybrid-array/README.md, hybrid-array/src/lib.rs
=> hybrid-array v0.1.0

zeroize/src/lib.rs
Reorder code in terms of precedence; add whitespace
=> zeroize: formatting fixups

Cargo.lock, cpufeatures/CHANGELOG.md, cpufeatures/Cargo.toml
=> cpufeatures: release v0.2.4

zeroize/src/lib.rs
=> zeroize: impl `Zeroize` for `core::num::Wrapping`

cpufeatures/src/lib.rs
Document which target feature names have not yet been stabilized and are subject to change
=> cpufeatures: document unstable target features

zeroize/derive/src/lib.rs, zeroize/tests/zeroize_derive.rs
=> Do not automatically inject bounds

hybrid-array/src/lib.rs
Changes `ArrayOps` to contain only operations that need to know the exact size (as a const generic) of an associated array.
=> hybrid-array: leverage `ArrayExt` to factor more methods onto `Array`

hybrid-array/src/lib.rs
It's leaked through `ArraySize::ArrayType` bounds, and it may potentially be useful to have in the public API.
=> hybrid-array: unseal `ArrayExt`

hybrid-array/src/lib.rs
Uses handwritten impls for the following traits on the `Array` type:
- Debug
- Eq
- Hash
- PartialEq
- PartialOrd
- Ord
The handwritten impls have looser bounds.
=> hybrid-array: use handwritten instead of derived impls

hybrid-array/src/lib.rs
Uses an `IntoIterator` bound on `ArraySize::ArrayType` and forwards the trait invocation to the inner array.
=> hybrid-array: impl `IntoIterator` for all `ArraySize`s

.github/workflows/security-audit.yml
=> Set minimal permissions at security-audit.yml

hybrid-array/src/lib.rs
Factors out a trait which can be impl'd on all three of `[T]`, `[T; N]`, and `Array<T, U>` for operations which don't need a const generic parameter.
=> hybrid-array: factor `SliceOps` out from `ArrayOps`

hybrid-array/src/lib.rs
It can be composed in terms of other features.
=> hybrid-array: get rid of `ArrayExt::from_slice`

hybrid-array/src/lib.rs
It was a hack.
Instead, leverages the `TryFrom` reference conversion to a core array to check the length, then casts from a core array reference.
This requires a few more bounds, but they shouldn't be problematic in practice.
=> hybrid-array: get rid of `check_slice_length`

fiat-constify/src/main.rs
See https://github.com/RustCrypto/elliptic-curves/issues/1034#issuecomment-1992136537
=> Filter out `let mut` declarations

cpufeatures/CHANGELOG.md
- Use `#[cold]` for initialization code ([#1096])
[#1096]: https://github.com/RustCrypto/utils/pull/1096
=> cpufeatures: release v0.2.13

aarch64-dit/src/lib.rs
This is more inlining-friendly
=> aarch64-dit: have `set_dit_enabled` return previous state

Cargo.lock, aarch64-dit/CHANGELOG.md, aarch64-dit/Cargo.toml
=> aarch64-dit v0.1.0

inout/src/reserved.rs
=> inout: fix `InOutBufReserved::get_out_len`

cmov/README.md, dbl/README.md
=> cmov+dbl: add new MSRV policy to README.md
